- meshroom/ui/qml/ImageGallery.qml
- meshroom/ui/qml/Viewer/Viewer3D.qml
- meshroom/ui/reconstruction.py
Spawn a cube on each camera to display which one is selected + allow picking from the 3D view
> [ui] highlight selected view in 3D + 3D picking

- INSTALL.md
- README.md
* readme: add doc to launch meshroom
* install: add AliceVision to pre-requisites + document environment variables
* install: mention Python for Qt + link to beta wheels
* install: mention additional Qt plugins
> Update readme and install doc

- meshroom/nodes/aliceVision/FeatureMatching.py
Add new geometric validation method to filter features matches.
> [nodes] FeatureMatching: add H Growing

- meshroom/core/graph.py
- meshroom/ui/commands.py
- meshroom/ui/graph.py
- meshroom/ui/qml/GraphEditor/AttributeItemDelegate.qml
- meshroom/ui/qml/GraphEditor/AttributePin.qml
- meshroom/ui/qml/GraphEditor/GraphEditor.qml
- meshroom/ui/qml/GraphEditor/Node.qml
- meshroom/ui/reconstruction.py
- tests/test_multiviewPipeline.py
This PR contains changes extracted from #129 that does not break scene/multiview pipeline compatibility.
> Linkable ListAttribute

- meshroom/ui/qml/LiveSfmView.qml
- meshroom/ui/reconstruction.py
> Fix Live Reconstruction mode

- meshroom/nodes/aliceVision/CameraInit.py
Fix images drag&drop when using Python3.
> [nodes] CameraInit: fix broken py3 compatibility + simplify json IO

- meshroom/ui/qml/GraphEditor/GraphEditor.qml
- meshroom/ui/qml/Viewer/DefaultCameraController.qml
- meshroom/ui/qml/Viewer/Viewer2D.qml
Useful when using Meshroom on laptop without an external mouse.
> [ui] mouse: add "Ctrl+Left click" as an alternative to Middle click

- meshroom/nodes/aliceVision/Publish.py
Fix #160 
Use ListAttribute's value to iterate over list elements.
> [nodes] fix Publish node: ListAttribute is not iterable

- meshroom/nodes/aliceVision/Texturing.py
Expose the new texturing options proposed in https://github.com/alicevision/AliceVision/pull/454.
> New texturing options

- meshroom/nodes/aliceVision/ExportMaya.py
Update `ExportMaya` software name  (aliceVision branch dev_exportMeshroomMaya)
> [nodes] `ExportMaya` use `aliceVision_exportMeshroomMaya`

- meshroom/ui/qml/main.qml
avoid potentially ambiguous platform-dependent text
> [ui] ComputeUnsaved: set a more straightforward text for Discard button

- CHANGES.md
- meshroom/__init__.py
- meshroom/ui/app.py
First release of Meshroom - based on AliceVision 2.0.0.
> Release 2018.1.0

- INSTALL.md
Renamed from sensor_width_camera_database.txt to cameraSensors.db
See: https://github.com/alicevision/AliceVision/commit/f2e3702b863d623d82760c4aa5e3a27733964afd#diff-dc9735c79457e576fde21ea129dba0ca
> AliceVision camera database renamed from sensor_width_camera_database.txt

- meshroom/nodes/aliceVision/DepthMap.py
- meshroom/nodes/aliceVision/DepthMapFilter.py
- meshroom/nodes/aliceVision/Meshing.py
See alicevision/AliceVision/pull/539
> [mvs] Add observation angles check

- meshroom/nodes/aliceVision/PrepareDenseScene.py
See alicevision/AliceVision/pull/545
> [nodes] `PrepareDenseScene` Add option `imagesFolders`

- meshroom/nodes/aliceVision/Meshing.py
See alicevision/AliceVision/pull/571
> [nodes] `Meshing` Add option `addLandmarksToTheDensePointCloud`

- meshroom/core/desc.py
- meshroom/core/node.py
- meshroom/nodes/aliceVision/FeatureMatching.py
- tests/test_compatibility.py
- tests/test_multiviewPipeline.py
This PR improves detection of deeper compatibility issues, by adding an additional recursive (taking List/GroupAttributes children into account) exact description matching test when de-serializing a Node.
> Improved compatibility issues detection

- meshroom/nodes/aliceVision/DepthMapFilter.py
See alicevision/AliceVision/pull/604
> [nodes] `DepthMapFilter` Add option `computeNormalMaps`

- meshroom/multiview.py
- meshroom/nodes/aliceVision/ExportColoredPointCloud.py
- meshroom/nodes/aliceVision/MeshFiltering.py
- meshroom/nodes/aliceVision/Meshing.py
- meshroom/nodes/aliceVision/Texturing.py
See alicevision/AliceVision/pull/597
> Dense point cloud

- meshroom/nodes/aliceVision/Texturing.py
See alicevision/AliceVision/pull/596
> [nodes] `Texturing` Add option `useUDIM`

- meshroom/core/__init__.py
- meshroom/submitters/simpleFarmConfig.json
- meshroom/submitters/simpleFarmSubmitter.py
> Packaging and farm submitter without rez

- meshroom/nodes/aliceVision/LDRToHDR.py
Add new LDRToHDR node.
Related to https://github.com/alicevision/AliceVision/pull/613
> [nodes][aliceVision] add LDRToHDR node

- meshroom/nodes/aliceVision/Texturing.py
> [nodes][aliceVision] Texturing: fix outputTextures files extension

- meshroom/nodes/aliceVision/SfMTransform.py
A new "method" called "from_single_camera" has been added since the last release
> [node][alicevision] SfMTransform: update version to 1.1

- meshroom/nodes/aliceVision/LDRToHDR.py
Following the changes in https://github.com/alicevision/AliceVision/pull/675.
> Update LDRToHDR node

- bin/meshroom_photogrammetry
New version of the PR https://github.com/alicevision/meshroom/pull/537.
> Fix meshroom_photogrammetry inputs

- CHANGES.md
- Dockerfile
- INSTALL.md
- meshroom/__init__.py
- meshroom/multiview.py
- requirements.txt
AliceVision 2.2.0 release: https://github.com/alicevision/AliceVision/pull/670
> Release 2019.2.0

- .github/stale.yml
Add automatic detection and marking of stale issues. 
These will be automatically closed after 7 days.
see https://github.com/apps/stale
> Added automatic stale detection and closing for issues

- Dockerfile
- Dockerfile_py2
- meshroom/core/graph.py
- setup.py
> Fix some packaging issues of the release 2019.2.0

- meshroom/core/desc.py
- meshroom/core/node.py
- meshroom/ui/qml/GraphEditor/Node.qml
New update hooks on node description `desc.Node`.
> Invalidation hooks

- .github/stale.yml
> Add exemptLabels

- meshroom/core/desc.py
- meshroom/core/node.py
- tests/test_compatibility.py
Compatibility update of node with list of groups is more tolerent.
Meshroom try now to conform list of groups attributes instead of removing eveything.
Compatibility "detection" is unchanged.
> [core] Compatibility : Improve list of groups update 

- meshroom/nodes/aliceVision/MeshDenoising.py
add title of citation to comments to better find the publication https://dl.acm.org/citation.cfm?id=2818068
> Fix typo, add reference

- meshroom/nodes/aliceVision/StructureFromMotion.py
See https://github.com/alicevision/AliceVision/pull/736 for more details
https://github.com/alicevision/QtAliceVision/pull/4
> [nodes] StructureFromMotion: Add scale as an option

- meshroom/nodes/aliceVision/ImageProcessing.py
Basic node for image processing.  It replaces the cameraDownscale node.
- Downscale images
- Apply exposure compensation, constrast, median filter, sharpen
- Convert image files into another file format.
https://github.com/alicevision/AliceVision/pull/741
> [nodes] new ImageProcessing node

- Dockerfile
- Dockerfile_deps
- docker/qt-installer-noninteractive.qs
- requirements.txt
Split Dockerfile into 2 parts:
- dependencies installation; Qt, Python, all build tools, etc
- build Meshroom plugins and launch cx_freeze to create the Meshroom executable
> [docker] update to qt 5.14 and split build of dependencies

- meshroom/nodes/aliceVision/FeatureMatching.py
Addition of 10 points relative pose solver for geometric validation in FeatureMatching.
See https://github.com/alicevision/AliceVision/pull/474
> [nodes] `FeatureMatching` Add `fundamental_with_distortion` option

- meshroom/ui/app.py
- meshroom/ui/qml/Viewer/FeaturesInfoOverlay.qml
- meshroom/ui/qml/Viewer/Viewer2D.qml
- Fixes #912
- Removes warnings that are not useful
> Fix open recent broken on windows and remove unnecessary warnings

- meshroom/core/attribute.py
When loading very old projects.
> [core] avoid error during project load

- meshroom/nodes/aliceVision/LdrToHdrSampling.py
Rely on https://github.com/alicevision/AliceVision/pull/835
> [nodes] LdrToHdrSampling: add debug option

- meshroom/ui/qml/Viewer3D/MediaLibrary.qml
Fix loading external files in MediaLibrary.
> [ui] Viewer3D: fix loading external files

- meshroom/nodes/aliceVision/ImageProcessing.py
- meshroom/nodes/aliceVision/PanoramaCompositing.py
Paired with the same branch on AliceVision. 
A checkbox to enable/disable graphcut based seams estimation
Based on https://github.com/alicevision/AliceVision/pull/850
> [nodes] PanoramaCompositing: add a new graphcut option to improve seams

- meshroom/nodes/aliceVision/SfMTransfer.py
Enable copy of intrinsics from one sfmdata to another
Based on https://github.com/alicevision/AliceVision/pull/882
> [nodes] SfmTransfer: New option to transfer intrinsics parameters

- meshroom/nodes/aliceVision/LdrToHdrCalibration.py
- meshroom/nodes/aliceVision/PanoramaCompositing.py
- meshroom/nodes/aliceVision/PanoramaWarping.py
Requires https://github.com/alicevision/AliceVision/pull/886
Also declare that LdrToHdrCalibration & PanoramaCompositing are compute intensive nodes
> [nodes] PanoramaWarping: boolean parameter to estimate the resolution automatically

- meshroom/multiview.py
- meshroom/nodes/aliceVision/ImageProcessing.py
Requires on https://github.com/alicevision/AliceVision/pull/890
> [nodes] ImageProcessing: add new option to fix non finite pixels

- meshroom/nodes/aliceVision/LdrToHdrMerge.py
- meshroom/nodes/aliceVision/PanoramaCompositing.py
- meshroom/nodes/aliceVision/PanoramaWarping.py
Requires https://github.com/alicevision/AliceVision/pull/891
> [nodes] Panorama: expose image storageDataType on some nodes

- meshroom/nodes/aliceVision/ImageProcessing.py
- meshroom/nodes/aliceVision/LdrToHdrMerge.py
- meshroom/nodes/aliceVision/PanoramaCompositing.py
- meshroom/nodes/aliceVision/PanoramaWarping.py
- meshroom/ui/components/filepath.py
- meshroom/ui/qml/Viewer3D/MediaLoader.qml
Based on https://github.com/alicevision/AliceVision/pull/896
> [ui] Avoid crash in 3D with large panoramas

- meshroom/nodes/aliceVision/PanoramaInit.py
Based on https://github.com/alicevision/AliceVision/pull/897
> [nodes] PanoramaInit: add debug circle detection option

- meshroom/nodes/aliceVision/LdrToHdrCalibration.py
- meshroom/nodes/aliceVision/LdrToHdrMerge.py
- meshroom/nodes/aliceVision/LdrToHdrSampling.py
- meshroom/nodes/aliceVision/PanoramaWarping.py
Based on https://github.com/alicevision/AliceVision/pull/905
> ldr2hdr: fix bypass option

- CHANGES.md
- dev_requirements.txt
- docker/Dockerfile_centos_deps
- docker/Dockerfile_centos_deps_py2
- meshroom/__init__.py
- meshroom/submitters/simpleFarmConfig.json
- setup.py
Based on https://github.com/alicevision/AliceVision/pull/910
> Release 2020.1.0

- CHANGES.md
- meshroom/__init__.py
- meshroom/core/stats.py
Fix windows instabilities of Release 2020.1.0 on Windows.
Due to a problem in https://github.com/giampaolo/psutil/issues/1763.
> Fix crashes on process statistics (windows-only)

- meshroom/nodes/aliceVision/CameraInit.py
Ignore integrated white balance post processing for raw images
Based on https://github.com/alicevision/AliceVision/pull/932.
> [camerainit] add a boolean for white balance use

- meshroom/ui/reconstruction.py
> fix error on live reconstruction

- meshroom/nodes/aliceVision/Meshing.py
Based on https://github.com/alicevision/AliceVision/pull/972
> [nodes] Meshing: add seed and voteFilteringForWeaklySupportedSurfaces

- meshroom/core/node.py
- meshroom/multiview.py
- meshroom/nodes/aliceVision/LdrToHdrMerge.py
- meshroom/nodes/aliceVision/PanoramaCompositing.py
- meshroom/nodes/aliceVision/PanoramaInit.py
- meshroom/nodes/aliceVision/PanoramaMerging.py
- meshroom/nodes/aliceVision/PanoramaSeams.py
- meshroom/nodes/aliceVision/PanoramaWarping.py
- meshroom/ui/qml/GraphEditor/NodeEditor.qml
- meshroom/ui/qml/GraphEditor/StatViewer.qml
These updates are meant to enable the creation of very large panoramas using optimized algorithms and the use of a disk cache.
Based on https://github.com/alicevision/AliceVision/pull/947
> [panorama] PanoramaCompositing: new out-of-core algorithm

- meshroom/nodes/aliceVision/Meshing.py
Add option in Meshing node, for digging using shape from silhouette principle.
See https://github.com/alicevision/AliceVision/pull/971
> [nodes] Meshing: Add `addMaskHelperPoints` option

- meshroom/core/node.py
- meshroom/ui/qml/Viewer3D/Inspector3D.qml
> Minor fixes

- README.md
Typo fixed in line 43 in `README.md` file
Just improves documentation. No break on code.
> Minor fix (line 43)

- meshroom/nodes/aliceVision/FeatureMatching.py
relates to https://github.com/alicevision/AliceVision/pull/980
Update to the featureMatching node to add a boolean for the use of cross verification
> [nodes] featureMatching add cross verification

- meshroom/ui/qml/AboutDialog.qml
Nothing important, just updating the copyright to: 2010-2021 AliceVision contributors
Should be added to the release checklist ;)
> Update copyright to current year

- bin/meshroom_batch
> [bin] meshroom_batch: fix typo in pipeline names

- setup.py
Add the following scripts to `setup.py`:
- `meshroom_newNodeType`
- `meshroom_statistics`
- `meshroom_status`
- `meshroom_submit`
resolves #1213
resolves #1409
> [setup] add all scripts in bin/ as executables

- meshroom/nodes/aliceVision/ExportAnimatedCamera.py
Based on https://github.com/alicevision/AliceVision/pull/1047
> [nodes] ExportAnimatedCameras: new sfmDataFilter parameter

- meshroom/core/desc.py
- meshroom/ui/graph.py
Also fix a random issue with the "stop" button enabled even if nothing is computing.
> No cmd line range arguments if we have only a single chunk

- meshroom/ui/qml/Viewer/FeaturesInfoOverlay.qml
- meshroom/ui/qml/Viewer/FeaturesViewer.qml
- meshroom/ui/qml/Viewer/MFeatures.qml
- meshroom/ui/qml/Viewer/Viewer2D.qml
Update 2d viewer for new Track drawing mode of `QtAliceVision`
Based on PR: https://github.com/alicevision/QtAliceVision/pull/18
> Update 2d viewer for new Track drawing mode of QtAliceVision 

- meshroom/nodes/aliceVision/Split360Images.py
Node to access av_split360Images
This node is used to extract multiple images from equirectangular or dualfisheye images or image folder
[x] node documentation = '''...'''
[x] does not throw errors ;)
> Create Split360Images Node

- meshroom/ui/qml/GraphEditor/AttributePin.qml
- meshroom/ui/qml/GraphEditor/GraphEditor.qml
- meshroom/ui/qml/GraphEditor/Node.qml
Visual improvement to the feature added on #1355. The edge that will be deleted when it is replaced with another edge is highlighted in red.
> [ui] highlight the edge that will be deleted

- meshroom/nodes/aliceVision/SfMTransform.py
Add the option to align the scene using gps metadata
see https://github.com/alicevision/AliceVision/pull/1069
> [nodes] add gps option to SfMTransform

- meshroom/core/desc.py
- meshroom/nodes/aliceVision/FeatureExtraction.py
- meshroom/nodes/aliceVision/ImageMasking.py
- meshroom/nodes/aliceVision/MeshMasking.py
- meshroom/nodes/aliceVision/PrepareDenseScene.py
- meshroom/nodes/aliceVision/SfMDistances.py
- meshroom/nodes/aliceVision/SfMTransform.py
- meshroom/nodes/aliceVision/StructureFromMotion.py
- meshroom/ui/qml/GraphEditor/AttributeItemDelegate.qml
- meshroom/ui/qml/Viewer3D/MediaLoader.qml
- meshroom/ui/qml/Viewer3D/Viewer3DSettings.qml
- New ImageMasking node
- New MeshMasking node
- New SfMDistances node
- [nodes] add semantic to customize attibute UI
- [nodes] add mask inputs to imageMasking featureExtraction and prepareDenseScene
- [ui] declare .stl support in 3D viewer
Based on https://github.com/alicevision/AliceVision/pull/1083
> New ImageMasking and MeshMasking nodes

- meshroom/nodes/aliceVision/ImportKnownPoses.py
- meshroom/nodes/aliceVision/Texturing.py
Based on https://github.com/alicevision/AliceVision/pull/1078
> New node to import known poses for various file formats

- meshroom/core/__init__.py
- meshroom/core/attribute.py
- meshroom/core/desc.py
- meshroom/core/node.py
- meshroom/nodes/aliceVision/CameraInit.py
- upgrade groups with changes in params
- new upgradeAttributeValues per node
> [core] Improve project files upgrade

- meshroom/core/attribute.py
- meshroom/nodes/aliceVision/CameraInit.py
Meshroom-side implementation of https://github.com/alicevision/AliceVision/pull/1072.
> Optical center relative to the image center

- README.md
The link to the paper will be updated when it becomes public.
> [doc] readme: add citation

- meshroom/nodes/aliceVision/MeshFiltering.py
- meshroom/nodes/aliceVision/MeshMasking.py
- meshroom/nodes/aliceVision/Meshing.py
Minor cleanup of https://github.com/alicevision/meshroom/pull/1508.
Based on https://github.com/alicevision/AliceVision/pull/1106.
> [nodes] Mesh*: use file extension to choose the file format

- README.md
> [doc] fix the bibtex

- meshroom/ui/qml/AboutDialog.qml
The copyright year should eventually be adjusted automatically :)
> 2022 Copyright

- meshroom/nodes/aliceVision/Split360Images.py
The initial wording was strange. Could be extended with some more details
> minor doc text improvement

- meshroom/multiview.py
- meshroom/nodes/aliceVision/ColorCheckerDetection.py
- meshroom/nodes/aliceVision/FeatureMatching.py
- meshroom/nodes/aliceVision/PanoramaSeams.py
- meshroom/nodes/aliceVision/SketchfabUpload.py
- meshroom/nodes/aliceVision/StructureFromMotion.py
- meshroom/nodes/aliceVision/Texturing.py
- meshroom/nodes/blender/scripts/renderAnimatedCameraInBlender.py
- meshroom/ui/graph.py
- meshroom/ui/qml/Controls/MessageDialog.qml
- meshroom/ui/qml/DialogsFactory.qml
- meshroom/ui/qml/GraphEditor/GraphEditor.qml
- meshroom/ui/qml/Utils/SortFilterDelegateModel.qml
- meshroom/ui/qml/Utils/request.js
- meshroom/ui/qml/Viewer/ColorCheckerEntity.qml
- meshroom/ui/qml/Viewer/FeaturesInfoOverlay.qml
- meshroom/ui/qml/Viewer3D/Materials/shaders/robustwireframe.geom
- meshroom/ui/qml/Viewer3D/MediaLibrary.qml
- meshroom/ui/qml/WorkspaceView.qml
- meshroom/ui/qml/main.qml
- meshroom/ui/utils.py
Fix various typos in the source code. This includes user facing code, documentation, and source comments. This PR has not been tested.
Closes #1605
> Fix various typos in the source code

- meshroom/core/desc.py
- meshroom/nodes/aliceVision/CameraInit.py
- meshroom/ui/qml/ImageGallery/ImageGallery.qml
- meshroom/ui/reconstruction.py
linked to https://github.com/alicevision/AliceVision/pull/1098 in alicevision
> [camerainit] update parameters to use focal in mm

- bin/meshroom_batch
For instance:
`--paramOverrides SfMTransform_1.manualTransform.manualRotation.x=52.5`
`--paramOverrides SfMTransform:manualTransform.manualRotation.x=52.5`
> [bin] batch: allow to set params inside groups

- .github/stale.yml
> [ci] add bug to the list of tag to skip the stale check

- meshroom/nodes/aliceVision/ImageProcessing.py
- start.bat
ImageProcessing Node : add ACES and ACEScg as possible output color spaces
Based on https://github.com/alicevision/AliceVision/pull/1169
> Output in ACES or ACEScg color space

- meshroom/nodes/aliceVision/FeatureExtraction.py
- meshroom/nodes/aliceVision/FeatureRepeatability.py
- meshroom/submitters/simpleFarmSubmitter.py
Some typo fixes. Found via `codespell`
> Fix various typos

- meshroom/nodes/aliceVision/SfMTransform.py
Based on https://github.com/alicevision/AliceVision/pull/1030
> [nodes] SfMTransform: add auto_from_cameras_x_axis

- bin/ion_start_meshroom.sh
Provides a shebang for ion run
Remove alicevision_root which is not usefull anymore
> update ion startup

- meshroom/nodes/aliceVision/ImageProcessing.py
Add option to enable the application of DCP metadata in imageProcessing node.
Based on https://github.com/alicevision/AliceVision/pull/1340
> Apply DCP metadata in imageProcessing

- meshroom/nodes/aliceVision/ImageProcessing.py
Complete description of highlight mode parameter of imageProcessing node.
> Update highlight mode description in imageProcessing node

- meshroom/nodes/aliceVision/SfMTransform.py
New sfmTransform Node
- Use cameras X axis to estimate the horizontal plane (and the horizon)
- Use GPS measurements (if available) to align the Z axis with the north
- Use GPS measurements (if available) to set the scale (otherwise scaled such that stddev=1)
- Use cameras center mean as frame origin
> [sfmTransform] add auto mode

- meshroom/nodes/aliceVision/PanoramaPostProcessing.py
New parameter to panoramaPostProcessing : 
Panorama preview width (Which has to be smaller than the panorama original width).
> [panorama] Panorama preview size

- meshroom/submitters/simpleFarmSubmitter.py
Propagate the `REZ_PROD_PACKAGES_PATH` environment variables through submitters.
> [submitters] propagate REZ_PROD_PACKAGES_PATH environment variable

- meshroom/nodes/aliceVision/LdrToHdrMerge.py
Add option in hdr merging node to keep the filenames of the input images selected as the central ones for the hdr image filename
> HDR images naming

- meshroom/nodes/aliceVision/StructureFromMotion.py
This PR updates the StructureFromMotion node following the command line changes introduced in https://github.com/alicevision/AliceVision/pull/1436.
> [nodes] StructureFromMotion: new nbOutliersThreshold attribute

- meshroom/nodes/aliceVision/ImageProcessing.py
Add options for setting automatic or manual exposure adjustment and maximum width and height in imageProcessing node
Related to: https://github.com/alicevision/AliceVision/pull/1414
> Exposure and format adjustment

- meshroom/nodes/aliceVision/LdrToHdrSampling.py
- meshroom/nodes/aliceVision/Split360Images.py
The goal of this PR is to reflect the changes made to the `aliceVision_split360Images` software in [this PR](https://github.com/alicevision/AliceVision/pull/1382) on the Split360Images node in Meshroom.
> [nodes] Split360Images: support for SfMData file input and output

- meshroom/pipelines/photogrammetryAndCameraTracking.mg
Update the `Photogrammetry and Camera Tracking` pipeline to use the new camera tracking pipeline structure.
> [pipelines] new photogrammetry and camera tracking pipeline

- meshroom/nodes/aliceVision/ExportAnimatedCamera.py
- meshroom/nodes/blender/ScenePreview.py
- meshroom/nodes/blender/scripts/preview.py
Use the chunk system on the `ScenePreview` to parallelize calculations.
> [nodes] parallelize ScenePreview

- meshroom/pipelines/panoramaFisheyeHdr.mg
- meshroom/pipelines/panoramaHdr.mg
This PR adds the "Panorama Preview" output to the list of published results in the Panorama HDR and Panorama Fisheye HDR templates.
> [pipelines] Panorama: Publish the panorama preview

- meshroom/nodes/aliceVision/PanoramaPostProcessing.py
- meshroom/pipelines/panoramaFisheyeHdr.mg
- meshroom/pipelines/panoramaHdr.mg
Add downscaled panorama levels to Publish node inputs for use in meshroom_batch.
> [pipelines] publish downscaled panorama levels

- meshroom/core/graph.py
Up until this PR, compatibility nodes (which necessarily had a version or description issue) were ignored during the evaluation of UID conflicts, as they had no UID.
This however created a bug, where already existing compatibility nodes with inputs from nodes that triggered UID conflicts were losing their input connections: when the node with the UID conflict was replaced with a new compatibility node (with a UID conflict issue), the link was broken and could not be resolved anymore as it lost any mention of the input node's name. This was also valid for nodes without any compatibility issue which had UID-conflicted nodes as their inputs.
Processing all the nodes in addition to those with a UID conflict issue prevents this from happening: edges are correctly preserved.
This also fixes an …
> [core] Preserve edges by recreating all the nodes during UID evaluation

- meshroom/nodes/aliceVision/PanoramaInit.py
- meshroom/pipelines/panoramaFisheyeHdr.mg
- meshroom/pipelines/panoramaHdr.mg
Remove fake dependency in `PanoramaInit` node as it is not needed anymore.
> PanoramaInit: remove fake dependency

- meshroom/core/attribute.py
- meshroom/ui/qml/GraphEditor/AttributeEditor.qml
- meshroom/ui/qml/GraphEditor/AttributeItemDelegate.qml
- meshroom/ui/qml/GraphEditor/GraphEditor.qml
- meshroom/ui/qml/GraphEditor/GraphEditorSettings.qml
- meshroom/ui/qml/GraphEditor/NodeEditor.qml
- meshroom/ui/qml/Viewer3D/Inspector3D.qml
> Multiple UI Improvements

- meshroom/nodes/aliceVision/ImageSegmentation.py
> [nodes] ImageSegmentation: increase GPU requirements

- meshroom/nodes/aliceVision/SfMMerge.py
- meshroom/nodes/aliceVision/SfMToRig.py
Create two new nodes :
one node to merge two sfmData assuming both sfmData does contain only unique ids
one node to create a rig from one input sfmData (All views are then a different subpose of a common rig)
Linked to https://github.com/alicevision/AliceVision/pull/1568
> New nodes for panorama to sfm

- RELEASING.md
- meshroom/ui/qml/Viewer3D/MediaLoader.qml
- meshroom/ui/qml/Viewer3D/SfmDataLoader.qml
- meshroom/ui/qml/Viewer3D/Viewer3DSettings.qml
Upgrade meshroom to
- use new module QmlSfmData
- Accept abc but also .sfm and .json
https://github.com/alicevision/QtAliceVision/pull/45
> Use new SfmDataEntity plugin instead of AlembicEntity

- meshroom/nodes/aliceVision/ImageProcessing.py
Add automatic reorientation option in imageProcessing node.
Associated to AliceVision PR https://github.com/alicevision/AliceVision/pull/1585
> Automatic reorientation

- meshroom/nodes/aliceVision/CameraInit.py
Upgrade sfmData version in cameraInit node.
link to https://github.com/alicevision/AliceVision/pull/1582
> Add ancestor images info in view

- meshroom/nodes/aliceVision/ImportE57.py
E57 importer node 
see also https://github.com/alicevision/AliceVision/pull/1652
> Add an "E57" importer node

- meshroom/nodes/aliceVision/ImportE57.py
see https://github.com/alicevision/AliceVision/pull/1666
> E57 importer is now generating multiple sfmData

- meshroom/nodes/aliceVision/ExportAnimatedCamera.py
Linked to https://github.com/alicevision/AliceVision/pull/1677
> [nodes] ExportAnimatedCameras: rename as ST maps (instead of UV)

- meshroom/nodes/aliceVision/MeshRemoveUnseenFaces.py
Remove triangles from the mesh when the vertices are not visible by any camera.
Based on https://github.com/alicevision/AliceVision/pull/1681
> [nodes] New node MeshRemoveUnseenFaces

- meshroom/nodes/aliceVision/CameraInit.py
Upgrade camera type on loading .mg files for version < 10.0
> Upgrade intrinsics for distortion

- meshroom/nodes/aliceVision/StructureFromMotion.py
SFM requires large CPU and RAM resources.
> [nodes] Update the ressources needs for the SFM node

- meshroom/ui/qml/Viewer3D/MediaLoader.qml
Load PLY as pointcloud for 3D viewer if the extension is .pc.ply
See https://github.com/alicevision/AliceVision/pull/1689
> Custom loader for .pc.ply pointcloud

- meshroom/nodes/aliceVision/SelectConnectedViews.py
Select Connected Views based on SfM landmarks.
Based on https://github.com/alicevision/AliceVision/pull/1692
> [nodes] New SelectConnectedViews node

- bin/meshroom_batch
- bin/meshroom_submit
- meshroom/submitters/simpleFarmConfig.json
- meshroom/ui/app.py
This PR updates the tags in the SimpleFarm configuration file for the Meshroom jobs that are sent to the render farm. Additionnally, it changes the default title of jobs to "[Meshroom] Job Title" instead of "Job Title [Meshroom]".
> [submitters] Update SimpleFarm configuration tags

- meshroom/ui/qml/Viewer/FeaturesViewer.qml
- meshroom/ui/qml/Viewer/SequencePlayer.qml
- meshroom/ui/qml/Viewer/Viewer2D.qml
- meshroom/ui/qml/Viewer3D/Inspector3D.qml
- meshroom/ui/qml/Viewer3D/MediaLoader.qml
- meshroom/ui/qml/Viewer3D/SfmDataLoader.qml
- meshroom/ui/qml/Viewer3D/Viewer3D.qml
- meshroom/ui/qml/Viewer3D/Viewer3DSettings.qml
- meshroom/ui/qml/Viewer3D/ViewpointCamera.qml
- meshroom/ui/qml/WorkspaceView.qml
- meshroom/ui/reconstruction.py
Synchronization of SequencePlayer and Viewer3D possible if button is toggled.
Not linked to ImageGallery to gain performances.
Removal of smooth animations for performance
Quick fix of View Through the Active Camera button if no element in inspector 3D.
> [ui] Sync SequencePlayer and Viewer3D

- meshroom/submitters/rippleSubmitter.py
> Update ripple constraints

- meshroom/nodes/aliceVision/ConvertDistortion.py
New node to convert distortions to undistortions (only for radial3 for now)
See https://github.com/alicevision/AliceVision/pull/1693
> Convert distortion node

- meshroom/nodes/aliceVision/LidarDecimating.py
- meshroom/nodes/aliceVision/LidarMerging.py
- meshroom/nodes/aliceVision/LidarMeshing.py
- Lidar Submeshes decimation
- Lidar Submesh merging to a single mesh
This relates to https://github.com/alicevision/AliceVision/pull/1708.
> Lidar nodes

- meshroom/ui/qml/Controls/FilterComboBox.qml
Quick bugfix to have scroll available in the FilterComboBox when there are too many items.
> [ui] Scroll available in FilterComboBox

- meshroom/ui/qml/Viewer/SequencePlayer.qml
Small UX improvements for Sequence Player
- FPS is now text input, 
- Slider has a tooltip to know on which frame you will be while handling
- Go to specific frame by text input or arrows on side
> [ui] Sequence Player UX improvements (fps, slider, frame)

- meshroom/core/attribute.py
- meshroom/core/desc.py
- meshroom/core/node.py
- meshroom/ui/qml/GraphEditor/AttributeItemDelegate.qml
Push Button is a new type of attribute for nodes. 
- They are described as PushButtonParam and do not need value. Value is set to "" to not have DescriptionConflict and be consistent with other types of attribute.
- Definition of `on{Attribute}Clicked` function available in the description of the node to have a custom behavior.
> [core/ui] Add support for PushButton attribute

- meshroom/ui/qml/Viewer/Viewer2D.qml
Add posibility to display auto detected spheres from a `SphereDetection` node.
> [ui] Viewer2D: Display lighting circle with auto detected sphere

- meshroom/core/graph.py
- meshroom/ui/reconstruction.py
Latest SfM node was not always the same because the edges of nodes weren't always in the same order. To solve that we decided to order the edges and then we obtain the correct node for previz.
> [ui/core] Fix get latest SfM node for previz

- meshroom/core/graph.py
- meshroom/nodes/aliceVision/ImageProcessing.py
- meshroom/ui/components/filepath.py
Several fixes :
- popup for modified file somewhere else fixed
- ImageProcessing update from <FILENAME> to <FILESTEM>
- add of <EXTENSION> in replacements
> [fix] Various fixes

- meshroom/ui/qml/Viewer/HdrImageToolbar.qml
- meshroom/ui/qml/Viewer/Viewer2D.qml
RGBA shortcuts for Image Viewer
> [ui] RGBA shortcuts for Image Viewer

- meshroom/ui/qml/GraphEditor/Node.qml
Eye on displayable node even if not computed.
> [GraphEditor] Eye on displayable node even if not computed

- meshroom/core/node.py
- meshroom/nodes/aliceVision/ExportAnimatedCamera.py
- tests/test_multiviewPipeline.py
Fix outputImages if no export in ExportAnimatedCamera
If exportUndistortedImages is false, we do not want outputImages attribute.
> [nodes] Fix outputImages if no export in ExportAnimatedCamera

- meshroom/ui/qml/Viewer/SequencePlayer.qml
- meshroom/ui/qml/Viewer/Viewer2D.qml
Shortcuts for the image metadata overlay using i key and to play and pause the timeline in the SequencePlayer using SPACE.
> [ui] Shortcuts in Viewer2D and SequencePlayer

- meshroom/common/core.py
- meshroom/common/qt.py
- meshroom/core/__init__.py
- meshroom/core/node.py
- meshroom/ui/app.py
- meshroom/ui/qml/Viewer/Viewer2D.qml
- meshroom/ui/reconstruction.py
- tests/test_compatibility.py
- tests/test_model.py
When displaying node not related with the current Camera Init, try to switch to the correct CameraInit to have everything working.
> [ui] Auto Update CameraInit when displaying node

- meshroom/core/graph.py
- meshroom/nodes/aliceVision/DepthMapFilter.py
- meshroom/submitters/simpleFarmSubmitter.py
- Display normal maps if enabled
- Fix extra logging
- Set user in simpleFarm submitter
> Depth map filter: display normals if enabled

- meshroom/ui/qml/main.qml
Avoid display troubles with native dialogs.
> [ui] do not use native dialog

- meshroom/core/graph.py
- meshroom/pipelines/cameraTracking.mg
- meshroom/pipelines/cameraTrackingWithoutCalibration.mg
- meshroom/pipelines/distortionCalibration.mg
- meshroom/pipelines/hdrFusion.mg
- meshroom/pipelines/nodalCameraTracking.mg
- meshroom/pipelines/nodalCameraTrackingWithoutCalibration.mg
- meshroom/pipelines/panoramaFisheyeHdr.mg
- meshroom/pipelines/panoramaHdr.mg
- meshroom/pipelines/photogrammetry.mg
- meshroom/pipelines/photogrammetryAndCameraTracking.mg
- meshroom/pipelines/photogrammetryDraft.mg
- meshroom/pipelines/stereoPhotometry.mg
- meshroom/ui/reconstruction.py
Sort node types versions and list of nodes in the graph to avoid randomness during file export.
> File export ordering

- meshroom/ui/qml/Viewer/FeaturesViewer.qml
- meshroom/ui/qml/Viewer/SequencePlayer.qml
- meshroom/ui/qml/Viewer/Viewer2D.qml
- meshroom/ui/qml/WorkspaceView.qml
Fetching button in Sequence Player to have the Sequence Player enabled by default.
Related to this [PR](https://github.com/alicevision/QtAliceVision/pull/71)
> [SequencePlayer] Fetching option added

- meshroom/submitters/rippleSubmitter.py
> Update ripple with "cuda" instead of "gpu"

- .git-blame-ignore-revs
- meshroom/core/graph.py
- meshroom/ui/__main__.py
- meshroom/ui/app.py
- meshroom/ui/qml/Viewer/Viewer2D.qml
- meshroom/ui/reconstruction.py
This PR builds on top of #2443 and changes its behaviour by providing access to the path of the currently displayed frame instead of providing the attribute describing the currently selected viewpoint.
This means that any image displayed in the 2D viewer, may it be an image that is selected in the gallery or that is coming from a node output, including outputs that are not related to the currently selected viewpoint (i.e. node outputs that are `sequence` or `imageList`-typed).
In order to do so, the UI is exposed globally and can be imported in any node, which allows access to the properties of the `Reconstruction` object through the `activeProject` property. The `currentViewPath` property is added to access directly the path through the `Reconstruction` object, and will return an empty …
> Provide access to the path of the currently displayed frame

- meshroom/ui/qml/Utils/format.js
- meshroom/ui/qml/Viewer/SequencePlayer.qml
- meshroom/ui/qml/Viewer/Viewer2D.qml
> [ui] Sequence Player UI Modifications

- meshroom/ui/app.py
- meshroom/ui/qml/Viewer/Viewer2D.qml
- meshroom/ui/qml/WorkspaceView.qml
For stability necessities, we had MESHROOM_USE_SEQUENCE_PLAYER environment variable.
> [ui] Add MESHROOM_USE_SEQUENCE_PLAYER environment variable

- bin/ion_start_meshroom.sh
- meshroom/__init__.py
Retrieve ion release version and display it inside meshroom
> Display ion container version in meshroom 

- meshroom/nodes/aliceVision/SfmExpanding.py
SfmExpansion pipeline 
See https://github.com/alicevision/AliceVision/pull/1718
> Add new SfMExpanding node

- meshroom/nodes/aliceVision/CheckerboardDetection.py
- meshroom/nodes/aliceVision/DistortionCalibration.py
Add some squeezing estimation option to distortion calibration 
see PR [1727](https://github.com/alicevision/AliceVision/pull/1727)
> Add squeeze option

- meshroom/submitters/rippleSubmitter.py
> Remove some computers even for normal tasks

- .github/workflows/continuous-integration.yml
Added an env var in the ci to allow bypassing certain tests that dont make sense in the CI (eg. plugins).
> added env var for ci

- meshroom/ui/qml/GraphEditor/NodeChunks.qml
- meshroom/ui/qml/main.qml
Because for now we do not see each chunk easily in the progress bar of a node we add something to alternate the colors.
> [GraphEditor] Improve visibility of chunks in progress bar

- meshroom/ui/components/filepath.py
- meshroom/ui/qml/Viewer/Viewer2D.qml
- allows multiple "*" in the files search expression
- fix a bug if we only provide a folder
- keep filepaths for missing files in sequence
- keep the current frame if the frame range has not changed
> [ui] Improve sequence display

- meshroom/ui/qml/GraphEditor/GraphEditor.qml
Use an explicit height on the newNodeMenu, this fixes the issue with unstable size of the menu.
> [ui] GraphEditor.newNodeMenu: fix unstable menu height

- meshroom/nodes/aliceVision/ApplyCalibration.py
See https://github.com/alicevision/AliceVision/pull/1735
> [nodes] ApplyCalibration: Add option to use a Lens calibration file from 3dequalizer in json

- meshroom/nodes/aliceVision/SfMAlignment.py
- meshroom/nodes/aliceVision/SfMMerge.py
see https://github.com/alicevision/AliceVision/pull/1730
> Multiple shots: Align and merge multiple SfM from feature matches

- meshroom/nodes/aliceVision/CameraInit.py
see https://github.com/alicevision/AliceVision/pull/1737
> Add locks for intrinsics

- meshroom/nodes/aliceVision/SfMTransform.py
See https://github.com/alicevision/AliceVision/pull/1742
> sfmTransform: Add option to lineup camera motion with object/lidar given an external camera pose

- meshroom/ui/qml/GraphEditor/AttributeItemDelegate.qml
- meshroom/ui/qml/GraphEditor/AttributePin.qml
If we need to know the type of attribute shortly we now have a tooltip displaying it.
> [AttributePin] Add tooltip to display type of attribute

- meshroom/nodes/aliceVision/ConvertSfMFormat.py
- meshroom/nodes/aliceVision/FeatureExtraction.py
- meshroom/nodes/aliceVision/FeatureMatching.py
- meshroom/nodes/aliceVision/ImageMatching.py
- meshroom/nodes/aliceVision/ImageMatchingMultiSfM.py
- meshroom/nodes/aliceVision/LdrToHdrCalibration.py
- meshroom/nodes/aliceVision/LdrToHdrMerge.py
- meshroom/nodes/aliceVision/LdrToHdrSampling.py
- meshroom/nodes/aliceVision/PanoramaCompositing.py
- meshroom/nodes/aliceVision/PanoramaEstimation.py
- meshroom/nodes/aliceVision/PanoramaMerging.py
- meshroom/nodes/aliceVision/SfMTriangulation.py
- meshroom/nodes/aliceVision/StructureFromMotion.py
- meshroom/nodes/aliceVision/TracksBuilding.py
- meshroom/ui/qml/Application.qml
- meshroom/ui/qml/GraphEditor/AttributeItemDelegate.qml
Quick changes for UI
For nodes, all attributes connected in default pipelines are exposed.
> UI Changes

- meshroom/ui/qml/Application.qml
- meshroom/ui/qml/Controls/MSplitView.qml
- meshroom/ui/qml/Controls/qmldir
- meshroom/ui/qml/GraphEditor/ChunksListView.qml
- meshroom/ui/qml/GraphEditor/NodeChunks.qml
- meshroom/ui/qml/GraphEditor/NodeEditor.qml
- meshroom/ui/qml/GraphEditor/NodeStatistics.qml
- meshroom/ui/qml/Homepage.qml
- meshroom/ui/qml/Viewer3D/Viewer3D.qml
- meshroom/ui/qml/WorkspaceView.qml
Fit Graph Editor if all WorkspaceView is hidden
It can be useful if you only need the Graph in the UI.
> [ui] Add View Image Gallery Parameter

- meshroom/core/desc.py
- meshroom/core/node.py
Added Pre and Post process functions on the Node Description which can be utilised by the nodes.
> Added Pre and Post process functions on the Base Node

- .github/workflows/continuous-integration.yml
- appveyor.yml
- meshroom/pipelines/cameraTracking.mg
- meshroom/pipelines/cameraTrackingWithoutCalibration.mg
- meshroom/pipelines/nodalCameraTracking.mg
- meshroom/pipelines/nodalCameraTrackingWithoutCalibration.mg
- meshroom/pipelines/photogrammetryAndCameraTracking.mg
- meshroom/submitters/simpleFarmConfig.json
Modify the pipelines to
- Use imageprompt everywhere
- Use exportDistortion in all tracking pipelines
> use export distortion and new segmentation

- meshroom/ui/qml/Viewer/Viewer2D.qml
- imageStatus was not available for 8bits viewer.
- making an alias imageStatus to status
> [qt6] Fix 8Bits image viewer zoom/fit

- meshroom/nodes/aliceVision/CameraInit.py
Version is not in sync with AV
> Change sfmData version

- meshroom/nodes/blender/scripts/preview.py
Update  blender script to new anamorphic model
> [blender] Adapt `ScenePreview`'s Blender script to pixel ratio

- meshroom/nodes/aliceVision/CameraInit.py
- meshroom/nodes/aliceVision/GlobalRotationEstimating.py
Add global rotation estimation node
See https://github.com/alicevision/AliceVision/pull/1773
> [nodes] Add Global Rotation Estimating node

- docs/source/conf.py
- meshroom/__init__.py
- meshroom/pipelines/cameraTracking.mg
- meshroom/pipelines/cameraTrackingWithoutCalibration.mg
- meshroom/pipelines/distortionCalibration.mg
- meshroom/pipelines/hdrFusion.mg
- meshroom/pipelines/multi-viewPhotometricStereo.mg
- meshroom/pipelines/nodalCameraTracking.mg
- meshroom/pipelines/nodalCameraTrackingWithoutCalibration.mg
- meshroom/pipelines/panoramaFisheyeHdr.mg
- meshroom/pipelines/panoramaHdr.mg
- meshroom/pipelines/photogrammetry.mg
- meshroom/pipelines/photogrammetryAndCameraTracking.mg
- meshroom/pipelines/photogrammetryDraft.mg
- meshroom/pipelines/photometricStereo.mg
- meshroom/ui/qml/AboutDialog.qml
This PR updates the development version from "2024.1.0" to "2025.1.0" as well as all the copyrights to 2025.
> Update version number and copyrights

- .github/workflows/continuous-integration.yml
Enable codecov test analytics.
> [ci] Codecov: enable support for test run reports

- meshroom/ui/graph.py
When the minimal refresh mode is on, only chunks that are running, submitted or in error while their execution mode is external should be polled.
Chunks that have the same status but with a local execution mode will be correctly updated as their status changes will be notified.
The behaviour for the automatic refresh mode remains the same: all the chunks are polled, independently from their status and their execution mode.
> [ui] Graph: In minimal refresh, do not poll files for chunks run locally

- meshroom/nodes/aliceVision/ExportUSD.py
Node to export object file to USD format
See https://github.com/alicevision/AliceVision/pull/1823
> Export USD Node

- meshroom/ui/qml/Viewer/Viewer2D.qml
Check that `FloatImageLoader` item exists
> [ui] [fix] Viewer2D: Failure on MousePosition on some edge cases

- .github/workflows/continuous-integration.yml
This PR updates the Python version used in the continuous integration from Python 3.9 to 3.11.
> [ci] Update Python version from 3.9.13 to 3.11

- meshroom/ui/components/scene3D.py
- meshroom/ui/qml/Viewer3D/MeshingBoundingBox.qml
- meshroom/ui/qml/Viewer3D/TransformGizmo.qml
- meshroom/ui/qml/Viewer3D/TransformGizmoPicker.qml
- Remove deprecated signals, replace with explicit parameters
- Removed function is replaced in scene3d to fill a 4d matrix with vectors
> Meshing: boundingBox working with qt6

- INSTALL.md
- INSTALL_PLUGINS.md
- README.md
This pull request updates the documentation and dependencies for Meshroom, focusing on improving clarity, fixing inconsistencies, and adding new instructions for advanced configurations. 
* Updated `INSTALL.md` to improve clarity and consistency in headings and text (e.g., renaming "Python Environment" to "Python environment") and fixed capitalization issues. [[1]](diffhunk://#diff-09b140a43ebfdd8dbec31ce72cafffd15164d2860fd390692a030bcb932b54a0L1-R1) [[2]](diffhunk://#diff-09b140a43ebfdd8dbec31ce72cafffd15164d2860fd390692a030bcb932b54a0L39-R39) [[3]](diffhunk://#diff-09b140a43ebfdd8dbec31ce72cafffd15164d2860fd390692a030bcb932b54a0L50-R50)
* Added detailed instructions for configuring environment variables for AliceVision and Meshroom, including new variables like `MESHROOM_NODES_PATH`, …
> [doc] Update `INSTALL.md` and `README.md` files

- meshroom/core/plugins.py
In some virtual environments on Linux platforms, extra "lib" directories may be located at a deeper level than "./lib" or "./lib64". For the `LD_LIBRARY_PATH` to contain all the necessary libraries, we recursively go over the virtual env packages and add the "lib" folders to `LD_LIBRARY_PATH`.
The virtual env packages are discovered recursively starting from `lib*/python[0-9].[0-9]*/site-packages`, which was already used to add the packages that needed it to the `PYTHONPATH`.
> [core] plugins: Look recursively for "lib" directories in Linux venv
