alicevision/Meshroom

tests/test_ui_graph.py

Unparented QObject with no QApplication causes crash after test execution if not explicitly deleted.

Fix UIGraph unit tests crash

---

meshroom/nodes/aliceVision/ImageMatching.py
meshroom/nodes/aliceVision/ImageMatchingMultiSfM.py

With prebuilt release in mind, avoid invalidating scenes because of an embedded resource.

[nodes][aliceVision] remove voctree path from uid 0 computation

---

meshroom/core/node.py

On Windows, attempting to remove a file that is in use causes an exception to be raised. So we may need multiple trials.
I didn't get the problem anymore with this fix.

[core] multiple trials to replace the status file to avoid file conflicts on windows

---

meshroom/core/graph.py
meshroom/core/node.py
meshroom/ui/commands.py
meshroom/ui/components/edge.py
meshroom/ui/graph.py
meshroom/ui/qml/GraphEditor/AttributeItemDelegate.qml
meshroom/ui/qml/GraphEditor/AttributePin.qml
meshroom/ui/qml/GraphEditor/Edge.qml
meshroom/ui/qml/GraphEditor/GraphEditor.qml
meshroom/ui/qml/GraphEditor/Node.qml
meshroom/ui/qml/LiveSfmView.qml
meshroom/ui/qml/MaterialIcons/MaterialToolButton.qml
meshroom/ui/qml/MaterialIcons/qmldir
meshroom/ui/qml/WorkspaceView.qml
meshroom/ui/qml/main.qml
meshroom/ui/reconstruction.py
meshroom/ui/utils.py

This PR adds nodes move operations to the undo stack and save nodes positions in the project file. This allows to restore nodes positions when loading a project or whenever an operation recreates a deleted node on "undo".
It also improves GraphEditor UX regarding node selection, visual feedbacks and attributes connections.

Save nodes position + undoable nodes moves

---

meshroom/nodes/aliceVision/CameraInit.py
meshroom/ui/qml/ImageDelegate.qml
meshroom/ui/qml/ImageGallery.qml
meshroom/ui/qml/MaterialIcons/MaterialLabel.qml
meshroom/ui/qml/MaterialIcons/qmldir
meshroom/ui/reconstruction.py

[ui] Display metadata and lens status flag

---

meshroom/ui/graph.py
meshroom/ui/qml/GraphEditor/GraphEditor.qml

Fix incorrectly initialized width and height for graph bounding box.

GraphLayout: fix bouding box computation

---

meshroom/__init__.py
setup.py

Introduce `PlatformExecutable` class to manage variations between platforms for executable freezing via cx_Freeze. This PR also fixes the issue reported (meshroom_photogrammetry without targetName) after #163 was merged.
After trying packaged application on different Linux distributions, it turns out that we also need to pack some system libraries (e.g: ssl) for things to work. We took this [setup script](https://github.com/Ultimaker/cura-build/blob/master/packaging/setup_linux.py.in) as reference to tweak dependencies lookup.

[setup] add PlatformExecutable to handle variations between platforms + dependencies lookup

---

.travis.yml
meshroom/core/desc.py

Add http://flake8.pycqa.org tests to look for Python syntax errors and undefined names
E901,E999,F821,F822,F823 are the "showstopper" flake8 issues that can halt the runtime with a SyntaxError, NameError, etc. Most [other flake8 issues](https://travis-ci.org/alicevision/meshroom/jobs/414794287#L479) are merely "style violations" -- useful for readability but they do not effect runtime safety.
F821: undefined name name
F822: undefined name name in __all__
F823: local variable name referenced before assignment
E901: SyntaxError or IndentationError
E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

Travis CI: Add flake8 to the testing

---

meshroom/ui/qml/GraphEditor/NodeLog.qml

Fix #219 
Add monospaced system font families for all platforms.

Multi-platform monospace display in Log view

---

requirements.txt

Fix #215 
Update to the latest PySide2 version available.

Bump to PySide2 5.11.1

---

meshroom/nodes/aliceVision/FeatureExtraction.py

Use GPU feature extraction if available. Bump node version to 1.1 (no incompatibilities).

FeatureExtraction: don't force CPU extraction by default

---

meshroom/core/desc.py
meshroom/nodes/aliceVision/CameraInit.py

See alicevision/AliceVision/pull/540

Add intrinsic locked option in CameraInit node

---

meshroom/nodes/aliceVision/ConvertSfMFormat.py

See alicevision/AliceVision/pull/550

[nodes] `convertSfMFormat` users can now specify a view white list

---

meshroom/ui/qml/Viewer3D/MediaLoader.qml

Bindings driving pointClouds/cameras 'enabled' property don't work properly here (at least for PySide2 < 5.11.2).
In https://github.com/alicevision/qmlAlembic/pull/11, QmlAlembic ensures entities are correctly hidden when their corresponding size/scale is set to 0; and therefore discard the need for those bindings.

Viewer3D: let QmlAlembic manage entities visibility

---

meshroom/core/graph.py
meshroom/ui/graph.py
meshroom/ui/qml/Controls/SearchBar.qml
meshroom/ui/qml/Controls/qmldir
meshroom/ui/qml/GraphEditor/AttributeEditor.qml
meshroom/ui/qml/GraphEditor/AttributeItemDelegate.qml
meshroom/ui/qml/GraphEditor/GraphEditor.qml
meshroom/ui/qml/GraphEditor/GraphEditorSettings.qml
meshroom/ui/qml/GraphEditor/NodeEditor.qml
meshroom/ui/qml/Viewer/ImageMetadataView.qml
meshroom/ui/qml/Viewer3D/Viewer3D.qml
meshroom/ui/qml/Viewer3D/Viewer3DSettings.qml
meshroom/ui/qml/WorkspaceView.qml
meshroom/ui/qml/main.qml

This PR contains various improvements in the Graph Editor module.

Graph editor improvements

---

meshroom/nodes/aliceVision/SfMTransform.py

The option "from_single_camera" is available in the transformation method. It allows to use a view as the origin of the coordinate system. The name of the view as to be specified in the transformation text field.
Related to https://github.com/alicevision/AliceVision/pull/557

New option to SfMTransform node

---

bin/meshroom_photogrammetry
meshroom/multiview.py
meshroom/nodes/aliceVision/CameraInit.py
meshroom/nodes/aliceVision/StructureFromMotion.py

* Allows to run the pipeline from a .sfm file, optionally containing the camera intrinsics
* exposes the refineIntrinsics parameter in sfm node to lock the camera intrinsics (eg the cameras have been already calibrated

[CLI] Add possibility to run pipeline from a .sfm file

---

bin/meshroom_photogrammetry
meshroom/core/graph.py
meshroom/core/node.py
meshroom/multiview.py
meshroom/nodes/aliceVision/CameraInit.py
meshroom/ui/reconstruction.py

Same goal as #354, taking #329 into account + deeper refactoring.
Add `--pipeline` parameter to use a Meshroom file as a pre-configured pipeline graph to run on input images. Simplify and generalize the way image files are detected and pipeline graphs are initialized.

meshroom_photogrammetry: add --pipeline parameter to use a pre-configured pipeline graph

---

meshroom/ui/app.py
meshroom/ui/graph.py
meshroom/ui/qml/GraphEditor/AttributePin.qml
meshroom/ui/qml/ImageGallery/IntrinsicsIndicator.qml

Minor UI fixes

---

meshroom/ui/qml/GraphEditor/GraphEditor.qml
meshroom/ui/qml/main.qml

Show unsaved project warning dialog when computing from GraphEditor, as it was the case when using the global "Start" button.
Add an option to disable this warning for the rest of a session.

Show unsaved project warning dialog also when computing from GraphEditor

---

meshroom/ui/qml/Viewer3D/MediaCache.qml
meshroom/ui/qml/Viewer3D/MediaLibrary.qml
meshroom/ui/qml/Viewer3D/MediaLoader.qml

Viewer3D: fix cache issue + disable camera picking when hidden

---

meshroom/ui/qml/ImageGallery/ImageGallery.qml
meshroom/ui/qml/ImageGallery/IntrinsicsIndicator.qml
meshroom/ui/reconstruction.py

[ui] IntrinsicsIndicator: display distortion model

---

meshroom/ui/qml/GraphEditor/AttributeEditor.qml

Usage of DelegateModel for model filtering has not proven to be the most stable solution, and might be responsible for random crashes happening during engine's garbage collection.  Implement Loader-based alternative:
* first delegate is a Loader which creates the AttributeItemDelegate if necessary
* compensate spacing using negative height when element is hidden

AttributeEditor: remove SortFilterDelegateModel

---

meshroom/ui/qml/Viewer3D/DefaultCameraController.qml
meshroom/ui/qml/Viewer3D/DepthMapLoader.qml
meshroom/ui/qml/Viewer3D/Inspector3D.qml
meshroom/ui/qml/Viewer3D/Locator3D.qml
meshroom/ui/qml/Viewer3D/MediaLibrary.qml
meshroom/ui/qml/Viewer3D/Viewer3D.qml

3DViewer small fixes and updates:

Viewer3D: use DepthMapEntity 2.0 + various fixes

---

bin/meshroom_compute
bin/meshroom_newNodeType
bin/meshroom_photogrammetry
bin/meshroom_statistics
bin/meshroom_status
setup.py

[bin] use sys.exit + build meshroom_compute executable

---

meshroom/core/attribute.py
meshroom/ui/qml/ImageGallery/ImageGallery.qml
meshroom/ui/qml/ImageGallery/IntrinsicsIndicator.qml

Add GroupAttribute.childAttribute method

---

bin/meshroom_photogrammetry
meshroom/nodes/aliceVision/PrepareDenseScene.py
meshroom/ui/app.py

This PR introduces two main options to the command line scripts.
* `meshroom_photogrammetry`, a `--overrides` parameter is added that enables the user to specify a json file containing parameters values to use for each node, thus overriding the default settings. The json file follows a similar structure of the `.mg` file containing the pipeline, ie:
```json
{
"<node1Name>": {
"<param1Name>": "<param1Value>"
"<param2Name>": "<param2Value>"
},
"<node2Name>": {
"<param1Name>": "<param1Value>"
},
...
}
```
For example one file setting file `settings.json` could be
```json
{
"FeatureExtraction_1": {
"describerPreset": "high"
},
"FeatureMatching_1": {
"guidedMatching": "0"
},
"StructureFromMotion_1": {
"useLocalBA": "0",
"refineIntrinsics": "0"
}
}
```
* `ui` can now take a parameter …

[CLI] Added new options

---

meshroom/ui/app.py

Argument was `project` but was used as `pipeline` which prevented the ui from starting.

Corrected project argument name

---

meshroom/core/desc.py

Expose `advanced` constructor argument on List/GroupAttribute.

Allow List/GroupAttribute to be marked as advanced parameters

---

meshroom/core/node.py

[flake8](http://flake8.pycqa.org) testing of https://github.com/alicevision/meshroom on Python 3.7.1
$ __flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics__
```
./meshroom/core/node.py:461:34: F632 use ==/!= to compare str, bytes, and int literals
if v is not None and v is not '':
^
./meshroom/core/node.py:480:34: F632 use ==/!= to compare str, bytes, and int literals
if v is not None and v is not '':
^
2     F632 use ==/!= to compare str, bytes, and int literals
2
```

Avoid issue with use ==/!= to compare str, bytes, and int literals

---

meshroom/ui/app.py
meshroom/ui/components/__init__.py
meshroom/ui/components/clipboard.py
meshroom/ui/components/edge.py
meshroom/ui/graph.py
meshroom/ui/qml/Controls/TextFileViewer.qml
meshroom/ui/qml/Controls/qmldir
meshroom/ui/qml/GraphEditor/NodeEditor.qml
meshroom/ui/qml/GraphEditor/NodeLog.qml
meshroom/ui/qml/Utils/Clipboard.qml
meshroom/ui/qml/Utils/qmldir
meshroom/ui/qml/Viewer3D/Inspector3D.qml
meshroom/ui/utils.py

This PR introduces improvements regarding node log display and status update management (ChunksMonitor). It also makes Meshroom work with PySide2 5.12.x.
**Log Display**
New TextFileViewer component that uses a ListView (with one delegate per line) instead of a TextArea. This supports much larger text files display and don't decrease performances due to ListView's caching system (only visible delegates are actually created). This also allows customizing line delegates to provide better visual feedback (log level coloring, progress bar display...).
This PR also fix log auto-reload issues, i.e. displayed text not being updated while content on disk has changed. It does not rely on 'Last-Modified' header from XHR response anymore, which was potentially not updated due to caching issues. …

Logs display and status update improvements

---

meshroom/core/desc.py

Related to https://github.com/alicevision/AliceVision/pull/628
* range 'blockSize' is now the complete block size (equal for all iterations)
* command lines nodes can use this complete block size to compute the iteration number on software side; delegate range cropping for last iteration to software.
* 'effectiveBlockSize' is still accessible through 'rangeEffectiveBlockSize' parameter

Make range complete block size accessible to command line nodes

---

meshroom/__init__.py

During development the git branch will be added to the version name. In releases, as there is no git repository included, the __version__ will not be modified.

[core] Add git branch name in version name

---

meshroom/__init__.py
meshroom/ui/app.py

Fix #508 
Introduce `meshroom.__version_name__` variable in order not to modify `meshroom.__version__` and use this as Application version. 
`meshroom.__version__` is stored in scene files and used when making a package and should not contain anything other than major.minor.micro information.

Dissociate meshroom.__version__ / __version_name__

---

meshroom/nodes/aliceVision/PrepareDenseScene.py

Advanced parameter : boolean to choose whether or not to correct images exposure values (EV) during the PrepareDenseScene.

[PrepareDenseScene] option to correct images exposure value

---

meshroom/nodes/aliceVision/Texturing.py

Colorspace for the texturing internal computation (does not impact the output file colorspace). Choose between sRGB (default), LAB and XYZ.
See https://github.com/alicevision/AliceVision/pull/651

[Texturing] Add option to choose the internal colorspace used for color fusion

---

meshroom/nodes/aliceVision/Texturing.py

Advanced parameter : boolean to choose whether or not to correct images exposure values (EV) during the Texturing.
See https://github.com/alicevision/AliceVision/pull/656.

[Texturing] Add option to correct exposure values during Texturing

---

meshroom/ui/graph.py
meshroom/ui/qml/Controls/TextFileViewer.qml

Minor bugfixes related to status file monitoring and log display.

Status and Log minor fixes

---

meshroom/nodes/aliceVision/Meshing.py
meshroom/ui/components/scene3D.py
meshroom/ui/qml/Viewer3D/MaterialSwitcher.qml

Related to https://github.com/alicevision/AliceVision/pull/661
Enables the display of vertex-colored meshes in the 3D Viewer, by using a `PerVertexColorMaterial` if vertex color data is available on a mesh without textures.

Viewer3D: add support for vertex-colored meshes

---

meshroom/core/node.py
meshroom/ui/graph.py
meshroom/ui/qml/Viewer3D/Viewer3D.qml
meshroom/ui/qml/main.qml

This PR contains small bugfixes regarding ChunkMonitor + updates issues in the 3D viewer.
Simplify NodeChunk status monitoring by storing status file last modification time on the NodeChunk itself and avoid stopping/restarting the thread each time the list of NodeChunks in the graph changes. 
Also add "Refresh Node Status" menu item to force the update of nodes status manually. 
Switch to RenderSettings.Always to avoid update issues since Qt 5.13 when resizing the window or toggling visibilities of 3D objects.

Minor bugfixes

---

meshroom/ui/qml/Controls/ColorChart.qml
meshroom/ui/qml/Controls/qmldir
meshroom/ui/qml/Utils/Colors.qml
meshroom/ui/qml/Viewer/FeaturesInfoOverlay.qml
meshroom/ui/qml/Viewer/FeaturesViewer.qml
meshroom/ui/qml/Viewer/Viewer2D.qml
meshroom/ui/qml/WorkspaceView.qml
meshroom/ui/qml/main.qml
meshroom/ui/reconstruction.py

Based on QtAliceVision plugin, provide a viewer for extracted feature points within the 2D Image Viewer.
* Provides 3 visualization modes: Points, (scaled) Squares, Orientated Squares
* FeatureExtraction nodes can be double clicked to drive which node is used for the FeaturesViewer
* Component is loaded dynamically to evaluate QtAliceVision plugin availability - an error is displayed if the plugin fails to load:
* A picker with a predefined palette is available to select feature points colors

Features Viewer

---

meshroom/ui/qml/Charts/ChartViewCheckBox.qml
meshroom/ui/qml/Charts/ChartViewLegend.qml
meshroom/ui/qml/Charts/qmldir
meshroom/ui/qml/GraphEditor/NodeLog.qml
meshroom/ui/qml/GraphEditor/StatViewer.qml

Various fixes for the statistics visualization system.

StatViewer fixex

---

bin/meshroom_photogrammetry

This PR fixes a problem when using a custom pipeline in meshroom_photogrammetry: the views and the intrinsics that might have been read before from the a json/sfm file were not added to the graph, thus leading to failure when calling cameraInit in AliceVision.
```
[11:25:25.780397][error] Program need -i or --imageFolder option
```

[bin] Fix project creation from custom pipeline

---

meshroom/ui/qml/Viewer3D/AlembicLoader.qml
meshroom/ui/qml/Viewer3D/MediaLibrary.qml
meshroom/ui/qml/Viewer3D/MediaLoader.qml

Binding the "enabled" property of AlembicLoader's ObjectPicker to the parent MediaLoader's own "enabled" property caused invalid state where the loaded AlembicEntity was partially visible when toggling object visibility (since Qt 5.13).
In order to disable camera picking when AlembicEntity is disable, scale the camSelector component to 0.

[ui] Viewer3D: fix Alembic visibility issues

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

this PR add:
* 2 templates for github issues, bug report and feature request
* 1 template for pull requests
* CODE_OF_CONDUCT.md
* CONTRIBUTING.md
* cii badge

[github] add issue templates

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/question_help.md

Add a template only for questions and help needed, not related to program crashes and failures.

[GitHub] add template for questions / help only 

---

dev_requirements.txt

Specify cx_Freeze version to 5.1.1 since latest 6.0 is not compatible with Python 2.7 and breaks tests.

[build] fix cxFreeze version for Python 2.7 compatibility

---

meshroom/nodes/aliceVision/ConvertSfMFormat.py

The new ability to output dense point clouds via AliceVision's meshing utility produces an Alembic file that seems to look identical to the normal SfM Alembic files except that the `mvgPointCloud` entries have their feature type set to `unknown`. However, this option isn't set as one of the parameters in the `ConvertSfMFormat` meshroom wrapper.   As a result the node always strips out the points.  Adding an "unknown" feature type option to the wrapper allows the dense cloud to be converted properly.
If there's a better way, or a different change needed to save dense clouds to non-Alembic formats let me know and can take a look.  Thanks for all the great work on AliceVision, I'm a huge fan.

Add option to include 'unknown' feature types in ConvertSfMFormat

---

meshroom/nodes/aliceVision/StructureFromMotion.py
meshroom/ui/qml/Controls/TextFileViewer.qml
meshroom/ui/qml/ImageGallery/ImageGallery.qml
meshroom/ui/qml/MaterialIcons/MaterialToolButton.qml
meshroom/ui/qml/Viewer3D/AlembicLoader.qml
meshroom/ui/qml/Viewer3D/DefaultCameraController.qml
meshroom/ui/qml/Viewer3D/ImageOverlay.qml
meshroom/ui/qml/Viewer3D/Inspector3D.qml
meshroom/ui/qml/Viewer3D/Viewer3D.qml
meshroom/ui/qml/Viewer3D/Viewer3DSettings.qml
meshroom/ui/qml/Viewer3D/ViewpointCamera.qml
meshroom/ui/qml/Viewer3D/qmldir
meshroom/ui/qml/WorkspaceView.qml
meshroom/ui/qml/main.qml
meshroom/ui/reconstruction.py

This PR introduces a new feature that enables to synchronize 3D camera pose with the image selection. 
After the computation of the StructureFromMotion step, a dedicated 3D camera can be controlled by choosing an image from the input Images list, allowing to view the reconstruction from this image's POV (pose and field of view). 
If the PrepareDenseScene step is computed, the undistorted image can also be displayed as an overlay on the 3D view.
- 3D camera's field of view is computed using intrinsics solved by the SfM step.
- a 2D shader handles the principal point correction for the image overlay
- add new ViewpointWrapper python class to easily get data related to a reconstructed image

Sync 3D camera with image selection

---

bin/meshroom_photogrammetry
meshroom/core/__init__.py
meshroom/core/graph.py
meshroom/multiview.py
meshroom/ui/app.py
meshroom/ui/graph.py
meshroom/ui/reconstruction.py

This PR improves meshroom_photogrammetry and meshroom command lines.
- meshroom_photogrammetry: "--save" does not disable the computation so you can save your batch reconstruction project and open it later interactively in meshroom. Additionnal --compute option if you need only to create a meshroom project file from this command line.
- "meshroom -h / --help": now provides command line documentation
- meshroom: new positional argument to set project file
- meshroom: new "--pipeline" option to override the default pipeline with your own project file. It also supports an environment variable MESHROOM_DEFAULT_PIPELINE.
- meshroom_photogrammetry: new "--paramOverrides NODE.param=value" allows to set a parameter directly from the command line.
- minor change in photogrammetry() to keep the …

Improve command line arguments

---

meshroom/nodes/aliceVision/SfMAlignment.py
meshroom/nodes/aliceVision/SfMTransfer.py
meshroom/nodes/aliceVision/SfMTransform.py

See https://github.com/alicevision/AliceVision/pull/695

Coordinate system alignment to specific markers or between scenes

---

meshroom/multiview.py
meshroom/nodes/aliceVision/CameraInit.py
meshroom/ui/reconstruction.py

Add error popups when the import of images failed.

Images import popup on failure

---

meshroom/ui/components/filepath.py
meshroom/ui/qml/Viewer3D/DepthMapLoader.qml
meshroom/ui/qml/Viewer3D/EnvironmentMapEntity.qml
meshroom/ui/qml/Viewer3D/MediaLibrary.qml
meshroom/ui/qml/Viewer3D/MediaLoader.qml
meshroom/ui/qml/Viewer3D/Viewer3D.qml
meshroom/ui/qml/WorkspaceView.qml
meshroom/ui/qml/main.qml

Add support for displaying equirectangular images as environment maps in the 3D viewer.
Requires https://github.com/alicevision/QtOIIO/pull/13.

Viewer3D: Display equirectangular images as environment maps

---

meshroom/core/desc.py
meshroom/core/node.py
meshroom/ui/qml/GraphEditor/Node.qml

The goal of this PR is to be able to react to node's update to dynamically modify output parameters / node's size (in terms of parallelization).

[core] new "Node Update Hooks" mechanism

---

meshroom/core/__init__.py

Setting MESHROOM_SUBMITTERS_PATH caused meshroom to try to load the bundled
simpleFarmSubmitter plugin twice, ignoring the path in the variable.
I believe the problem lies with the way loadPlugins() works in meshroom.core,
because it's trying to import the package name "submitters" more than once.  The
second time, import_module() just returns a reference to the
This is a revised PR based on feedback from the first one I submitted last year,
which went stale and then got erased as I was stumbling my way through git.

Bugfix for MESHROOM_SUBMITTERS_PATH env variable

---

meshroom/multiview.py
meshroom/ui/app.py
meshroom/ui/graph.py
meshroom/ui/reconstruction.py

Command line adjustments

---

meshroom/core/__init__.py
meshroom/ui/qml/GraphEditor/CompatibilityManager.qml
meshroom/ui/qml/Viewer/Viewer2D.qml
meshroom/ui/qml/WorkspaceView.qml
meshroom/ui/reconstruction.py

New PR based on #657 (with a rebase to clean old merge commits).

Ability to load depth maps into 2D and 3D Viewers within meshroom

---

meshroom/ui/qml/GraphEditor/ChunksListView.qml
meshroom/ui/qml/GraphEditor/NodeEditor.qml
meshroom/ui/qml/GraphEditor/NodeStatistics.qml
meshroom/ui/qml/GraphEditor/NodeStatus.qml

NodeEditor: minor improvements with single tab group and status table

---

meshroom/__init__.py
meshroom/core/desc.py
meshroom/core/node.py

When computing on a single machine with very large ressources, the chunks can limit the ressources used.
A new environment variable `MESHROOM_USE_MULTI_CHUNKS` can be set to 0 to disable it.
Warning: If you mix usage with and without this option, the nodes status will be incoherent.

[core] Option to make chunks optional

---

meshroom/ui/qml/Viewer/FloatImage.qml
meshroom/ui/qml/Viewer/ImageToolbar.qml
meshroom/ui/qml/Viewer/Viewer2D.qml
meshroom/ui/qml/WorkspaceView.qml

Need plugin https://github.com/alicevision/QtAliceVision/pull/3

[ui] Add a new FloatImageViewer

---

meshroom/core/node.py
meshroom/nodes/aliceVision/Publish.py
meshroom/nodes/aliceVision/SketchfabUpload.py
setup.py

Fix for #780, the log is cleared directly from `processChunk` instead of relying on chunk.statusChanged

fix python nodes being blocked by log

---

.travis.yml

- Updates the build environment from Ubuntu 16.04 Xenial to Ubuntu 18.04 Bionic
- Removes Python 2.7 from the build matrix (since support has ended)
- Adds Python 3.8 to the build matrix

Travis CI: Update environment, remove Python 2.7 & add 3.8

---

meshroom/ui/qml/Charts/InteractiveChartView.qml
meshroom/ui/qml/Charts/qmldir
meshroom/ui/qml/Controls/Panel.qml
meshroom/ui/qml/GraphEditor/StatViewer.qml
meshroom/ui/qml/Viewer/FeaturesInfoOverlay.qml
meshroom/ui/qml/Viewer/FeaturesViewer.qml
meshroom/ui/qml/Viewer/ImageMetadataView.qml
meshroom/ui/qml/Viewer/MSfMData.qml
meshroom/ui/qml/Viewer/MTracks.qml
meshroom/ui/qml/Viewer/SfmGlobalStats.qml
meshroom/ui/qml/Viewer/SfmStatsView.qml
meshroom/ui/qml/Viewer/Viewer2D.qml
meshroom/ui/qml/WorkspaceView.qml
meshroom/ui/reconstruction.py

Add widgets to display SfM statistics.
Based on https://github.com/alicevision/QtAliceVision/pull/5

Add SfM Statistics

---

meshroom/ui/qml/ImageGallery/IntrinsicsIndicator.qml
meshroom/ui/qml/Viewer/ImageMetadataView.qml

Recognize images with non standard metadata as exported by Nuke on EXR images.
https://github.com/alicevision/AliceVision/pull/820

More generic metadata support

---

meshroom/nodes/aliceVision/CameraInit.py

https://github.com/alicevision/AliceVision/pull/823

[cameraInit] new viewId generation and selection of allowed intrinsics

---

appveyor.yml
dev_requirements.txt

- Updates the build environment to the Visual Studio 2019 image
- Use Python 3.8 in AppVeyor builds
- Saves the build folder as an artifact

AppVeyor: Update build environment and save artifacts

---

meshroom/nodes/aliceVision/LdrToHdrCalibration.py
meshroom/nodes/aliceVision/LdrToHdrMerge.py
meshroom/nodes/aliceVision/LdrToHdrSampling.py
meshroom/ui/graph.py

When a scene is generated from a script, the positions of the nodes are not initialized.
So when we load the scene in Meshroom UI, all nodes are in (0,0).
This PR recognize this particular case, and update the nodes layout automatically.

Automatically update layout when needed

---

meshroom/core/attribute.py
meshroom/core/desc.py
meshroom/core/node.py
meshroom/nodes/aliceVision/CameraInit.py
meshroom/nodes/aliceVision/ImageMatching.py
meshroom/nodes/aliceVision/ImageProcessing.py
meshroom/nodes/aliceVision/LdrToHdrMerge.py
meshroom/nodes/aliceVision/LdrToHdrSampling.py
meshroom/nodes/aliceVision/Meshing.py
meshroom/nodes/aliceVision/PanoramaInit.py
meshroom/ui/qml/GraphEditor/AttributeEditor.qml
meshroom/ui/qml/GraphEditor/AttributeItemDelegate.qml
meshroom/ui/qml/GraphEditor/NodeEditor.qml

'enabled' is a new parameter for the node's attributes. It allows to enable/disable the attribute. If it is disabled, the attribute will not be displayed inside the UI and will not be sent to the command line.
This is quite useful when an attribute is used only if another is checked, for instance.
'enabled' can receive either a boolean or a lambda function.
⚠️ Disabled parameters will not be used anymore in the UID. So it will change the invalidation status on existing projects. The major versions of the modified nodes are therefore changed.

[Nodes] Add a new 'enabled' parameter to node's attributes

---

meshroom/core/attribute.py

Disabled params should not be part of the UID computation, even for child attributes of an enabled GroupAttribute.
For instance, on the ImageProcessing node:
- Note the original "Output Folder"
- Enable "Sharpen Filter"
- Change "Width"
- Disable "Sharpen Filter"
- Should get the same value as the original "Output Folder" (even if the disabled "Sharpen Width" is not the same)

[core] GroupAttribute: check "enabled" property of child params in uid computation

---

meshroom/ui/components/__init__.py
meshroom/ui/components/csvData.py
meshroom/ui/qml/Viewer/CameraResponseGraph.qml
meshroom/ui/qml/Viewer/Viewer2D.qml

New button to display Camera Response Function graph inside the Viewer when a LdrToHdrCalibration node exists in the pipeline and is computed.
Works thanks to a new QObject class used to process CSV data.

[ui] Viewer: add Camera Response Function graph

---

meshroom/ui/qml/GraphEditor/StatViewer.qml

Before this change, the graph for the ram statistics used gigabytes as the unit, but [the actual value is in percent](https://github.com/alicevision/meshroom/blob/a24bfc14b0eb9a669c082b96950571c38cbdc128/meshroom/core/stats.py#L103).
- ram graph now uses % instead of gigabytes
- refactoring of the id names of ValueAxis items to be more readable e.g. `valueAxisY3` -> `valueGpuY`

[ui] Fix graph axes naming for ram statistics

---

meshroom/core/node.py
meshroom/ui/components/csvData.py
meshroom/ui/qml/Viewer/CameraResponseGraph.qml
meshroom/ui/qml/Viewer/Viewer2D.qml

Camera Response Function display crashes on linux with Qt 5.14.2.
to False but use visibility instead).

[ui] Camera Response Function display: fix instabilities on linux

---

meshroom/nodes/aliceVision/PanoramaInit.py

Add a parameter to panoramaInit :
XML input is giving a pose.
This parameter will update the input pose such that it adapts to a rotated image input.
Based on https://github.com/alicevision/AliceVision/pull/867

[nodes] PanoramaInit: New parameter to set an extra image rotation to each camera declared the input xml

---

meshroom/nodes/aliceVision/PanoramaWarping.py

Add control to select upscale ratio
Based on https://github.com/alicevision/AliceVision/pull/864

[nodes] PanoramaCompositing: option to select the percentage of upscaled pixels

---

meshroom/nodes/aliceVision/Texturing.py

Scale 1 could be better for objects, but is really too much for large environments.
It's better to have a default value which ensures that we can open the result.

[nodes] Texturing: put downscale to 2 by default

---

meshroom/ui/qml/Viewer/HdrImageToolbar.qml
meshroom/ui/qml/Viewer/Viewer2D.qml

Also update var names to use the fixes in: https://github.com/alicevision/QtAliceVision/pull/12

[ui] Viewer: fix gain/gamma and use non-linear sliders

---

meshroom/ui/qml/ImageGallery/ImageGallery.qml
meshroom/ui/qml/main.qml

[ui] init saveAs folder

---

meshroom/core/node.py
meshroom/multiview.py
meshroom/nodes/aliceVision/CameraLocalization.py
meshroom/nodes/aliceVision/CameraRigCalibration.py
meshroom/nodes/aliceVision/ConvertSfMFormat.py
meshroom/nodes/aliceVision/ExportMatches.py
meshroom/nodes/aliceVision/FeatureExtraction.py
meshroom/nodes/aliceVision/FeatureMatching.py
meshroom/nodes/aliceVision/FeatureRepeatability.py
meshroom/nodes/aliceVision/GlobalSfM.py
meshroom/nodes/aliceVision/PanoramaEstimation.py
meshroom/nodes/aliceVision/PanoramaInit.py
meshroom/nodes/aliceVision/SfMTransform.py
meshroom/nodes/aliceVision/StructureFromMotion.py
meshroom/ui/qml/main.qml

See https://github.com/alicevision/AliceVision/pull/935

[feature] sift: update default values, add new filtering and add dsp-sift variation

---

meshroom/nodes/aliceVision/LightingEstimation.py
meshroom/ui/qml/Viewer3D/MaterialSwitcher.qml
meshroom/ui/qml/Viewer3D/Materials/SphericalHarmonicsEffect.qml
meshroom/ui/qml/Viewer3D/Materials/SphericalHarmonicsMaterial.qml
meshroom/ui/qml/Viewer3D/Materials/shaders/SphericalHarmonics.frag
meshroom/ui/qml/Viewer3D/Materials/shaders/SphericalHarmonics.vert
meshroom/ui/qml/Viewer3D/Viewer3D.qml
meshroom/ui/qml/Viewer3D/Viewer3DSettings.qml

Requires https://github.com/alicevision/AliceVision/pull/797
See also:
alicevision/AliceVision/pull/604
alicevision/AliceVision/pull/560

[nodes] New node `LightingEstimation`

---

meshroom/core/attribute.py
meshroom/core/graph.py
meshroom/core/node.py
meshroom/core/taskManager.py
meshroom/multiview.py
meshroom/nodes/aliceVision/LdrToHdrCalibration.py
meshroom/nodes/aliceVision/PanoramaWarping.py
meshroom/ui/commands.py
meshroom/ui/graph.py
meshroom/ui/qml/GraphEditor/AttributePin.qml
meshroom/ui/qml/GraphEditor/Edge.qml
meshroom/ui/qml/GraphEditor/GraphEditor.qml
meshroom/ui/qml/GraphEditor/Node.qml
meshroom/ui/qml/Viewer/ImageMetadataView.qml
meshroom/ui/qml/Viewer/Viewer2D.qml

Connection from an input attribute to another input attribute does not represent a real dependency between the nodes: the 2nd node does not need to have the 1st node computed.
This PR adds the option `dependenciesOnly` to many graph functions to choose if we want to manipulate the user graph or the dependency graph.
With this PR many actions like duplicate nodes, remove nodes, remove data, etc are applied only to the dependency graph.

Graph Dependencies

---

meshroom/core/taskManager.py

Avoid to get trailing "submitted" chunks on the current node when we stop the computation.

[core] taskManager: downgrade status per chunk

---

bin/meshroom_photogrammetry
meshroom/core/attribute.py
meshroom/core/graph.py
meshroom/core/node.py
meshroom/multiview.py
meshroom/nodes/aliceVision/LdrToHdrMerge.py
meshroom/nodes/aliceVision/PanoramaEstimation.py
meshroom/nodes/aliceVision/PanoramaInit.py
meshroom/ui/qml/Controls/KeyValue.qml
meshroom/ui/qml/Controls/qmldir
meshroom/ui/qml/GraphEditor/AttributePin.qml
meshroom/ui/qml/GraphEditor/ChunksListView.qml
meshroom/ui/qml/GraphEditor/GraphEditor.qml
meshroom/ui/qml/GraphEditor/Node.qml
meshroom/ui/qml/GraphEditor/NodeEditor.qml
meshroom/ui/qml/GraphEditor/NodeLog.qml
meshroom/ui/qml/GraphEditor/NodeStatistics.qml
meshroom/ui/qml/GraphEditor/NodeStatus.qml
meshroom/ui/qml/GraphEditor/StatViewer.qml
meshroom/ui/qml/Utils/format.js
meshroom/ui/qml/Viewer3D/AlembicLoader.qml
meshroom/ui/reconstruction.py
tests/test_graph.py

https://github.com/alicevision/AliceVision/pull/964

Panorama: new options to init with known poses

---

meshroom/nodes/aliceVision/ConvertMesh.py
meshroom/nodes/aliceVision/MergeMeshes.py

Add two nodes for mesh boolean operations and mesh conversion.
See https://github.com/alicevision/AliceVision/pull/969

Add mesh utilities nodes

---

meshroom/nodes/aliceVision/MeshFiltering.py

Add smoothing and filtering options for MeshFiltering software.
See https://github.com/alicevision/AliceVision/pull/970

[nodes] MeshFiltering: smoothing & filtering on subset of the geometry

---

meshroom/ui/qml/main.qml

Small change to get a quick link to https://meshroom-manual.readthedocs.io within Meshroom. This makes it very easy to find the documentation.

[ui] add link to online documentation in 'Help' menu

---

meshroom/nodes/aliceVision/ExportAnimatedCamera.py

export distortion map in EXR Format
https://github.com/alicevision/AliceVision/issues/957
export undistort images with full ROD in EXR Format
https://github.com/alicevision/AliceVision/issues/956
https://github.com/alicevision/AliceVision/pull/963

[nodes] ExportAnimatedCamera: New option to export undistort maps in EXR format

---

meshroom/core/taskManager.py

After a renderfarm submit, it was not possible to compute the same node locally anymore.

[core] TaskManager: fix compute after submit

---

meshroom/multiview.py

On most platforms Meshroom and Alicevision are already build with libheif enabled, this commit enables Meshroom to also accept the files as known image formats.
Could be a bit buggy on platforms that don't build with libheif by default.

meshroom/multiview.py: Add .heic, .heif and .avif as supported formats

---

meshroom/core/stats.py

`io_counters` is not always available (e.g. under Ubunutu 20 run in WSL), resulting in an exception being throw.
See #1373 for a complete explanation of the issue.

Removing `io_counters` from the ProcStatatistics

---

meshroom/ui/graph.py
meshroom/ui/qml/GraphEditor/AttributePin.qml

This makes using the graph editor more efficient because if I have node A connected to node C but then I want to connect node B to node C instead then I would have to first delete the edge from node A to node C before it was possible to drag the edge from node B to node C. With these changes it is possible to do this without having to explicitly delete the previous edge.

Allow replacing edges

---

meshroom/ui/qml/GraphEditor/Node.qml

This change increases the radius of the node highlight so that the inner radius of the highlight is the same as the node. This makes it so that there is no longer a gap between the highlight and the node at the corners. 
Before:
After:

Node highlight radius

---

meshroom/common/qt.py
meshroom/core/graph.py
meshroom/core/node.py
meshroom/ui/commands.py
meshroom/ui/graph.py
meshroom/ui/qml/GraphEditor/GraphEditor.qml
meshroom/ui/qml/GraphEditor/Node.qml
tests/test_graph.py

The ability to select multiple nodes at once improves the efficiency of using the graph editor. I have tried to make the node selection behave similar to blender. The box select widget is used by dragging with the left mouse button. The main selected node is slightly brighter than the other selected nodes and has a blue border.
- select multiple nodes at once
- use of control key modifier to select multiple nodes
- use of box select widget to select multiple nodes
- duplicate selected nodes
- remove selected nodes
- delete data of selected nodes
- move selected nodes together
(Resolves some points on #269)

[ui] add support for selecting multiple nodes at once

---

meshroom/multiview.py
meshroom/nodes/aliceVision/CameraInit.py
meshroom/nodes/aliceVision/DistortionCalibration.py
meshroom/ui/reconstruction.py

Update camerainit node to accept new kind of cameras.
Update camerainit node such that a camera has two focal lengths in pixels (both horizontal and vertical)
Add a distortion calibration node
Based on https://github.com/alicevision/AliceVision/pull/1035

New lens distortion calibration node

---

start.bat

Simple .bat script to start Meshroom. Requires aliceVision and qtPlugins binaries in the same folder.

Add cli script to start Meshroom on Windows

---

setupInitScriptUnix.py

In cx_Freeze 6.7, released last week, the startup code was changed so the run() function in the startup module is given the name of the main module as an argument.  This causes meshroom to fail to start on Linux (and presumably also on macOS, which uses the same startup script) with a confusing error:
```
Traceback (most recent call last):
File ".../cx_Freeze/initscripts/__startup__.py", line 104, in run
module_init.run(name + "__main__")
TypeError: run() takes 0 positional arguments but 1 was given
```
This change makes meshroom compatible with new cx_Freeze, while retaining the old behaviour if run() received no arguments.

Fix incompatibility with recent cx_Freeze

---

meshroom/ui/qml/main.qml

New button in the file menu to clear all images from the scene.
This means it deletes all the viewpoints and intrinsics from all the camera inits present in the scene.

[ui] Add a clear images button 

---

README.md
start.sh

Improve the documentation to be able to run Meshroom without building UI (tested only on Ubuntu 20.04 LTS)
How to run and debug with PyCharm
Add information about downloading meshroom release directly, as I've seen users on reddit not aware about the existence of the built version
No feature
This is an complex workflow just a small change in the documentation. Not sure if this is the right way to do.

Documentation update : how to use Meshroom without building AliceVision

---

bin/meshroom_batch
meshroom/multiview.py
meshroom/ui/qml/main.qml
meshroom/ui/reconstruction.py

In order to easier the use of Meshroom for user who don't have an NVIDIA CUDA card, I think that it is important to be able to start a project with the appropriate pipeline without customing it manually.
Related with wiki page https://github.com/alicevision/meshroom/wiki/Draft-Meshing
Add File > New Pipeline > Photogrammetry (No CUDA)
Use the same parameters than others pipelines
An alternative would be to https://github.com/alicevision/AliceVision/issues/439 or to make it compatible with OpenMVS which doesn't need CUDA

Draft Reconstruction pipeline

---

meshroom/ui/graph.py
meshroom/ui/qml/Viewer/FloatImage.qml
meshroom/ui/qml/Viewer/HdrImageToolbar.qml
meshroom/ui/qml/Viewer/LensDistortionToolbar.qml
meshroom/ui/qml/Viewer/PanoramaToolbar.qml
meshroom/ui/qml/Viewer/PanoramaViewer.qml
meshroom/ui/qml/Viewer/Viewer2D.qml
meshroom/ui/reconstruction.py

New button to preview the panorama inside a new viewer.
Tools to edit the panorama dynamically before the SfMTranform node computation.
New button to display the lens distortion inside the FloatImageViewer when a SfMData node exists in the panorama HDR pipeline and is computed.
Panorama Viewer : 
Lens distortion :
This PR is linked to the following in the QTAliceVision plugin : https://github.com/alicevision/QtAliceVision/pull/17

[ui] Add Panorama Viewer

---

bin/meshroom_newNodeType

- allow executable with multiple arguments
- force utf8 conversion
- fix typo in help

[bin] newNodeType: update

---

meshroom/core/attribute.py
meshroom/ui/reconstruction.py

This PR fixes a couple of deprecation warnings with Python 3:
- import "collections" correctly depending on the used version of Python (fixes `DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working`)
- use a raw string for a regex compilation (fixes `DeprecationWarning: invalid escape sequence \{`)

Fix compatibility with Python 3

---

meshroom/ui/qml/GraphEditor/AttributePin.qml

Fix the offset between the tip of the connecting edge and the position of the mouse that could appear when the user quickly dragged the mouse away from the attribute pin. The offset could at times be extremely large, causing issues when trying to connect the edge somewhere (the user needed to position the tip of the edge on the attribute pin with the mouse being positioned sometimes really far away from said attribute pin).

[ui] Fix offset between the mouse's position and the tip of the edge when connecting two nodes

---

meshroom/core/graph.py
meshroom/ui/commands.py
meshroom/ui/graph.py
tests/test_graph.py

Fix corner cases that could lead to some errors when duplicating or removing nodes: 
- a node could be duplicated several times at once but only the first duplicate was stored, causing the "undo" operation to not remove any of the duplicates for that specific node beyond the first one; additionally, duplicated nodes could get stacked on top of other nodes, "hiding" them.
- there could be attempts to remove a single nodes several times at once, causing errors.
Change the ambiguous behaviour of the "duplicate node(s) from here" action that could lead to duplicating several times the same node unwillingly.

Fix node duplication/removal behaviour

---

bin/meshroom_batch
meshroom/core/desc.py
meshroom/core/graph.py
meshroom/nodes/aliceVision/CameraInit.py

This PR adds the abstract class "InitNode" which is meant to be inherited by all the initialization nodes (such as CameraInit), included those that might be created by the user. InitNode contains methods that can be reimplemented by the children classes if necessary.
This abstract class allows to keep on using scripts (such as meshroom_batch) without being limited to the use a specific initialization node (like it used to be with CameraInit in the case of meshroom_batch, for example), needing to have the knowledge of the used initialization node and/or having to modify the scripts as a workaround.

Add abstract InitNode

---

meshroom/ui/qml/ImageGallery/ImageGallery.qml

This PR fixes a UI bug that would cause the displayed intrinsics table to always be the first CameraInit node's, no matter which group the user wanted to display. The intrinsics table was loaded once on the first CameraInit node and never reloaded after that, so if there was more than a single CameraInit node in the graph, the corresponding tables could not be displayed.
The intrinsics table is now correctly reloaded when the group index is changed.

[ui] Update intrinsics table when switching between groups

---

meshroom/ui/app.py

Currently we disable all logging out of qml by default. This is problematic in case qml loading fails for any reason (e.g. missing dependencies) as the user will be presented with a message that is not actionable: "QQmlApplicationEngine failed to load component". There is no way to understand what's happening unless the user knows about MESHROOM_OUTPUT_QML_WARNINGS.
This is improved by checking for presence of "QQmlApplicationEngine failed to load component" and warning if qml logging is disabled in that case.
There has been many issues with this log message and no further logs in the bug tracker, so I'm not the only one who hit this issue. Hopefully this improves debugging experience for everyone.

[ui] Reduce confusion when qml loading fails

---

meshroom/core/attribute.py
meshroom/core/graph.py
meshroom/core/node.py
meshroom/pipelines/cameraTracking.mg
meshroom/pipelines/panoramaFisheyeHdr.mg
meshroom/pipelines/panoramaHdr.mg
meshroom/pipelines/photogrammetry.mg
meshroom/pipelines/photogrammetryAndCameraTracking.mg
meshroom/pipelines/photogrammetryDraft.mg
meshroom/ui/app.py
meshroom/ui/graph.py
meshroom/ui/qml/main.qml

Following #1727, project files can be used as templates, with the .mg files containing the entire description of the graph. This implies that if there is a single node whose description is modified (parameters added, parameters removed, etc.), description conflicts will arise when opening a template containing such a node. For these conflicts to be resolved, the template would need to be saved again with the upgraded version of the node every single time there is a change, which defeats the purpose of having templates.
This PR adds a "minimal" mode to save and load templates. Instead of saving the entire graph description, the minimal mode only saves the modified input/output parameters. When that template is opened, conflicts are detected only on the saved parameters (with non-default …

Add dedicated "minimal" mode for templates

---

meshroom/nodes/aliceVision/FeatureMatching.py

Option to remove matches without enough motion between the two observations
May be useful to remove matches caused by dirt/dust on sensor
May be useful to remove background features on turning tables
See AliceVision PR :  https://github.com/alicevision/AliceVision/pull/1198

[Feature Matching] Add an option to remove matches without enough motion

---

bin/meshroom_batch
meshroom/core/graph.py

meshroom_batch was not working because of a duplicated call to findNodes.
Removed the duplicated call and modified the submit function.

removed duplicated call to findnodes

---

meshroom/core/node.py
meshroom/ui/qml/GraphEditor/NodeEditor.qml

This PR displays, for a node whose status is either "FINISHED" or "RUNNING", the computation time in the title bar of the node. For nodes with several chunks, the displayed time corresponds to the cumulated computation time of every chunk; in that case, the computation time for the longest chunk is also displayed in a tooltip.

[ui] Display computation time for "running" or "finished" nodes

---

meshroom/nodes/aliceVision/CameraInit.py

CameraInit node: all intrinsics parameters should invalidate the output.

[nodes] CameraInit: all intrinsics parameters should invalidate

---

meshroom/core/graph.py

When a scene is saved as a template, a flag named "template" is set to "true" in the header of the .mg file. 
Prior to this PR, and since #1754, that flag was never explicitly set to "false" when saving a scene as a regular project, meaning that any pipeline built on top of a template pipeline was necessarily saved with "template" set to "true".

[core] Set the "template" flag to "false" when saving a project as a regular file

---

meshroom/ui/qml/GraphEditor/GraphEditor.qml
meshroom/ui/qml/main.qml

This PR fixes an issue introduced with #1758 which overrides any Ctrl+C / Ctrl+V shortcut with a "Copy node(s)" / "Paste node(s)", no matter which part of Meshroom has the focus or which element is currently selected.
If a Ctrl+C or Ctrl+V shortcut is performed outside the GraphEditor, the performed action should not be a copy or a paste of the nodes, but the own copy/paste of the current element. For example, if the currently selected element is a text field in the NodeEditor, then using Ctrl+C shoud trigger that text field's own copy function and copy its content to the clipboard; "Copy node(s)" and "Paste node(s)" should only be called when Ctrl+C and Ctrl+V are performed within the GraphEditor.

[ui] Restrain the "copy/paste nodes" shortcuts to the GraphEditor

---

meshroom/core/graph.py
meshroom/ui/commands.py
meshroom/ui/graph.py
meshroom/ui/qml/main.qml

When clicking on File->Open to open a .mg project, the file dialog will open at the most recent project's directory instead of the default directory for convenience.

Use most recent project as base folder for file dialogs

---

meshroom/pipelines/cameraTracking.mg
meshroom/pipelines/panoramaFisheyeHdr.mg
meshroom/pipelines/panoramaHdr.mg
meshroom/pipelines/photogrammetry.mg
meshroom/pipelines/photogrammetryAndCameraTracking.mg
meshroom/pipelines/photogrammetryDraft.mg

This PR upgrades the version of the CameraInit nodes in the templates. 
The CameraInit node's version was last updated with #1747.

[pipelines] Update CameraInit version from 7.0 to 8.0 in templates

---

meshroom/ui/graph.py
meshroom/ui/qml/GraphEditor/GraphEditor.qml

When using the Edit > Paste action menu, or when pressing Ctrl+V while the Graph Editor has the focus but does not contain the mouse, there is no current mouse position within the GraphEditor. The position that is provided to the "pasteNodes" function is the last known mouse position within the Graph Editor, which oftentimes corresponds to its borders.
Instead of using the border of the Graph Editor as the top-left corner of the pasting zone (the zone in which all the nodes contained in the clipboard will be pasted, with their original distance to one another preserved), this PR simulates the mouse's position and sets it at the center of the Graph Editor. This position is then used as the center of the pasting zone instead of its top-left corner. Distances between the pasted nodes remain …

[ui] Paste nodes at the center of the Graph Editor when it does not contain the mouse

---

meshroom/ui/qml/Controls/TextFileViewer.qml
meshroom/ui/qml/GraphEditor/NodeEditor.qml
meshroom/ui/qml/Utils/Colors.qml
meshroom/ui/qml/Utils/format.js

The goal of this PR is to enrich the node log viewer so that finding the steps that require long calculations is easier for users. To achieve that, we retrieve the time value of each log-line (when it exists) and we display the elapsed time between consecutive time values.
We add 2 visual indicators: 
- a colored marker next to the line number
- a tooltip when hovering over the line number cell displaying the elapsed time.

[ui] Elapsed time indicators in log

---

.readthedocs.yaml
docs/.gitignore
docs/Makefile
docs/README.md
docs/make.bat
docs/requirements.txt
docs/source/_ext/fetch_md.py
docs/source/_ext/meshroom_doc.py
docs/source/_ext/utils.py
docs/source/_templates/autosummary/class.rst
docs/source/_templates/autosummary/module.rst
docs/source/api.rst
docs/source/changes.rst
docs/source/conf.py
docs/source/index.rst
docs/source/install.rst
meshroom/__init__.py
meshroom/common/__init__.py
meshroom/ui/__init__.py
meshroom/ui/__main__.py

This PR introduces a documentation generation process using Sphinx for the Meshroom Python API.
The process also supports including the content of markdown files that belong to the project (such as `README.md`, `INSTALL.md`, etc.) for convenience using a custom directive called `fetch_md`.
The instructions for building the documentation are stored in `docs/README.md`.
- we use a custom `module.rst` template for the `autosummary` extension in Sphinx to have a more fine-grain control over the stub generation process and to be able to correct errors that occur during that process
- when importing markdown content with the `fetch_md` directive, the links based on relative paths are not valid anymore, so we try to re-link them (see the `Relinker` class), but for now this only works for images …

[docs] Python documentation generation using Sphinx

---

meshroom/core/graph.py
meshroom/pipelines/cameraTracking.mg
meshroom/pipelines/panoramaFisheyeHdr.mg
meshroom/pipelines/panoramaHdr.mg
meshroom/pipelines/photogrammetry.mg
meshroom/pipelines/photogrammetryAndCameraTracking.mg
meshroom/pipelines/photogrammetryDraft.mg
tests/test_templatesVersion.py

This PR adds a unit test that checks, for every template, whether there are conflicts on the contained nodes: the test will fails if at least one node needs to be upgraded (either because its version is not the most recent or because there is a description conflict). Templates containing nodes that are not up-to-date can still be opened in Meshroom: they will still automatically be upgraded (unlike "regular" .mg files, which require user confirmation to be upgraded). The aim of this test is mainly to let committers know whether their changes affect the templates.
Additionally, node UIDs, outputs, internal folder and parallelization parameters are not saved anymore in templates as they are not relevant, and the existing templates have been cleansed of them.

Add a unit test to check the node versions of templates

---

meshroom/ui/qml/main.qml

Importing images with the "Import Image" action causes a crash if the images contain non-ASCII characters in their filepath.
This was apparently a problem on the QML side, occurring when we were trying to log the urls. Removing the log line seems to have fixed the issue.
> However I did not find any issue online related to this specific logging problem, this might require further investigation to understand exactly the origin of the crash

Fix crash when importing images with non-ascii characters in their filepath

---

meshroom/ui/components/scene3D.py
meshroom/ui/qml/Viewer3D/MeshingBoundingBox.qml

Bounding box for the meshing node 
The bounding box manipulator was not storing parameters in the correct geometric frame

Update bounding box display to use the correct geometric frame

---

meshroom/ui/components/scene3D.py
meshroom/ui/qml/Viewer/PanoramaViewer.qml

New manipulator for panoramaviewer :
If no key is pressed :
On mouse pressed :  select a point on the panorama
On mouse moved : rotate the panorama such that the selected point is at the new mouse coordinates, keeping the vertical similar.
If CTRL key is pressed
On mouse pressed :  select a point on the panorama
On mouse moved : rotate the panorama such that it is rotated around the selected point (~In image rotation)

[ui] Improve the manipulator of the panorama viewer

---

meshroom/ui/app.py
meshroom/ui/qml/Viewer/Viewer2D.qml

This PR enables the HDR viewer (float image viewer) by default in the 2D Viewer instead of the 8-bit image viewer. 
The 8-bit image viewer becomes unavaible unless the QtAliceVision plugin (which provides the HDR viewer) is unavailable or Meshroom is started with a specific environment variable, `MESHROOM_USE_8BIT_VIEWER`:
- If the HDR viewer is available and the environment variable is provided, the 8-bit viewer can be used by disabling the HDR viewer through the interface;
- If the QtAliceVision plugin is unavailable for any reason, the 8-bit image viewer is necessarily used
The behaviours of the other viewers (i.e. lens distortion, feature display, panorama viewers) remain unchanged.

[ui] Viewer 2D: enable the HDR viewer by default

---

meshroom/ui/qml/GraphEditor/GraphEditor.qml

This PR introduces a new keyboard shortcut in the graph editor: TAB to open the node menu (same behavior as right clicking).
This has been requested by a user, the main reason being that this shortcut is used in several other programs (Houdini, Maya, Nuke, etc.).

[ui] keyboard shortcut: press tab to open node menu

---

meshroom/ui/qml/ImageGallery/ImageGallery.qml

When a project file is opened, its images are first loaded in the ImageGallery, which displays them in a GridView. The first image in the gallery is automatically selected within that GridView and then displayed in the Viewer2D, with an auto-fit applied so it can fit in the viewer. The image displayed in the Viewer2D is then updated according to the one that is selected in the ImageGallery, in which every image is identified by its index within the GridView. 
This PR addresses two issues related to the indices update within the GridView:
1. If the currently selected image is the first one in the gallery and another .mg file is opened, the new first image in the gallery, which will automatically be selected, will not properly be displayed in the Viewer2D: the auto-fit will not be applied …

[ui] ImageGallery: update the Viewer2D correctly when the GridView's current item changes

---

bin/meshroom_batch
meshroom/core/desc.py

Fix https://github.com/alicevision/Meshroom/issues/1797
Currently it is not possible to pass a list of values with the `--paramOverrides` argument of `meshroom_batch`, which is problematic when overriding non-exclusive choice parameters, such as `FeatureExtraction:describerTypes`.
This PR provides the following mechanism to fix this issue: if the input string contains at least one comma it will be interpreted as a list of values (split around the commas), otherwise it will be interpreted as a single value.

[bin] meshroom_batch: allow passing list of values to param overrides

---

meshroom/ui/qml/Viewer/Viewer2D.qml

This PR fixes one actual bug with the Viewer2D, and two minor UI issues:
- After dropping an external image in the 2D viewer, it was impossible to display another image from the Image Gallery, no matter whether it was selected with a click or with the arrow keys;
- The "Clear node" button was displayed in the 2D viewer, although disabled, even when there was no node to unload, hence creating some confusion;
- The ComboBox containing the currently loaded node's output attributes could be opened even when no node was loaded (the only default option, "Image Gallery", was dropping down when the user clicked on it).

[ui] Viewer2D: fix minor issues

---

meshroom/ui/app.py
meshroom/ui/commands.py
meshroom/ui/graph.py
meshroom/ui/qml/GraphEditor/GraphEditor.qml

This PR adds a "Pipelines" category to the node menu (opened with a right click or a press of the TAB key in the GraphEditor) which contains the list of available templates. Selecting a pipeline through the menu creates said pipeline into the current scene, with its top-left corner being placed on the mouse's position. Pipelines can be searched using the search bar at the same time as any node type.
- Creating a pipeline with the node menu is functionally akin to importing a template into the current project, and moving it to the mouse's position (instead of leaving it below the current graph).
- The "Pipelines" category's creation is hard-coded, and then filled with the list of the available templates' names. 
- Since the "Pipelines" category is added as a regular one, it is …

[ui] GraphEditor: create new pipelines with the node menu

---

meshroom/core/graph.py
meshroom/core/node.py
meshroom/ui/graph.py

This PR fixes two bugs related to local graph computations:
- When computing a graph in an instance of Meshroom, and opening the same computing graph in another instance of Meshroom, the second instance of Meshroom behaves as if it was performing the computations even though it was not. As a consequence, trying to open a new graph was failing (Meshroom would try stopping the computations, but fail since they were carried out by the first instance), and so was closing the instance, with a "Please stop any local computation before exiting Meshroom" error message. Only the chunks' statuses were taken into account to determine whether local computations were ongoing.
- When loading a new graph while the opened one was locally computing nodes, computations were automatically stopped to be able …

[ui] Correctly determine if a graph is being computed locally and update nodes' statuses accordingly

---

bin/meshroom_batch
bin/meshroom_submit
meshroom/core/graph.py
meshroom/core/submitter.py
meshroom/core/taskManager.py
meshroom/submitters/simpleFarmSubmitter.py
meshroom/ui/app.py
meshroom/ui/graph.py
meshroom/ui/reconstruction.py

This PR adds an option, `--submitLabel`, to both the scripts (meshroom_batch) and the Meshroom app to set the title of jobs that are submitted. If a job is submitted with `--submitLabel` unset, the default name of the job will be "x [Meshroom]", with x the name of the submitted .mg file.

[submitters] Add an option to update the job title on submitters

---

meshroom/ui/qml/GraphEditor/CompatibilityManager.qml
meshroom/ui/qml/GraphEditor/GraphEditor.qml
meshroom/ui/qml/GraphEditor/NodeDocumentation.qml
meshroom/ui/qml/GraphEditor/TaskManager.qml
meshroom/ui/qml/ImageGallery/ImageDelegate.qml
meshroom/ui/qml/ImageGallery/ImageGallery.qml
meshroom/ui/qml/LiveSfmView.qml
meshroom/ui/qml/Viewer/Viewer2D.qml
meshroom/ui/qml/Viewer3D/AlembicLoader.qml
meshroom/ui/qml/Viewer3D/Inspector3D.qml
meshroom/ui/qml/Viewer3D/Viewer3D.qml
meshroom/ui/qml/WorkspaceView.qml
meshroom/ui/qml/main.qml

Some QML properties access exposed Python objects that may or may not be null upon their access. When these objects are accessed while null, QML issues "TypeError" warnings. These warnings have no functional impact as QML correctly handles trying to access null objects, but can spam the logs.
This PR fixes all these warnings by ensuring that the Python objects are not null before they are accessed by QML properties. In case the objects are null, default values are returned instead of still attempting to access them anyway.

[ui] Fix all "TypeError" QML warnings

---

requirements.txt

There are 1 security vulnerabilities found in psutil 5.6.3
- [CVE-2019-18874](https://www.oscs1024.com/hd/CVE-2019-18874)
Upgrade psutil from 5.6.3 to 5.6.7 for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
Signed-off-by:pen4<948453219@qq.com>

fix(sec): upgrade psutil to 5.6.7

---

meshroom/nodes/aliceVision/ColorCheckerCorrection.py
meshroom/nodes/aliceVision/ColorCheckerDetection.py
meshroom/nodes/aliceVision/ImageProcessing.py
meshroom/nodes/aliceVision/KeyframeSelection.py
meshroom/nodes/aliceVision/LightingEstimation.py
meshroom/nodes/aliceVision/MergeMeshes.py
meshroom/nodes/aliceVision/SfMAlignment.py
meshroom/nodes/aliceVision/SfMDistances.py
meshroom/nodes/aliceVision/SfMTransfer.py
meshroom/nodes/aliceVision/SfMTransform.py
meshroom/nodes/aliceVision/Split360Images.py

Based on https://github.com/alicevision/AliceVision/pull/1318

[nodes] rename: remove "utils" from executables names

---

meshroom/ui/qml/main.qml

This PR simplifies and reorganizes Meshroom's "File" menu as follows:
- The "New" action has been removed and the "Ctrl+N" shortcut that is used to create new default (photogrammetry) pipelines remains valid;
- The "Save As Template" and "Import Project" actions have been moved to the new "Advanced" sub-menu;
- Separators have been added between different menu categories (new/open files, save files, import images, advanced, quit).
The changes are shown below (left: before the PR; right: with the PR):

[ui] Reorganize the "File" menu

---

meshroom/ui/qml/ImageGallery/ImageGallery.qml

The "cacheBuffer" property determines whether delegates are retained outside the visible area of view. In the case of the ImageGallery, it determines whether the images that are not currently visible in the GridView (because we need to scroll up or down to be able to see them) will remain in the cache or not. The default value is platform-dependent (but seems to be 320 for maintream systems) and currently causes any image that is not directly visible to be lost, even if it was previously loaded when it appeared in the view: if we scroll up or down, we will necessarily need to wait for the images to be loaded again.
This PR increases the value of the "cacheBuffer" property to keep more images, even if they are not currently visible, in the cache. This improves the navigation in the Image …

[ui] ImageGallery: Increase the GridView's cache capacity

---

meshroom/submitters/rippleSubmitter.py

Add a submitter for an in-house tool called ripple to compute on renderfarm.

Add Ripple submitter

---

meshroom/ui/qml/Viewer/Viewer2D.qml
meshroom/ui/qml/WorkspaceView.qml

This PR introduces a new checkbox to enable/disable the 8-bit viewer: 
The default value of this checkbox can be changed with the `MESHROOM_USE_8BIT_VIEWER` environment variable.

[ui] Checkbox to enable/disable 8-bit viewer

---

meshroom/ui/qml/Viewer/Viewer2D.qml
meshroom/ui/qml/Viewer3D/MediaLibrary.qml
meshroom/ui/qml/Viewer3D/Viewer3D.qml
meshroom/ui/qml/WorkspaceView.qml

This PR introduces some minor improvements around loading depth maps in 3D: 
- the "View Depth Map in 3D" button in the 2D viewer is enabled only when the currently viewed attribute corresponds to a depth map
- when loading a depth map in the 3D viewer with this button, a custom label is used in the 3D inspector composed of the node name, attribute name and view id.

[ui] Load 3D Depth Map: minor improvements

---

meshroom/nodes/aliceVision/CameraInit.py
meshroom/nodes/aliceVision/LdrToHdrCalibration.py
meshroom/nodes/aliceVision/LdrToHdrMerge.py
meshroom/nodes/aliceVision/LdrToHdrSampling.py
meshroom/pipelines/panoramaFisheyeHdr.mg
meshroom/pipelines/panoramaHdr.mg

Update rawColorInterpretation default value and add some comments in cameraInit node.
Add working color space as input parameter in Sampling, Calibration and Merging HDR nodes.
Update HDR pipelines accordingly.
Based on https://github.com/alicevision/AliceVision/pull/1328

Use DCP by default if the database is set and create errors on missing DCP files

---

meshroom/ui/qml/ImageGallery/ImageGallery.qml

When opening the dialog to edit the sensor database, the displayed path of the database was not resolved. Instead, the environment variable that contains it was displayed:
This PR displays the resolved path to the sensor database instead. As a direct consequence, the "Copy Path" button does indeed copy the absolute path to the sensor database (rather than the environment variable itself), and the "Open in External Editor" button can be used again to open the database in the set editor.

[ui] ImageGallery: fix the DB path in the "Edit Sensor Database" dialog

---

meshroom/nodes/aliceVision/SfMTriangulation.py
meshroom/nodes/aliceVision/Triangulate.py

Adds a main that is essentially the triangulation step from the sequential SfM.
AliceVision PR: https://github.com/alicevision/AliceVision/pull/1314
This allows to run the triangulation without going into the sfm step.

[nodes] new SfMTriangulation node

---

meshroom/ui/qml/Controls/ExifOrientedViewer.qml
meshroom/ui/qml/Controls/qmldir
meshroom/ui/qml/Viewer/Viewer2D.qml

The goal of this PR is to support all [Exif orientation tags](http://sylvana.net/jpegcrop/exif_orientation.html) in the 2D viewer, which only handles tags 6 and 8 at the moment.
We also solved a bug with the features viewer not being at the right position with some orientation tag (noticed with orientation tag 6): 
Historically the 8bit viewer had to be handled differently than the other viewers because it is backed by Qt Images which handle orientation at the C++ level (therefore in the qtAliceVisionImageIO plugin in our case). 
This automatic transform has been disabled to make sure we can control all viewers with the same mechanism.
The float viewer, 8bit viewer and features viewer have been tested on all Exif orientations (including images with no orientation metadata) on several …

[ui] Viewer2D: support all Exif orientation tags

---

meshroom/ui/qml/GraphEditor/GraphEditor.qml

Put the scale to 1 when fitting the graph to prevent huge node/text when there are only a few nodes.

[ui] GraphEditor: use maxZoom to fit on nodes

---

meshroom/ui/app.py
meshroom/ui/qml/ImageGallery/ImageGallery.qml
meshroom/ui/qml/WorkspaceView.qml
meshroom/ui/qml/main.qml

Since #1778, all the actions from the "File" menu that open dialogs use the folder of the .mg file that was opened last as the base folder. 
This is also the case for the "Import Images" dialog, which means that at each import, the dialog opens in the folder containing the most recently opened .mg file rather than the most recently imported images. 
This PR changes that behaviour by saving the location of the last imported images, and using it as the base folder specifically for the "Import Images" dialog. The new behaviour can be summed up as follows:
- The last 3 locations of the imported images are saved across Meshroom sessions and used as a base folder (if the most recent location is not valid anymore, it is dropped and the second most recent location is used, and so on until either …

[ui] Use the location of the most recently imported images as the base folder for the "Import Images" dialog

---

meshroom/core/node.py
meshroom/ui/qml/GraphEditor/Node.qml

This PR contains a bugfix and a minor UI improvement:
- Bugfix: a node used to be considered as computed externally if and only if its first chunk's execution mode was external. This is true in most cases but it does not cover the cases of nodes that are computed both locally and externally: if computations are started locally, interrupted and resumed externally, any chunk that completed its computations locally will have its execution mode set as such. When resuming the computations externally, the first chunk will still indicate that its execution mode is local, so the whole node will be treated as computed locally.
A node is now considered as computed externally if at least one of its chunks' execution mode is external.
- The "Computed Externally" icon used to be display on a node only …

[ui] Display nodes computed in another Meshroom instance as "Computed Externally"

---

meshroom/nodes/aliceVision/CameraInit.py
meshroom/pipelines/cameraTracking.mg
meshroom/pipelines/panoramaFisheyeHdr.mg
meshroom/pipelines/panoramaHdr.mg
meshroom/pipelines/photogrammetry.mg
meshroom/pipelines/photogrammetryAndCameraTracking.mg
meshroom/pipelines/photogrammetryDraft.mg

The PR https://github.com/alicevision/Meshroom/pull/1863 changes the order of parameters and modify the node UID, so it requires a version upgrade.

[nodes] CameraInit: upgrade version following the parameters changes

---

meshroom/ui/app.py
meshroom/ui/components/thumbnail.py
meshroom/ui/qml/ImageGallery/ImageDelegate.qml
meshroom/ui/qml/ImageGallery/ImageGallery.qml

This PR introduces a new caching mechanism for thumbnails to improve interactivity when navigating in the Image Gallery.
This cache associates to each image a unique thumbnail, which is stored on disk for later reuse.
The storing location is global (i.e not specific to a Meshroom scene).
The default location can be overriden with the `MESHROOM_THUMBNAIL_DIR` environment variable.
The thumbnails dimensions cannot exceed 256x256, and are stored on disk in JPEG format.
On the tested dataset, their size vary between 6 and 11 Ko (per thumbnail).
When launching the application, the cache directory is scanned and all thumbnails that haven't been used for more than a certain time limit are removed. This process also makes sure that the number of thumbnails on disk does not exceed a certain limit. …

[ui] Thumbnail cache

---

meshroom/nodes/aliceVision/LdrToHdrCalibration.py
meshroom/nodes/aliceVision/LdrToHdrMerge.py
meshroom/nodes/aliceVision/LdrToHdrSampling.py
meshroom/pipelines/panoramaFisheyeHdr.mg
meshroom/pipelines/panoramaHdr.mg

LdrToHdrMerge node: Add a checkbox enabling the manual setting of the reference bracket for HDR merging
Based on https://github.com/alicevision/AliceVision/pull/1315

Ldr to hdr merging checkbox

---

meshroom/ui/qml/Viewer/FeaturesInfoOverlay.qml
meshroom/ui/qml/Viewer/FeaturesViewer.qml

This PR introduces the "display track endpoints" option in the features viewer.
See https://github.com/alicevision/QtAliceVision/pull/25 for details.

[ui] FeaturesViewer: track endpoints

---

meshroom/ui/qml/Controls/ExifOrientedViewer.qml
meshroom/ui/qml/Utils/ExifOrientation.qml
meshroom/ui/qml/Utils/qmldir
meshroom/ui/qml/Viewer3D/ImageOverlay.qml
meshroom/ui/qml/Viewer3D/Viewer3D.qml
meshroom/ui/reconstruction.py

This PR fixes the "Sync Camera with Image Selection" feature in the 3D viewer.
- use the correct formulas for the camera rotation and translation
- apply exif orientation tag of input image to 3D viewer in order to match 2D viewer.
The image used as overlay is not exactly the input image but its undistorted version computed by the PrepareDenseScene node. This means that if the PrepareDenseScene node has not been computed or does not exist (for example in a CameraTracking pipeline), there won't be a background image.
A more robust solution should be imagined for handling such cases.

[ui] fix "Sync Camera with Image Selection"

---

meshroom/ui/reconstruction.py

This PR fixes an issue that occurred when dragging and dropping images from a folder into Meshroom's Image Gallery.
When dropping new images, the intrinsics were rebuilt asynchronously in a thread that was not attached to anything. The update of the intrinsics, performed in the main thead following a signal emitted in the detached thread, would block when there were already some existing intrinsics (and thus already some existing images in the gallery) because the garbage collector would destroy the thread in which the new intrinsics had been computed while the update was ongoing. It seems the issue did not appear when there was not any image in the gallery because the update of the intrinsics did not need to remove the previously existing ones before adding the new ones.
- This pull …

[ui] Drag&Drop: Use a pool of threads for asynchronous intrinsics computations

---

meshroom/ui/qml/ImageGallery/ImageGallery.qml

Selecting any filter in the Image Gallery changes the displayed content of the gallery according to the filter. Unselecting any filter automatically switches the displayed content back to the "input images" filter (which simply displays all the input images), but the "input images" button is never reselected, meaning that there can be a display corresponding to a filter without any filter being selected, as shown in the image below.
<div align="center"><img src="https://i.gyazo.com/9b7efcb7e0bb375003410f9a44c76573.png" height=300></div>
This PR prevents unselecting a filter without reselecting the one corresponding to the display. Since the "input images" is always the display that is reverted back to, unselecting any filter automatically selects its button:
<div align="center"><img …

[ImageGallery] Match the filter selection with the gallery's display

---

meshroom/ui/components/thumbnail.py
meshroom/ui/qml/ImageGallery/ImageDelegate.qml

In this PR we fix several bugs related to the thumbnail cache mechanism.
We fix a problem that can occur with the thumbnail cache when input images cannot be read: 
since each image delegate has a Timer that will send a new request every 5 seconds until a thumbnail can be loaded, in the case of images that cannot be read these requests will be sent endlessly.
The proposed fix is to stop the Timer after the 1st request, since it is the only one that is actually useful for preventing unwanted behaviour from the QML engine.
Another problem that we fixed is that when an image was loaded once, then modified for any reason and then reloaded later on, its corresponding thumbnail will not be updated.
The proposed fix is to remove a thumbnail if its corresponding image has been modified after the …

[ui] fix thumbnail cache bugs

---

meshroom/ui/qml/ImageGallery/ImageGallery.qml
meshroom/ui/qml/ImageGallery/IntrinsicDisplayDelegate.qml
meshroom/ui/reconstruction.py

This PR fixes a QML warning and a raised exception related to the intrinsics:
- The QML warning "Unable to assign QJSValue to QObject*", which was related to the wrong initialisation of the `attribute` variant in the intrinsics table.
- The exception that raised with "Failed to parse Viewpoint metadata: 'the JSON object must be str, bytes or bytearray, not Property'" whenever there was a switch between the different CameraInit groups after all the intrinsics had been cleared. The metadata value is now accessed if and only if it exists, ie. if it is a string instance and not a PySide property (the metadata value becomes a PySide property when the viewpoint attribute is deleted).

[ui] Intrinsics: Fix warnings and exceptions

---

meshroom/nodes/aliceVision/PanoramaPostProcessing.py
meshroom/nodes/aliceVision/PanoramaSeams.py
meshroom/pipelines/panoramaFisheyeHdr.mg
meshroom/pipelines/panoramaHdr.mg

Very large panoramas required to update the panorama seams node and replace image processing node with a specific node to handle large memory consumption

New nodes for large memory use in panoramas

---

meshroom/nodes/aliceVision/SfMTransform.py

Transformation parameter is available when auto_from_cameras_x_axis is selected in sfmTransform.
This way, the user can select which view is the center in the panorama.

[sfmtransform] Transformation parameter availability

---

bin/meshroom_batch
meshroom/core/graph.py
meshroom/pipelines/cameraTracking.mg
meshroom/pipelines/panoramaFisheyeHdr.mg
meshroom/pipelines/panoramaHdr.mg
meshroom/pipelines/photogrammetry.mg
meshroom/pipelines/photogrammetryAndCameraTracking.mg
meshroom/pipelines/photogrammetryDraft.mg
meshroom/ui/graph.py
meshroom/ui/reconstruction.py

Closes #1900.
This PR fixes an issue in `meshroom_batch` which was caused by the refactoring of hard-coded pipelines to .mg files. Specifically, this commit: 8fb0c778d12af5d3d51567407a6d38132e53d796 omitted the `Publish` node from the photogrammetry pipeline. This PR adds it back. Before this PR, if the `--output` argument was passed to `meshroom_batch`, it throws an error complaining from no Publish nodes as explained in the linked issue.

Fix missing Publish nodes in templates

---

meshroom/nodes/aliceVision/LdrToHdrCalibration.py
meshroom/nodes/aliceVision/LdrToHdrMerge.py
meshroom/nodes/aliceVision/LdrToHdrSampling.py
meshroom/nodes/aliceVision/PanoramaPostProcessing.py
meshroom/pipelines/panoramaFisheyeHdr.mg
meshroom/pipelines/panoramaHdr.mg

This PR updates the documentation strings of the `LdrToHdrSampling`, `LdrToHdrCalibration`, `LdrToHdrMerging` and `PanoramaPostProcessing` nodes so that they are both correct (in the case of the `LdrToHdrMerge` node) and displayed correctly. 
Prior to this PR, these nodes' documentation was displayed as
<div align="center"><img src="https://i.gyazo.com/c8f0c52a1e249858dd58aa608b3f8c99.png" width=300></div>
instead of 
<div align="center"><img src="https://i.gyazo.com/bdd2226418be2b09d54f2652bc54e7a6.png" width=300></div>
For the `LdrToHdrSampling` and `LdrToHdrCalibration` nodes, any references to Robertson have been removed from the description of the `calibrationMethod` attribute, as it is not an available value for it anymore.
Finally, the `PanoramaPostProcessing` nodes that are …

Fix the documentation related to Panorama nodes

---

meshroom/nodes/aliceVision/PanoramaWarping.py

Since [this PR](https://github.com/alicevision/AliceVision/pull/1244) was merged, the output images of the PanoramaWarping node are stored on disk as several tiles, and there is currently no system to support tiles in the 2D viewer.
Therefore, double-clicking on the PanoramaWarping node results in an empty 2D viewer.
This PR simply removes the image attributes from the node description, thus double-clicking the node won't have any effect.

[nodes] PanoramaWarping: remove obsolete image output attributes

---

meshroom/ui/qml/Viewer/Viewer2D.qml

This PR fixes an issue that occurs when displaying the "StructureFromMotion Statistics" and "StructureFromMotion Global Statistics" components more than once per session. The components would be correctly loaded upon their first display, but disabling them and redisplaying them would lead to empty graphs, as the SfMData would not be correctly reloaded.
The SfMData is now provided to the components every time they are to be displayed (instead of providing it only once the first time they were to be displayed, and then never again), and the components' source is explicitly unloaded when they are hidden again. The behaviour of the statistics components is now similar to the other components' (such as the FeatureViewer, for example).
The image on the left below shows the statistics graphs …

[Viewer] Load and unload the SfMStats components explicitly every time they are shown and hidden 

---

meshroom/ui/commands.py
meshroom/ui/graph.py
meshroom/ui/qml/main.qml
meshroom/ui/reconstruction.py

This PR modifies the behaviour of the "Clear Images" menu action as follows:
- It is now executed on the Python side instead of the QML side, which makes it more than 4x faster:
- For 500 PNG images, it used to take ~38s, it now takes less than 0.5s.
- For 1000 PNG images, it used to take ~2m39, it now takes 1s.
- "Clear Images" now only clears the images for the active group (meaning the active CameraInit node), instead of clearing all the images for all groups (all CameraInit nodes).
- When using "Clear Images", the "Undo" stack used to be filled with individual intrinsics and viewpoints images. Calling "Clear Images" when 500 images were in the gallery was thus requiring at least 500 calls to "Undo" to be fully reverted. It is now considered as a single action, meaning a single call to …

[ui] Improve "Clear Images" action's behaviour and performance

---

meshroom/core/attribute.py
meshroom/core/desc.py
meshroom/core/graph.py
meshroom/core/node.py
meshroom/ui/commands.py
meshroom/ui/graph.py
meshroom/ui/qml/GraphEditor/AttributeItemDelegate.qml
meshroom/ui/qml/GraphEditor/Node.qml
meshroom/ui/qml/GraphEditor/NodeEditor.qml
tests/test_templatesVersion.py

This PR adds support for internal attributes, which are attributes that exist for all nodes independently from their type.
Internal attributes are displayed in the "Notes" tab of the graph editor (also added in this PR) and can be set for each node individually and independently. 
Four internal attributes are added with this PR: comments/invalid comments (to write some comments regarding a node), label (to rename a node), and color (to change a node's color).
Regarding the "comments" internal attribute, an icon is added to the node's header if a comment has been set, and hovering over that icon displays a tooltip containing the comment.
Internal attributes will be written to the template files if and only if they have non-default values (so they need to have been set). If no internal …

Add internal attributes in "Notes" tab

---

meshroom/pipelines/panoramaFisheyeHdr.mg
meshroom/pipelines/panoramaHdr.mg

#1819 introduced a new node, `PanoramaPostProcessing`, that was added at the end of the Panorama templates to replace the `ImageProcessing` node. 
#1903 however added `Publish` nodes at the end of the Panorama templates with the pipelines using the `ImageProcessing` as a reference, which left us with templates that correctly used `PanoramaPostProcessing` instead of `ImageProcessing`, but expected the `Publish` node to be connected to the `ImageProcessing`'s output.
This PR correctly connects the `Publish` nodes to the `PanoramaPostProcessing` outputs.

[pipelines] Panorama: Fix inputs of the "Publish" nodes

---

meshroom/nodes/aliceVision/PanoramaCompositing.py

Add an option to manually set the number of pyramid levels in the laplacian compositing
Based on https://github.com/alicevision/AliceVision/pull/1369

[panorama] force pyramid levels count in compositing

---

meshroom/ui/qml/main.qml

A project needs to be saved in order to be submitted to the renderfarm. However, attempting to submit an unsaved project does not prompt any dialog in the UI, despite the exception that is thrown on the Python side.
This PR improves that behaviour by opening a warning dialog that lets the user know their project needs to be saved in order to be submitted.

[ui] Prompt a warning dialog when attempting to submit an unsaved project

---

meshroom/ui/commands.py

This PR fixes a bug introduced by #1897, which modified the way images were cleared. 
The viewpoints and intrinsics were correctly reset, but not followed by a request to update the graph. This meant that nodes' status was not updated (the cache for the CameraInit should be invalidated and propagated), and the filters in the Image Gallery were not all properly updated (in particular, the "Estimated Cameras" / "Non Estimated Cameras" were not reset.
A request to update the graph is now emitted after each attribute's reset.

[ui] Clear Images: Request a graph update after resetting the viewpoints and intrinsics

---

meshroom/ui/qml/Viewer/Viewer2D.qml

When double-clicking on a node with image output attributes, even though the image shown is not the view itself, the metadata used are the viewpoint's metadata, taken from the CameraInit's sfm data.
This can lead to problems, for example with the orientation metadata: if the viewpoint and the image displayed have a different orientation, the image will appear flipped and/or rotated.
However, whenever we use the FloatImage viewer, the displayed image's metadata are available (directly loaded from disk using the aliceVision::image module).
Therefore the purpose of this PR is to use in priority the metadata retrieved by the FloatImage viewer when it is available.

[ui] Viewer2D: fix displayed metadata

---

meshroom/nodes/aliceVision/KeyframeSelection.py

This PR is related to https://github.com/alicevision/AliceVision/pull/1343 and replaces #1765.
It removes the parameters that were previously used for the Keyframe Selection and replaces them with new ones, corresponding to the two newly added selection methods:
- The regular method, that samples frames regularly over time;
- The smart method, that scores all the frames based on their sharpness and optical flow, and selects the most relevant.

[nodes] KeyframeSelection: Rework the node and add parameters for new selection methods

---

meshroom/nodes/aliceVision/ImageProcessing.py

Add a parameter for the correction of chromatic aberrations in the LCP group but disable it. It will need to be re-enabled later on, when there will be a full support of the chromatic aberration correction.
This parameter is needed for the ImageProcessing binary on AliceVision's side to be properly executed.

[nodes] ImageProcessing: Add and hide the fringing correction in the LCP

---

meshroom/ui/qml/ImageGallery/ImageGallery.qml
meshroom/ui/reconstruction.py

This PR fixes an issue that appeared when switching between several temporary `CameraInit` nodes, which are used for example when enabling the "Visualize HDR Images" option: although the thumbnails in the Image Gallery were correctly updated, the 2D Viewer was not always updated with the newest selected item in the grid view, which caused a mismatch between what was shown in the Image Gallery and what was displayed in the 2D Viewer. 
There are two cases to switch between temporary `CameraInit` nodes: 
1.  By changing the active `CameraInit` group in the ImageGallery: changing the active group would not lead to any update of the 2D Viewer, while the thumbnails were always up-to-date. Indeed, if several `CameraInit` groups are available, and if the currently selected image in the grid view …

[ui] Correctly update the Viewer 2D when there are temporary CameraInit nodes

---

meshroom/nodes/aliceVision/Split360Images.py

In this PR, we reflect the changes made to the command-line of the software `aliceVision_split360Images` in its corresponding Meshroom node.
AliceVision PR: https://github.com/alicevision/AliceVision/pull/1378

[nodes] Split360Images: update attributes to software version 2.0

---

meshroom/nodes/aliceVision/StructureFromMotion.py
meshroom/ui/qml/ImageGallery/ImageDelegate.qml

This PR adds a "SfM: Define Initial Pair" menu in the Image Gallery, which allows the user to set the "Initial Pair A" and "Initial Pair B" parameters from the `StructureFromMotion` node with the currently selected image's view ID. 
The menu is only enabled if there is a `StructureFromMotion` node in the active group. 
<div align="center"><img src="https://i.gyazo.com/6d392b359b2c39b2da2fb63f5d530f70.png" width=250></div>
The description of the `initialPairA` and `initialPairB` parameters in the `StructureFromMotion` node is also updated with the list of accepted values for these parameters (filename, filepath, or view ID).

Image Gallery: Add a menu to set the StructureFromMotion initial pair from the gallery

---

meshroom/ui/qml/ImageGallery/ImageGallery.qml
meshroom/ui/qml/ImageGallery/IntrinsicDisplayDelegate.qml
meshroom/ui/reconstruction.py

When a temporary `CameraInit` node was created, its intrinsics (set to be identical to the currently active `CameraInit` node) were not parsed and the intrinsics table was not updated with them. This issue was not visible if there was a single `CameraInit` node in the graph, as its intrinsics were still displayed, making it seem like the intrinsics were those of the temporary `CameraInit` node.
However, when there were several `CameraInit` groups, switching from one group's temporary `CameraInit` node to another's would generate a QML error and cause the intrinsics table to be empty. 
This PR addresses this issue by correctly parsing the intrinsics when temporary `CameraInit` nodes are created, thus correctly filling the intrinsics table at all times.
It also handles an issue that was …

[ui] Image Gallery: Fix the display of the intrinsics table with temporary CameraInit nodes

---

meshroom/ui/qml/main.qml

This PR fixes an issue introduced by #1927, which aimed at displaying a warning pop-up whenever the user attempted to submit a project file that was not saved to the render farm. 
To do so, it relied on an already existing `canSubmit` variable, which itself depended on a `canStartComputation` variable that was not used anywhere else and was actually outdated.
In particular, the `canStartComputation` variable required to have more than one image for any computation to be allowed, and it was automatically set to false if there was any ongoing computation.  This was not compatible with what is expected of `canSubmit`, which should be set to true as soon as submitters are available and the project file is saved, independently from what is (or is not) being computed.
As a consequence, …

[ui] Fix conditions on which the prompt asking the user to save a project before submitting it to the render farm relies

---

meshroom/ui/qml/ImageGallery/ImageGallery.qml

This PR fixes the behaviour of the Image Gallery, which used to switch to read-only as soon as a node in the entire graph was being computed. This meant that no image could be dropped in the gallery if there was any ongoing computation, even if the nodes that were computed did not include or involve the active `CameraInit` node.
The computation status of the active `CameraInit` node is now taken into account when determining whether the Image Gallery should be read-only or not.

[ui] ImageGallery: Allow image drop if the active group is not computing

---

docs/source/conf.py
meshroom/ui/app.py
meshroom/ui/qml/AboutDialog.qml

This PR does the following:
- Update all the copyrights dates from 2022 to 2023;
- Add Meshroom's changelog to the "About" dialog, along with the licenses. The changelog model is concatenated with the licenses model for display purposes, but is retrieved separately.

Display the changelog in the "About" dialog and update copyrights

---

meshroom/core/__init__.py

`Version` objects were meant to be used only with numerical characters, separated by periods. Now that the version of Meshroom can also contain its status ("develop" when it is in develop mode), the `Version` class needs to be able to parse the status string (when it exists) as well as the version components.
This PR addresses this by handling the status as a separate string, which is returned in addition to the tuple of integers when the whole version string is parsed in the first place.
This prevents issues when opening files that have been saved with a version like "x.x.x-develop".

[core] Correctly parse status in version names when it exists

---

tests/test_templatesVersion.py

This PR adds a message when an assertion is raised because of compatibility issues in the test on templates' versions. 
If such a compatibility issue is found and the corresponding assertion is raised, a message is now displayed to indicate which template (with its path) and which node (with its node type) caused the issue.

[tests] TemplatesVersion: Add message when compatibility assertion is raised

---

RELEASING.md

This PR adds an example of the command to use to generate the release note.
```
./github-generate-release-note.py -o alicevision -r Meshroom -m "Meshroom MAJOR.MINOR.PATCH" --highlights major-feature --label-include bugfix,ci,scope:doc,scope:build -s updated-asc
```
generates a list of all the closed pull requests for the milestone MAJOR.MINOR.PATCH with:
- a "Main features" section (`highlights`) containing all the PRs tagged with the label `major-feature`;
- an "Other improvements" section that contains all the PRs that are not tagged with the labels used in `label-include`;
- a section (`label-include`) that includes all the PRs tagged with labels `bugfix`, `ci`, `scope:doc`, `scope:build`.
All the pull requests are sorted with the "least recently updated" setting.

[doc] RELEASING: Add example command to generate the release note

---

meshroom/core/stats.py

This PR fixes an issue that occured whenever a GPU was found and its name and total memory size were expected to be displayed in the "Statistics" tab: the memory size was correctly shown, but the name remained empty.
<div align="center">
</div>
This stemmed from the parsing of the XML tree that is obtained with the `nvidia-smi -q -x` command: the memory-related information was correctly parsed, but the name of the GPU was never retrieved. The name of the GPU is now retrieved and saved alongside the rest of the information, which automatically fixes the display in the "Statistics" tab:
<div align="center"><img src="https://i.gyazo.com/3c03fbf09d643b47a26e1f601a6f6aef.png" width=400 />
</div>

[core] Stats: Retrieve and set the GPU name if it is found

---

meshroom/nodes/aliceVision/KeyframeSelection.py
meshroom/ui/reconstruction.py

This PR is related to https://github.com/alicevision/AliceVision/pull/1406, and adds the support of `SfMData` files as inputs and outputs.
In particular:
- It adds two new output parameters, `outputSfMDataKeyframes` and `outputSfMDataFrames` which are `SfMData` files which respectively contain all the selected keyframes and all the input frames that were not selected as keyframes;
- It updates the description of the input `inputPaths` parameter to indicate the `SfMData` files are supported;
- It updates the label of the `sensorDbPath` parameter (trivial).

[nodes] KeyframeSelection: Add support for SfMData files as inputs and outputs

---

meshroom/nodes/aliceVision/TracksBuilding.py

Move tracks building out of incremental Sfm code for easier distribution of the following processes
A new application is created to generate tracks from matches
Exporter for tracks to json is added
See https://github.com/alicevision/AliceVision/pull/1418

add trackbuilder node

---

bin/meshroom_statistics
bin/meshroom_status
bin/meshroom_submit
meshroom/core/stats.py

This PR fixes errors on different Meshroom scripts that thus could not be run, or crashed when some specific arguments were set. More specifically, it targets:
- `meshroom_submit`: 
- The input argument containing the path of the project file to submit was never used to call the core.graph's "submit" method;
- Instead, two invalid arguments were used;
- `meshroom_status`: The `--toNode` option caused errors when retrieving the list of nodes up to `toNode`;
- `meshroom_statistics`: 
- The script was still performing Python 2-imports;
- It relied on a method in the core.stats module that was broken: when reading the `statistics` file, the computer and process statistics where initialized to empty dictionaries instead of `ComputerStatistics` and `ProcStatistics` objects, meaning the file was …

[bin] Fix all the scripts that had errors

---

meshroom/nodes/aliceVision/StructureFromMotion.py
meshroom/pipelines/cameraTracking.mg
meshroom/pipelines/photogrammetry.mg
meshroom/pipelines/photogrammetryAndCameraTracking.mg
meshroom/pipelines/photogrammetryDraft.mg

Add two new input parameters to the `StructureFromMotion` node:
- `nbFirstUnstableCameras` which sets the number of cameras for which a bundle adjustment is performed every time a camera is added;
- `maxImagesPerGroup` which sets the maximum number of cameras that can be added before the bundle adjustment has to be performed again.
By default, the bundle adjustment will be performed every time one of the first 30 cameras is added, as computations are not too expensive while there are few cameras. Past that number, the bundle adjustment will only be performed when up to 30 cameras have been added.
The node's version and the templates using the `StructureFromMotion` node are updated accordingly.
Related AliceVision pull request: https://github.com/alicevision/AliceVision/pull/1413

StructureFromMotion: Add new inputs parameters

---

meshroom/ui/qml/Viewer/FeaturesInfoOverlay.qml
meshroom/ui/qml/Viewer/FeaturesViewer.qml
meshroom/ui/qml/Viewer/Viewer2D.qml
meshroom/ui/reconstruction.py

In [this QtAliceVision PR](https://github.com/alicevision/QtAliceVision/pull/31) several changes has been made to the QML types defined in the plugin.
The goal of this PR is to reflect these changes in Meshroom's QML code to keep it up to date.

[ui] Reflect changes made in QtAliceVision refactorize PR

---

meshroom/ui/qml/ImageGallery/ImageGallery.qml
meshroom/ui/qml/WorkspaceView.qml

This PR fixes an issue that occurred when all the images from the Gallery were manually removed one by one (either with the "Del" key or the "Remove" option): the list of viewpoints was emptied as expected (but never reset) but the list of intrinsics was never modified (neither emptied nor reset). This could cause errors later on, when re-filling the Gallery with new images that were unrelated to the remaining intrinsics.
When the list of viewpoints is now emptied, both the list of viewpoints and the list of intrinsics are reset, in the same fashion as when "Clear Images" is called.

[ui] ImageGallery: Reset viewpoints and intrinsics when removing all the images

---

meshroom/nodes/aliceVision/ApplyCalibration.py
meshroom/nodes/aliceVision/CameraInit.py
meshroom/nodes/aliceVision/DistortionCalibration.py
meshroom/nodes/aliceVision/ExportDistortion.py
meshroom/pipelines/cameraTracking.mg
meshroom/pipelines/distortionCalibration.mg
meshroom/pipelines/photogrammetryAndCameraTracking.mg

The goal of this PR is to reflect the changes made in [this PR](https://github.com/alicevision/AliceVision/pull/1415) in Meshroom.

[nodes] Distortion calibration

---

meshroom/nodes/aliceVision/SfMTransform.py

Update SfMTransform node to support ground level alignment, introduced in this PR: https://github.com/alicevision/AliceVision/pull/1438

[nodes] SfMTransform: add alignGround option

---

meshroom/nodes/aliceVision/LdrToHdrMerge.py
meshroom/nodes/aliceVision/Publish.py
meshroom/pipelines/cameraTracking.mg
meshroom/pipelines/hdrFusion.mg
meshroom/pipelines/panoramaFisheyeHdr.mg
meshroom/pipelines/panoramaHdr.mg
meshroom/pipelines/photogrammetry.mg
meshroom/pipelines/photogrammetryAndCameraTracking.mg
meshroom/pipelines/photogrammetryDraft.mg

This PR adds a new template to perform a stand-alone HDR fusion, which used to be only available in the HDR panorama templates.
As the `LdrToHdrMerge` node's only output was an SfMData file, its output folder is now exposed so that results of the fusion are available. 
The `Publish` node's support for inputs has also been extended to folders: if a folder is provided in the list of inputs, its content will be recursively published to the output folder.

Add a template for the HDR fusion

---

meshroom/nodes/aliceVision/CameraInit.py

When opening SfM scenes before version 1.2.4, a `KeyError` was raised because we were trying to read intrinsic properties that did not exist.

[nodes] CameraInit: access intrinsic properties safely

---

meshroom/nodes/blender/ScenePreview.py
meshroom/nodes/blender/scripts/preview.py

The `ScenePreview` node was using `viewIds` to name its output images, which breaks sequence order and makes it difficult to compare with the initial images.
In this PR we change the output naming process and use the base images names instead.

[nodes] ScenePreview: use base image name for naming output

---

meshroom/nodes/aliceVision/KeyframeSelection.py

Related AliceVision pull request: https://github.com/alicevision/AliceVision/pull/1457
This PR sets a dynamic size for the `KeyframeSelection` node, thus allowing the nodes that follow to be chunked if applicable.
As its number of outputs can rarely be precisely known before it is actually computed, we set the size with what we know to be the maximum number of keyframes.
There are 3 cases to determine what the maximum number of keyframes will be:
1. The number of input frames is known (the input is not a video) and the smart selection is enabled: the size is the minimum between the number of input frames and the maximum number of output frames for the smart selection.
2. The number of input frames is known and the regular selection is enabled:
a. If the maximum number of output frames for …

[nodes] KeyframeSelection: Set a dynamic size for the node

---

meshroom/nodes/aliceVision/KeyframeSelection.py
meshroom/pipelines/cameraTracking.mg

Related AliceVision pull request: https://github.com/alicevision/AliceVision/pull/1454
This PR adds the support of the `none` value for the `outputExtension` parameter in the `KeyframeSelection` node, and sets it as the default value. Setting `outputExtension` to `none` disables the export of the selected keyframes, meaning that only the SfMData files will be written on disk as outputs of the `KeyframeSelection` node. 
The description of the parameter is updated accordingly and mentions that it should not be used with video inputs, as this would lead to no output at all.

KeyframeSelection: Add new parameter value to disable the export of keyframes

---

meshroom/core/node.py
meshroom/nodes/aliceVision/DepthMap.py
meshroom/ui/qml/Viewer/Viewer2D.qml

This PR splits from #1925 and keeps the dynamic update of the list of viewable outputs in the 2D Viewer: instead of displaying at all times the list of a node's viewable outputs independently from their current status (enabled or disabled), the 2D Viewer should only show the enabled outputs, and adding/removing them as soon as they get enabled/disabled.
Hiding (or showing) the connections of output attributes that get disabled (or enabled) will remain handled in #1925.

Viewer2D: Dynamically update the list of viewable outputs

---

meshroom/nodes/blender/scripts/preview.py

Fix failure in `ScenePreview` node when `useBackground` is checked but one background image is not found.
This situation occurs in the "Photogrammetry and Camera Tracking" pipeline as photogrammetry poses are filtered out at the end of the process.

[blender] preview: handle background image not found

---

meshroom/ui/qml/ImageGallery/ImageGallery.qml

This PR adds the name of the currently active `CameraInit` group in the Image Gallery, right below the group selection area.
Additionally, it adds the name of the previous/next `CameraInit` group in the tooltip of the buttons used to switch between groups.
<div align="center"><img src="https://github.com/alicevision/Meshroom/assets/11963329/5b7f6c69-1ba3-4fba-af91-2e6459e043e4" /></div>

[ui] ImageGallery: Display the name of the active `CameraInit` group

---

meshroom/nodes/aliceVision/LightingCalibration.py
meshroom/nodes/aliceVision/SphereDetection.py

Related AliceVision pull request: https://github.com/alicevision/AliceVision/pull/1452
This PR fixes the label and description for the output folder of the `SphereDetection` node, as well as some parameters' description in the `LightingCalibration` node.

[nodes] StereoPhotometry: Fix some labels and descriptions

---

meshroom/core/node.py
meshroom/ui/qml/GraphEditor/Node.qml

This PR adds an icon on nodes with outputs that can be visualised with the 2D Viewer (following #1776). 
When a node has been computed, if it has at least one viewable output, an icon appears next to its name with a tooltip indicating that it can be loaded by double-clicking it.
<div align="center"><img src="https://github.com/alicevision/Meshroom/assets/11963329/6819c506-ecb1-4c50-9c0d-c53a7c22f089" /></div>

[ui] Display an icon on nodes that have viewable outputs

---

meshroom/nodes/aliceVision/CameraInit.py
meshroom/nodes/aliceVision/FeatureExtraction.py
meshroom/nodes/aliceVision/PanoramaWarping.py
meshroom/pipelines/cameraTracking.mg
meshroom/pipelines/panoramaFisheyeHdr.mg
meshroom/pipelines/panoramaHdr.mg
meshroom/pipelines/photogrammetry.mg
meshroom/pipelines/photogrammetryAndCameraTracking.mg
meshroom/pipelines/photogrammetryDraft.mg

Enable color space selection at stitching level.

Stitching color space

---

meshroom/nodes/blender/scripts/preview.py

In the `preview` script used to render views with Blender we must clear the background image (when it exists) between each frame, otherwise we can quickly occupy the entire RAM.

[blender] preview: clear loaded images to avoid memory leak

---

meshroom/core/node.py
meshroom/ui/qml/GraphEditor/Node.qml
meshroom/ui/qml/Viewer/Viewer2D.qml

This PR follows #2047 and extends the display of the icon for viewable outputs to outputs that are viewable in the 3D Viewer. Any `File` output that has an extension supported by the 3D Viewer can be loaded.
The distinction between outputs that can be loaded in the 2D Viewer and those that can be loaded in the 3D Viewer is made, and the tooltip that appears when hovering over the icon reflects that. The tooltip message has also been simplified. 
The case where a node has both 2D and 3D outputs is handled with a corresponding tooltip message, although there is currently no such node.

[ui] Display an icon on nodes that have viewable 3D outputs

---

meshroom/submitters/simpleFarmSubmitter.py

Bug fix for simpleFarm submission:
use node name instead of node type when naming tasks as they are guaranteed to be unique

Fix submit through simpleFarm

---

meshroom/ui/components/thumbnail.py

Avoid crashes and unwanted behaviours when thumbnailDir cannot be created (for example if user does not have write permissions in target directory).

[ui] thumbnails: fallback if thumbnailDir could not be created

---

meshroom/core/graph.py
meshroom/core/node.py
meshroom/ui/qml/GraphEditor/CompatibilityManager.qml

This PR relates to #2038, which invalidates all the nodes in all the existing graphs by changing the way UIDs are computed. Without it, all nodes will be invalidated silently, without letting the user know why or giving them the chance to still use their computed data before doing the upgrade.
With this PR, UID conflicts - differences between the UIDs that are saved in a project file and the UIDs that are computed in the graph once all the links have been resolved - are detected and handled like any other compatibility issue, meaning they can be solved with the Compatibility Manager.
When a project file is loaded, the graph is built normally (compatibility issues on nodes' versions and descriptions are raised as usual) and then evaluated to check for UID conflicts. If a node presents a …

[core] Detect and handle UID conflicts when loading a graph

---

meshroom/core/node.py

This PR adds the node's type in the tuple of each attribute that is used to compute its UID. The goal is to prevent getting the same UID for two nodes which are of different types but have an identical list of attributes.
:warning: **Warning**: This will invalidate all the existing cached computations as all the nodes' UIDs will change.

[core] Include the node's type in the UID computation

---

meshroom/nodes/blender/scripts/preview.py

Use the `CYCLES` render engine in the `ScenePreview` node script to support farm rendering.

[blender] preview: use cycles render engine

---

INSTALL.md

This PR adds a link to download the sphere detection model that is needed for the automatic sphere detection in the `SphereDetection` node, and how to set the `ALICEVISION_SPHERE_DETECTION_MODEL` environment variable.

[doc] INSTALL: Add info about the sphere detection model

---

meshroom/nodes/blender/scripts/preview.py

Modify the Material graph used for the `wireframe` rendering mode in the `ScenePreview` node to support occlusions, which makes the output more readable.

[blender] preview: occlusions in wireframe shading

---

meshroom/nodes/blender/scripts/preview.py

A regression on the `ScenePreview` node was introduced in [this PR](https://github.com/alicevision/Meshroom/pull/2064): the `line_art` shading method was not working properly with Cycles.
In this PR we fix this regression by replacing the former method with a new one that provides more flexibility for potential future refinements.
For that we simply use the Freestyle renderer: https://docs.blender.org/manual/fr/dev/render/freestyle/introduction.html

[blender] preview: use Freestyle for line art shading

---

meshroom/__init__.py

The `ALICEVISION_SPHERE_DETECTION` variable needs to be declared and set using the installation path. If it is not, no node using it will be able to work unless the users set this environment variable on their own.
This relates to #2067 and should have been a part of it.

Set `ALICEVISION_SPHERE_DETECTION_MODEL` variable during the initialisation

---

meshroom/__init__.py

Following the release of Meshroom 2023.2.0, this PR sets the current version to 2023.3.0 with the "develop" status.

Start Development 2023.3

---

meshroom/nodes/aliceVision/FeatureExtraction.py
meshroom/nodes/aliceVision/ImageSegmentation.py

Create a node which calls AliceVision semantic segmentation

semantic image segmentation

---

meshroom/nodes/aliceVision/SfMSplitReconstructed.py

Take an input sfmdata
- Create 1 sfmdata with reconstructed views only (and landmarks)
- Create 1 sfmdata with non reconstructed views only (without landmarks)
TCSR-305
see https://github.com/alicevision/AliceVision/pull/1409

Node to split reconstructed and not reconstructed cameras

---

meshroom/nodes/aliceVision/CameraInit.py
meshroom/nodes/blender/scripts/preview.py

Full support of pixel aspect ratio in all the tools used for camera tracking.
related AliceVision PR: https://github.com/alicevision/AliceVision/pull/1448
This PR is **NOT** about supporting non-trivial pixel aspect ratio in the UI.
The SfMData file version was increased to `1.2.5` and this change impacts the `viewpoints.sfm` file generated when importing images in Meshroom.

Support pixel aspect ratio (no UI)

---

meshroom/core/attribute.py
meshroom/core/desc.py

Add brackets option for GroupAttribute command line value. Brackets option is a two chars string or None. 
If specified the GroupAttribute command line value is encapsulated between the two chars. (e.g. '[]')

[core] Add brackets option for GroupAttribute

---

meshroom/nodes/aliceVision/LdrToHdrCalibration.py
meshroom/nodes/aliceVision/LdrToHdrMerge.py
meshroom/nodes/aliceVision/LdrToHdrSampling.py

This PR relates to https://github.com/alicevision/AliceVision/pull/1484.
The detection of the number of brackets used to only work in a case where there was a single dataset / a single camera intrinsics. If two datasets with the same number of brackets were provided, the detection was failing because we expected the exposure levels to be uniform across all the images.
If more than one dataset is provided, there is no guarantee that the exposure groups will be identical although the number of brackets is the same.
The inputs are however sorted, and the shutter speeds are expected to be decreasing, meaning that a shutter speed N superior to a shutter speed N-1 indicates a new group. In the same manner, ISO or aperture values that change from one input to the next one indicate a new group. …

[nodes] HDR Fusion: Correctly detect the number of brackets when there are several intrinsics

---

INSTALL.md
meshroom/__init__.py

The `ALICEVISION_SEMANTIC_SEGMENTATION_MODEL` variable needs to be declared and set using the installation path. If it is not, no node using it will be able to work unless the users set this environment variable on their own.
Additionally, the `INSTALL.md` file is completed with a link to download the semantic segmentation model and how to set the `ALICEVISION_SEMANTIC_SEGMENTATION_MODEL` variable. 
This PR relates to https://github.com/alicevision/AliceVision/pull/1481.

Set `ALICEVISION_SEMANTIC_SEGMENTATION_MODEL` variable during the initialisation

---

meshroom/ui/qml/Utils/SortFilterDelegateModel.qml
meshroom/ui/qml/Viewer/Viewer2D.qml

Following #1882, this PR fixes an issue related to type coercion in `SortFilterDelegateModel` which prevents the `find` method from ever matching with anything, as well as a warning caused by the deprecated use of implictly declared slots.

QML: Fix minor coercion error and warning

---

meshroom/ui/qml/Viewer/FloatImage.qml
meshroom/ui/qml/Viewer/PanoramaViewer.qml
meshroom/ui/qml/Viewer/SequencePlayer.qml
meshroom/ui/qml/Viewer/Viewer2D.qml
meshroom/ui/qml/WorkspaceView.qml
meshroom/ui/reconstruction.py

This PR introduces a new UI element in the 2D viewer: an image sequence player.
This player allows user to navigate smoothly between viewpoints and provides playback functionnalities.
For performance and interactivity purposes, this feature relies on a newly introduces image sequence cache in QtAliceVision: https://github.com/alicevision/QtAliceVision/pull/36
- `SequencePlayer` component with :
- slider to scroll through viewpoints
- play/pause functionnalities
- cached regions indicator in background
- new `pickedViewId` concept in `reconstruction` subordinated to `selectedViewId` to allow only partial UI updates
- bug fix in the float image viewer: avoid black image when a new image is being loaded

[ui] 2D viewer: image sequence player

---

meshroom/nodes/aliceVision/LdrToHdrCalibration.py
meshroom/nodes/aliceVision/LdrToHdrMerge.py
meshroom/nodes/aliceVision/LdrToHdrSampling.py

Bracket size selection is now tolerant to at most two spurious image in the images list.
rule : (Bracket size * countGroupsWithThisSize) >= totalImages - 2

tolerant bracket size selection

---

meshroom/nodes/aliceVision/LdrToHdrCalibration.py
meshroom/nodes/aliceVision/LdrToHdrMerge.py
meshroom/nodes/aliceVision/LdrToHdrSampling.py

This PR updates the command line for the HDR Fusion nodes (`LdrToHdrSampling`, `LdrToHdrCalibration` and `LdrToHdrMerge`) with or without the `nbBrackets` parameters depending on whether the number of brackets is detected automatically or provided by the user. 
If the user provides it, it is added to the command line as `--nbBrackets x`. If the detection is automatic, the `nbBrackets` parameter is not part of the command line, and the brackets will be automatically detected on the AliceVision side. 
The goal is to be able to distinguish, from the AliceVision side, cases where the number of brackets is determined automatically or set by the user; up until now, Meshroom always sent a fixed number of brackets (either automatically detected or provided by the user), without any way to …

[nodes] HDR Fusion: Do not send `nbBrackets` parameter to the command line when the bracket detection is automatic

---

meshroom/nodes/aliceVision/LdrToHdrCalibration.py
meshroom/nodes/aliceVision/LdrToHdrMerge.py
meshroom/nodes/aliceVision/LdrToHdrSampling.py

This PR removes brackets limits on Meshroom when managing outliers. The limit of two outliers at most does not exist anymore.
Related to https://github.com/alicevision/AliceVision/pull/1491.

[nodes] Remove limits on outliers for brackets detection

---

meshroom/nodes/aliceVision/LdrToHdrCalibration.py
meshroom/nodes/aliceVision/LdrToHdrMerge.py
meshroom/nodes/aliceVision/LdrToHdrSampling.py

If there are several groups with different bracket numbers but identical counts (e.g. 3 groups with 7 brackets, and 3 groups with 3 brackets), select the groups with the largest bracket number (e.g. groups with 7 brackets instead of 3).
This reflects changes introduced with https://github.com/alicevision/AliceVision/pull/1493.

[nodes] HDR Fusion: Select group with largest bracket number in case of equality

---

CMakeLists.txt
COPYING.md
INSTALL.md
docker/Dockerfile_centos
docker/Dockerfile_ubuntu
docker/Dockerfile_ubuntu_deps

Following https://github.com/alicevision/QtAliceVision/pull/38 which merged QmlAlembic into QtAliceVision, this PR removes all the references to QmlAlembic from the documentation and the Dockerfiles.
QtAliceVision is now referred to as the only existing plugin for Meshroom, and is the only one to be built in Meshroom's Dockerfiles.

[build] Remove references to QmlAlembic in the build process

---

meshroom/core/node.py
meshroom/ui/qml/GraphEditor/ChunksListView.qml
meshroom/ui/qml/GraphEditor/CompatibilityManager.qml
meshroom/ui/qml/GraphEditor/NodeEditor.qml

This PR introduces some minor UI changes in the Graph Editor:
- If a node has a custom label (set through the "Notes" tab), the default label of the node is now displayed next to the custom one in the Node Editor. The goal is to be able to quickly identify the type of nodes that have custom labels, as these labels may not be explicit. The default label is always composed of the node's type and a unique index (e.g. `CameraInit2`).
- When compatibility issues are raised on nodes, their default label is displayed in the Compatibility Manager instead of their type. For graphs that have multiple nodes of the same type, this allows to clearly identify the compatibility issue that's been raised for each node. The width of the "Node" column has also been increased to ensure that there is no …

[ui] GraphEditor: Minor UI changes

---

bin/meshroom_batch

Modify `meshroom_batch` command line to support pipelines with multiple init nodes, such as the `cameraTracking` pipeline.
The `--input` and `--inputRecursive` arguments syntax used to be `input1 input2 input3 ...` (each input being either an image, a folder or a SfMData file), now it is `NodeAName:input1;input2;input3 NodeBName:input4`.
For example with a `cameraTracking` pipeline where the shot to track is in a folder named `/path/to/my/shot` and the distortion grid is just one image named `distogrid.exr` the command line would be:
```
meshroom_batch -i CameraInit_1:/path/to/my/shot CameraInit_2:distogrid.exr -p cameraTracking
```
When the pipeline used has only one init node (most common use case) there is no need to specify the `NodeName:` part:
```
meshroom_batch -i …
```

[bin] meshroom_batch: support multiple init nodes

---

meshroom/nodes/aliceVision/LdrToHdrCalibration.py
meshroom/nodes/aliceVision/LdrToHdrMerge.py
meshroom/nodes/aliceVision/LdrToHdrSampling.py

Prior to this PR, only the shutter speed was compared between two images to determine whether they belonged to the same group. The fnumber and ISO were assumed to be fixed within a group, which is not always true, and differs from what is done on the AliceVision's side.
We now also check that the ISO is either constant or increasing and that the fnumber is either constant or decreasing to determine that an image belongs to the current exposure group.

[nodes] HDR Fusion: Fix bracket detection

---

meshroom/nodes/aliceVision/LdrToHdrCalibration.py
meshroom/nodes/aliceVision/LdrToHdrMerge.py
meshroom/nodes/aliceVision/LdrToHdrSampling.py

The bracket detection performed in Meshroom used to differ from the one performed in AliceVision.
The metadata that were retrieved to perform the exposure comparisons were not the same, and where AliceVision was actually computing an exposure value, Meshroom was just performing a comparison between the shutter speed, fnumber and ISO values, which resulted in less accurate groups.
This PR updates the HDR Fusion nodes so that they use the same bracket detection as AliceVision.
The `getExposure()` static method that is added to the `LdrToHdrSampling`, `LdrToHdrCalibration` and `LdrToHdrMerge` node is the pythonic version of the `getExposure()` method from the View class in AliceVision.

[nodes] HDR Fusion: Use the same bracket detection as in AliceVision

---

meshroom/ui/qml/WorkspaceView.qml

When dragging the border between 3D Viewer and 2D Viewer:
- previous behavior: the Image Gallery is resized instead of the 2D Viewer
- new behavior: the 2D Viewer is resized

[UI] fix resize of horizontal splitview

---

meshroom/core/attribute.py
meshroom/core/desc.py
meshroom/nodes/aliceVision/LdrToHdrCalibration.py
meshroom/nodes/aliceVision/LdrToHdrMerge.py
meshroom/nodes/aliceVision/LdrToHdrSampling.py
meshroom/ui/qml/GraphEditor/AttributeItemDelegate.qml
meshroom/ui/qml/MaterialIcons/MaterialIcons.qml

This PR introduces two new parameters in the description of Int, Float and String attributes:
- `validValue`, which is true if the value of the attribute is not erroneous (i.e. valid for the type of the attribute but invalid in the
context of that specific attribute) and false otherwise. This holds a different significance than the "validateValue()" method, which only checks if the attribute's value is correct with respect to its type. For example, we could want an IntParam that flags any value that is not even: an odd integer value would successfully go through the "validateValue()" method, but would then be flagged as an invalid value at the attribute's level.
- `errorMessage`, an attribute-specific string that contains a message explaining why the attribute's `validValue` parameter …

AttributeEditor: Flag attributes with invalid values

---

meshroom/nodes/aliceVision/ImageProcessing.py

Add LCP related parameters in imageProcessing node interface.

Manage LCP in imageProcessing

---

meshroom/pipelines/cameraTracking.mg
meshroom/pipelines/photogrammetryAndCameraTracking.mg

This PR adds default colors for the nodes from the "Camera Tracking" and "Photogrammetry and Camera Tracking" templates so that the different processing blocks of these rather complex pipelines can be identified more easily.
"Camera Tracking" template:
"Photogrammetry and Camera Tracking" template:

[pipelines] Add colors for CameraTracking and Photog+CamTrack templates

---

meshroom/pipelines/cameraTracking.mg
meshroom/pipelines/photogrammetryAndCameraTracking.mg

Add `ImageSegmentation` node to tracking pipelines: `Camera Tracking` and `Photogrammetry and Camera Tracking`.
By default only one class is used for segmentation: `person`.

[pipelines] add ImageSegmentation node to tracking pipelines

---

meshroom/nodes/aliceVision/ImageSegmentation.py
meshroom/nodes/aliceVision/MeshMasking.py
meshroom/nodes/aliceVision/PrepareDenseScene.py
meshroom/pipelines/cameraTracking.mg
meshroom/pipelines/photogrammetryAndCameraTracking.mg

This PR reflects the changes made in alicevision/AliceVision#1517 to handle other file extensions than "png" for masks and to invert mask values in the `ImageSegmentation` node. 
Additionally, the "Camera Tracking" and "Camera Tracking and Photogrammetry" templates are updated as follows:
- The `maskInvert` attribute of the `ImageSegmentation` node is enabled;
- The `maskInvert` attribute of the `FeatureExtraction` node is disabled;
- For the "Camera Tracking" pipeline, the (inverted) output of the `ImageSegmentation` node is connected to the `PrepareDenseScene`'s input.

[nodes] Masking: Handle file extensions for masks and mask inversion for `ImageSegmentation`

---

meshroom/nodes/aliceVision/KeyframeSelection.py

The `minBlockSize` parameter allows to set the minimum number of frames that will be processed by a single thread spawned by the Keyframe Selection process. 
It prevents spawning threads that will create their own `FeedProvider` objects to process a single frame.

[nodes] KeyframeSelection: Add `minBlockSize` param for multi-threading

---

meshroom/core/attribute.py
meshroom/core/desc.py
meshroom/nodes/aliceVision/KeyframeSelection.py

This PR follows #2141 and extends the `validValue` and `errorMessage` parameters to "Choice" attributes. It additionally ensures that the `validValueChanged` signal is emitted whenever the attribute's value is updated so it can be re-evaluated, even if `validValue` itself has not changed.
The `outputExtension` attribute from the `KeyframeSelection` node, which determines whether the selected keyframes should be written on disk (and the file extension they should be written on disk with), gets its `validValue` and `errorMessage` parameters to get flagged whenever a video input is part of the list of inputs while `outputExtension` is set to "none". Indeed, if it is set to "none" for video inputs, no frame will ever be written on disk and, as a consequence, no SfMData file will be written …

KeyframeSelection: Flag `outputExtension` attribute when it is set to "none" for video inputs

---

meshroom/nodes/blender/ScenePreview.py
meshroom/nodes/blender/scripts/preview.py
meshroom/pipelines/cameraTracking.mg
meshroom/pipelines/photogrammetryAndCameraTracking.mg

Use segmentation masks in ScenePreview node: this will avoid rendering geometry on top of moving characters, cars, etc.

[blender] apply masks to scene preview

---

meshroom/ui/qml/Viewer/FloatImage.qml
meshroom/ui/qml/Viewer/SequencePlayer.qml
meshroom/ui/qml/Viewer/Viewer2D.qml

Based on this PR: https://github.com/alicevision/QtAliceVision/pull/39
Set the `targetSize` property of the float image viewer to adapt the image resolution to the zoom level.

[ui] FloatImageViewer: adapt resolution to zoom

---

meshroom/pipelines/panoramaFisheyeHdr.mg

Disable export of pyramid for panorama fisheye in the default pipeline

Disable pyramid export for fisheye

---

meshroom/nodes/aliceVision/StructureFromMotion.py

If `logIntermediateSteps` is enabled, the current state of the scene will be dumped as an SfMData file every 3 resections. Before this option was added, the intermediate steps were always dumped.
This relates to alicevision/AliceVision#1377, which has disabled the dumping of intermediate steps by default and added a new parameter to control it.

[nodes] StructureFromMotion: Add new `logIntermediateSteps` parameter

---

bin/meshroom_batch

This PR fixes an issue that occurred when executing `meshroom_batch` on Windows. To determine the relationships between the provided input paths and the initialisation nodes, the strings given for the `-i` argument is parsed based on ":", which is the expected separator between the node instance and the input path(s).
On Linux, this works flawlessly since no path can contain a ":". On Windows however, ":" is a basic character in paths, which led to issues: since the input path was unexpectedly split, it was not correctly recognised, and the `CameraInit` node was never set with that input path. As a consequence, the process was stopping with a `Nothing to compute for node CameraInit_1.` error.
To prevent this, we now check that the first element after the split of the provided argument …

[bin] `meshroom_batch`: Fix input parsing for Windows

---

meshroom/nodes/aliceVision/RelativePoseEstimating.py
meshroom/nodes/aliceVision/SfmBootstraping.py

SFM bootstraping ;
Incremental SFM needs to be bootstraped with an initial set of views.
This app choose the initial pair as currently done in ReconstructionEngine_sequential but as a standalone application.
Once the pair is chosen, it generate the associated point cloud and the SfmData as required for the rest of the pipeline.
See https://github.com/alicevision/AliceVision/pull/1432

sfm bootstraping

---

meshroom/nodes/aliceVision/PanoramaPostProcessing.py
meshroom/pipelines/panoramaFisheyeHdr.mg
meshroom/pipelines/panoramaHdr.mg

This PR adds two new input String parameters to the `PanoramaPostProcessing` node to determine the name of the generated outputs. These attributes include:
- the name of the generated output panorama;
- the name of the generated output panorama preview.
These two attributes are not added to the command line, as their only purpose is to be used to set the names of the outputs at will. The base folder for these outputs remains the node's cache, only the name of the outputs themselves can be updated.
The `downscaledPanoramaLevels` output attribute is also updated following alicevision/AliceVision#1542, since the name of the downscaled levels is now a concatenation of the generated panorama's name, "_level_" and the size of the level.
As a consequence, the version of the …

[nodes] PanoramaPostProcessing: Add attributes to change the outputs' names

---

meshroom/ui/qml/ImageGallery/ImageGallery.qml

This PR fixes a minor UI issue in the Image Gallery related to the visualization of HDR images.
When all the images in the gallery are cleared using the "Clear Images" or "Clear All Images" menu action while the "Visualize HDR images" option is turned on, the gallery was correctly emptied and the viewer correctly reset but the button remained turned on even though there was nothing left to show.
As it was turned on (although with a "0" count), the gallery remained in read-only mode and no more image could be dropped until the button was manually clicked to be turned off. Even after that, it remained clickable instead of being disabled.
<div align="center"><img src="https://github.com/alicevision/Meshroom/assets/11963329/27660c2a-a1da-4f2f-ace0-f2ef78b533bd" height=300 /></div>
This PR …

[ui] ImageGallery: Disable "Visualize HDR" button after clearing images

---

meshroom/ui/reconstruction.py

When parsing the input SfM JSON file of a project, there might be some instances where the `poses` key, unlike the `views` and `intrinsics` keys, does not exist. If that is the case, an unhandled exception is raised while connections are being made, which then causes issues for the lifetime of the Meshroom instance.
This PR checks that the `poses` key exists before trying to access it, which prevents raising unhandled exceptions while the active project is being set up.

[ui] Check for the existence of the `poses` key in SfM JSON files before accessing it

---

meshroom/nodes/aliceVision/StructureFromMotion.py

Enable automatic alignment at the of the structure from motion result.
"Determines scene orientation from the cameras' X axis, determines north and scale from GPS information if available, and defines ground level from the point cloud."
See https://github.com/alicevision/AliceVision/pull/1546

[nodes] StructureFromMotion: Automatic alignment of the 3D reconstruction

---

meshroom/ui/qml/Viewer/SequencePlayer.qml

Default value for FPS is now 24
Update icon to use "repeat" (instead of "replay")
When launching "play" on the last frame, restart from the beginning instead of doing nothing.

[ui] SequencePlayer: minor adjustments (fps, icon, play)

---

meshroom/nodes/aliceVision/CheckerboardCalibration.py
meshroom/nodes/aliceVision/IntrinsicsCalibration.py

Add a node for the new `aliceVision_intrinsicsCalibration` software introduced in https://github.com/alicevision/AliceVision/pull/1524.

[nodes] new IntrinsicsCalibration node

---

meshroom/ui/commands.py
meshroom/ui/graph.py
meshroom/ui/qml/ImageGallery/ImageDelegate.qml
meshroom/ui/qml/ImageGallery/ImageGallery.qml
meshroom/ui/qml/WorkspaceView.qml
meshroom/ui/qml/main.qml

In addition to the existing "Remove" menu action in the Image Gallery that deletes the currently selected image, this PR adds a "Remove All Images" menu action that performs the same action as "Clear Images" from the "File" menu.
The `Del` key was used as a shortcut to remove the currently selected image when the Image Gallery has the focus, `Shift+Del` can now also be used to remove all the images at once.
<div align=center><img src="https://github.com/alicevision/Meshroom/assets/11963329/082aa304-5aba-4f0f-b891-29a5e3bffd41" height=400 /></div>

[ui] ImageGallery: Add "Remove All Images" menu to clear all images

---

bin/meshroom_batch

Up to this commit, `meshroom_batch` only supported absolute input and output paths: using relative ones led to a failure during the execution of the `CameraInit` node.
Now, if relative paths are provided by the user, they are automatically converted to absolute ones, thus ensuring that everything will run smoothly.

[bin] `meshroom_batch`: Add support for relative input and output paths

---

meshroom/nodes/aliceVision/ImageProcessing.py

Add a choice param in the imageProcessing node to force the color space of the input images. Default value set to AUTO. In that case, the input color space is extracted from the metadata as it is implemented in the current version.

Input color space setting

---

meshroom/ui/qml/ImageGallery/ImageGallery.qml
meshroom/ui/reconstruction.py

Prior to this PR, when a `CameraInit` node was added to or removed from the list of `CameraInit` nodes, the active `CameraInit` was always reset to the first one in the list, independently from its previous value. This meant that whenever a `CameraInit` node was added to or removed from the graph while the Image Gallery was displaying a `CameraInit` node that was not the first one in the list, the Image Gallery was automatically updated to display the first `CameraInit` node without any intervention from the user, as shown below:
<div align="center"><img src="https://github.com/alicevision/Meshroom/assets/11963329/d6f9da48-33cc-41ed-8e0b-e122ce4f79ac" height=500 /></div>
This pull request changes that behaviour by only modifying the active `CameraInit` node if no `CameraInit` node has …

[ui] Preserve last `CameraInit` index when updating the CameraInits list

---

meshroom/ui/qml/main.qml

Prior to this PR and following #2208, any file whose extension is `.json`,  `.sfm` or `.abc` could be loaded in the 3D viewer. Double-clicking on a node that had an output with one of these extensions, even if it was not a 3D output, led to the node being loaded in the 3D viewer.
For example, double-clicking the `CameraInit` node, which has `.sfm` outputs but no 3D output, resulted in it being added to the list of entries of the Inspector3D. 
This PR ensures that no node will be loaded in the 3D viewer upon being double-clicked unless it has a 3D output, which is indicated by an icon next to the node's name in the Graph Editor. Only `.abc` outputs are considered to be valid 3D outputs.
Any `.json`, `.sfm` and `.abc` can still be dropped in the 3D viewer, and the `SfmDataLoader` will load …

[ui] Don't load a node's output in the 3DViewer if it has no 3D output

---

meshroom/pipelines/photogrammetryAndCameraTracking.mg

This PR disables the automatic alignment in the `StructureFromMotion` nodes for the "Photogrammetry and Camera Tracking" pipeline.

[pipelines] PhotogAndCamTrack: Disable automatic alignment in SfM

---

meshroom/pipelines/photogrammetryDraft.mg

This PR adds a `PrepareDenseScene` node to the Photogrammetry Draft template, and connects it to the final `Texturing` node. Without it, no texture file is created during the texturing step. 
This fixes https://github.com/alicevision/Meshroom/issues/2136.

[pipelines] Photogrammetry Draft: Add a `PrepareDenseScene` node to the template

---

meshroom/ui/qml/Controls/ExpandableGroup.qml
meshroom/ui/qml/Controls/qmldir
meshroom/ui/qml/MaterialIcons/MaterialIcons.qml
meshroom/ui/qml/Viewer3D/Inspector3D.qml
meshroom/ui/qml/Viewer3D/MediaLibrary.qml
meshroom/ui/qml/Viewer3D/MediaLoader.qml
meshroom/ui/qml/Viewer3D/MediaLoaderEntity.qml
meshroom/ui/qml/Viewer3D/SfmDataLoader.qml
meshroom/ui/qml/Viewer3D/Viewer3DSettings.qml

This PR adds a slider in the 3D Viewer to filter cameras in the 3D view based on their resection IDs. The slider appears when the "Display Cameras Based On Resection IDs" button is selected, and if at least one of the objects currently loaded in the 3D Viewer has cameras with identifiable resection IDs. 
Any camera whose resection ID is higher than the one set through the slider will be hidden the 3D view, which allows to visualize the order in which the cameras have been added, and the groups in which they have been added.
<div align="center"><img src="https://github.com/alicevision/Meshroom/assets/11963329/eeb9a4bd-d2ee-4258-96bb-0d670f5c2c04" width=400 /></div>
Additionally, the "DISPLAY" and "CAMERA" groups become tabs that can be expanded and hidden. By default, they are hidden. …

[Viewer3D] Add slider to display cameras based on their resection IDs

---

meshroom/ui/qml/Viewer3D/MediaLoader.qml
meshroom/ui/qml/Viewer3D/SfmDataLoader.qml

This PR connects the `selectedViewId` property from the `Reconstruction` object to the `selectedViewId` property of the `SfmDataLoader` object: any change of the currently selected view ID, either by selecting another image in the Image Gallery or by clicking on a camera in the 3D Viewer, will be propagated to QtAliceVision.
This relates to https://github.com/alicevision/QtAliceVision/pull/52.

[Viewer3D] Connect any change of the selected view ID to the SfmDataLoader

---

meshroom/core/node.py

When stopping the local computations of the graph with the "Stop" button, the status of the chunks that have already been updated to `SUCCESS` is preserved, and the submitted chunks are reset. However, when stopping the computation of a specific node with the "Stop Computation" option, all the chunks are updated to `STOPPED` independently from their previous status.
This PR ensures that chunks of a node that are already in the `SUCCESS` state will not be updated when stopping the computations, and those that are `SUBMITTED` but not `RUNNING` will be reset to `NONE`; only the `RUNNING` chunk will be updated to `STOPPED`.

[core] Only update the running chunk to `STOPPED` when stopping computations

---

meshroom/__init__.py

Following the release of Meshroom 2023.3.0, this PR sets the current version to 2023.4.0 with the "develop" status.

Start Development 2024.1.0

---

meshroom/nodes/aliceVision/ImageSegmentation.py

Add an option in image segmentation to use GPU (or CPU if disabled).
related to https://github.com/alicevision/AliceVision/pull/1618

ImageSegmentation: add an option to choose between cpu and gpu

---

meshroom/pipelines/nodalCameraTracking.mg
meshroom/pipelines/nodalCameraTrackingWithoutCalibration.mg

This PR adds the distortion calibration to the Nodal Camera Tracking template, and creates a new "Nodal Camera Tracking Without Calibration" template.
Depends on https://github.com/alicevision/AliceVision/pull/1624.

[pipelines] Nodal Camera Tracking: Add a new template with the calibration of the distortion 

---

meshroom/ui/qml/Viewer/FloatImage.qml
meshroom/ui/qml/Viewer/Viewer2D.qml

When an image cannot be loaded in the 2D Viewer, for example when visualizing the output of a node while an image whose viewpoint does not correspond to any output image is selected in the Image Gallery, the viewer remained in a loading state. The only way to get out of it was to try and load another image successfully. 
This PR stops displaying a loading icon as soon as it has been detected that the image could not be loaded, basing itself on the FloatImageViewer's global status, which is updated in QtAliceVision: the viewer is cleared and the error message corresponding to the global status is displayed (in the case described above: "Missing File").
<div align="center"><img src="https://github.com/alicevision/Meshroom/assets/11963329/5aeb57a5-f307-4d39-ad25-01febb8c0565" width=600 …

[Viewer] Display error labels when an image cannot be loaded

---

meshroom/nodes/blender/scripts/preview.py

This PR rescales images that are rendered by the `ScenePreview` node if the input images have a pixel aspect ratio that is different from 1. This prevents getting visualisation images that are squished and that have lost all the pixel aspect ratio-related information.

[nodes] Blender: Rescale rendered images based on their pixel aspect ratio

---

meshroom/nodes/aliceVision/ExportDistortion.py

Add an option to ExportDistortion to undistort input lens grids and save the result as an EXR image
See https://github.com/alicevision/AliceVision/pull/1630

[nodes] ExportDistortion: Option to export lens grid undistorted

---

meshroom/ui/components/thumbnail.py
meshroom/ui/graph.py
meshroom/ui/reconstruction.py

Fix the error about threadpool deletion when Meshroom exits: this fixes the "OSError: [Errno 9] Bad file descriptor" that occurs when Python 3.9 is used.

Correctly delete thread pools when exiting Meshroom with Python 3.9

---

meshroom/ui/qml/Viewer/PanoramaViewer.qml
meshroom/ui/qml/Viewer/SequencePlayer.qml
meshroom/ui/qml/Viewer/Viewer2D.qml

This PR fixes the following issues:

[Viewer] Viewer: Fix various issues with the 2D Viewer

---

meshroom/nodes/aliceVision/LdrToHdrCalibration.py
meshroom/pipelines/hdrFusion.mg
meshroom/pipelines/panoramaFisheyeHdr.mg
meshroom/pipelines/panoramaHdr.mg
meshroom/ui/qml/Viewer/CameraResponseGraph.qml
meshroom/ui/qml/Viewer/Viewer2D.qml

Following the changes introduced by https://github.com/alicevision/AliceVision/pull/1484, the response file is not always named "response.csv" anymore, but is instead named "response_{INTRINSIC_ID}.csv".
This PR updates the corresponding output attribute in the `LdrToHdrCalibration` node by adding the intrinsic ID, which is never fixed beforehand, to the string of the response file's path. 
Since the intrinsic ID must be resolved, the way the CSV file is provided to the Camera Response Graph widget is also modified: instead of providing the `LdrToHdrCalibration` node to the Camera Response Graph and retrieving the path of the response file within the widget, the path is retrieved and resolved before activating the Camera Response Graph, and is then passed as a parameter to the component.

Use the correct response file to display the graph of the Camera Response Function

---

meshroom/nodes/aliceVision/ImageSegmentation.py
meshroom/pipelines/cameraTracking.mg
meshroom/pipelines/cameraTrackingWithoutCalibration.mg
meshroom/pipelines/nodalCameraTracking.mg
meshroom/pipelines/nodalCameraTrackingWithoutCalibration.mg
meshroom/pipelines/photogrammetryAndCameraTracking.mg

This PR add an option avoiding the replacement of the input filename with the viewID in the imageSegmentation node.
Related AliceVision pull request: https://github.com/alicevision/AliceVision/pull/1636

Add option to keep input filename in imageSegmentation

---

meshroom/pipelines/cameraTracking.mg
meshroom/pipelines/cameraTrackingWithoutCalibration.mg
meshroom/pipelines/nodalCameraTracking.mg
meshroom/pipelines/nodalCameraTrackingWithoutCalibration.mg
meshroom/pipelines/photogrammetryAndCameraTracking.mg

Following #2288, this PR enables the `Keep Filename` option for all the `ImageSegmentation` nodes that are in the templates. The targeted templates are:
- Camera Tracking
- Camera Tracking without Calibration
- Nodal Camera Tracking
- Nodal Camera Tracking without Calibration
- Photogrammetry & Camera Tracking

[pipelines] Enable `Keep Filename` for all `ImageSegmentation` nodes in templates

---

meshroom/pipelines/panoramaFisheyeHdr.mg
meshroom/pipelines/panoramaHdr.mg

This PR updates the "Panorama HDR" and "Panorama Fisheye HDR" templates to set the "Minimal 2D Motion" parameter, which was disabled up to now, to 5.

[pipelines] Panorama: Enable "Minimal 2D Motion" for `FeatureMatching`

---

meshroom/pipelines/panoramaFisheyeHdr.mg

This PR moves the `PanoramaInit` and `FeatureExtraction`, which could run in parallel, so that they are run sequentially.
The `FeatureExtraction` node will thus be able to use the fisheye circle information obtained with `PanoramaInit` to only extract features within that circle.
This relates to https://github.com/alicevision/AliceVision/pull/1645.

[pipelines] PanoramaFisheyeHdr: Run `FeatureExtraction` after `PanoramaInit`

---

meshroom/pipelines/photogrammetryAndCameraTracking.mg

This PR updates the matching method from the `ImageMatchingMultiSfm` node (matching between the photog and the keyframes) to `Exhaustive`.

[pipelines] PhotogAndCamTrack: Update matching mode to "Exhaustive"

---

meshroom/nodes/aliceVision/ImageSegmentation.py

Up until #2288, the `ImageSegmentation` node's outputs were named based on the original image's view ID. They can now also be named directly after the input image.
When loading an `ImageSegmentation` node in the 2D Viewer, it should thus have the correct name of the generated masks.

[nodes] ImageSegmentation: Support loading masks in 2D Viewer if they are named after the input images

---

meshroom/core/attribute.py
meshroom/core/node.py
meshroom/core/utils.py
meshroom/nodes/aliceVision/FeatureExtraction.py
meshroom/nodes/aliceVision/ImageProcessing.py
meshroom/nodes/aliceVision/LdrToHdrCalibration.py
meshroom/nodes/aliceVision/LdrToHdrMerge.py
meshroom/nodes/aliceVision/LdrToHdrSampling.py
meshroom/nodes/aliceVision/PanoramaPostProcessing.py
meshroom/nodes/aliceVision/PanoramaWarping.py
meshroom/nodes/aliceVision/Texturing.py
tests/test_nodeCommandLineFormatting.py

This PR adds native support of the following camera color spaces through an updated "ocio.config" file:
ARRI:
Linear ARRI Wide Gamut_3
ARRI LogC3 (EI800)
Linear ARRI Wide Gamut_4
ARRI LogC4
Black Magic:
Linear BMD Wide Gamut Gen5
BMD Film Wide Gamut Gen5
Canon:
CanonLog2 Cinema Gamut D55
CanonLog3 Cinema Gamut D55
Linear Cinema Gamut D55
Panasonic:
Linear V Gamut
V Log V Gamut
RED:
Linear RED Wide Gamut RGB
Log3G10 RED Wide Gamut RGB
Sony:
Linear Venice S Gamut3 Cine
S Log3 Venice S Gamut3 Cine

Add camera color spaces

---

meshroom/core/graph.py
meshroom/ui/commands.py

The behaviour regarding `ListAttributes` was different depending on whether an edge or a node was removed:
- if an edge was removed, the `ListAttribute` that was the destination of that edge had its corresponding element completely removed;
- if a node was removed, the `ListAttribute` that was the destination of one of the node's edges had its corresponding element reset, but not removed.
With this behaviour, a user had different UIDs depending on whether a single edge or the whole node had been removed where the UID should always be identical.
This PR ensures that removing a node has the same effect on a connected node as removing an edge: it thus removes completely an element connected to a `ListAttribute` when the node is removed.
When collecting the outgoing edges, we now check …

Update `ListAttributes` identically when removing edges or nodes

---

meshroom/nodes/aliceVision/CameraInit.py

Display an error on the param if the value is invalid.

[nodes] CameraInit: check allowedCameraModels validity

---

meshroom/nodes/aliceVision/LidarMeshing.py

See https://github.com/alicevision/AliceVision/pull/1668

First node for Lidar Meshing

---

meshroom/pipelines/nodalCameraTracking.mg
meshroom/pipelines/nodalCameraTrackingWithoutCalibration.mg

Enable the "Apply Masks" option in the `ScenePreview` node for the Nodal Camera Tracking templates.

[pipelines] NodalTracking: Apply masks in `ScenePreview`

---

meshroom/ui/qml/main.qml

Added the option to display multiple meshes in the 3D viewport by adding  '3D' in the 'semantic' attribute field.
Keeps the original Meshroom logic of only displaying the first 3D object.

Added semantic logic to display multiple 3d objects

---

meshroom/nodes/aliceVision/KeyframeSelection.py

This PR updates the default value for the `minNbOutFrames` parameter of the KeyframeSelection node from 10 to 40.
All the templates that include a KeyframeSelection node use its default value for the minimum number of output keyframes. They will thus be automatically updated with the latest default value.

[nodes] KeyframeSelection: Update default minimum number of keyframes

---

meshroom/core/attribute.py
meshroom/ui/qml/GraphEditor/AttributeEditor.qml
meshroom/ui/qml/GraphEditor/AttributeItemDelegate.qml
meshroom/ui/qml/GraphEditor/AttributePin.qml
meshroom/ui/qml/GraphEditor/GraphEditor.qml
meshroom/ui/qml/GraphEditor/Node.qml

This PR effectively hides `File` attributes that are disabled. If these attributes have connections, the edges representing connections are hidden but preserved. 
- When the edges are hidden, if one of the connected attributes is still enabled, its pin becomes empty as if it was not connected to anything. If the disabled attribute is re-enabled and the connection has not been broken (if the enabled attribute on the other side of the edge has not been reconnected to another attribute, for example), the edge re-appears:
<div align="center"><img src="https://i.gyazo.com/c85dda91a99ac4390bffcac0ca4cf34a.gif" width=500></div>
- If the connection has been broken, then the attribute will re-appear as unconnected, as the edge has been removed:
<div align="center"><img …

Hide disabled File attributes and their connections

---

meshroom/ui/qml/Viewer/Viewer2D.qml

When opening an empty pipeline while the lens distortion viewer was enabled, we ended up in a state where the distortion viewer remained enabled and could not be disabled anymore as its button was greyed out.

[Viewer] fix lens distortion viewer status when switching between projects

---

meshroom/nodes/aliceVision/FeatureMatching.py

This PR updates the default value for the `maxIteration` parameter of the FeatureMatching node from 2048 to 50000. It additionally increases its range of valid values from 20000 to 100000. This parameter now matches the range and default value of the `localizerEstimatorMaxIterations` parameter from the StructureFromMotion node (#2341).

[nodes] FeatureMatching: Update default value for the maximum number of Ransac iterations

---

meshroom/core/attribute.py

Dynamic Param with onAttributeChanged behavior should not be applied if CompatibilityNode.
If it is a CompatibilityNode, we should only get the value of the attribute to create fully all the attributes instead of throwing an error.
Related to this [PR](https://github.com/alicevision/Meshroom/pull/2350)

[core] BugFix : Upgrade of Dynamic Choice Param fixed

---

meshroom/ui/qml/Viewer3D/MediaLibrary.qml
meshroom/ui/qml/main.qml

Bounding boxes can be used in nodes, not only Meshing. It only needs to have an attribute with useBoundingBox name.

[ui] Bounding Box are usable in other nodes, not only Meshing

---

meshroom/ui/qml/GraphEditor/GraphEditor.qml
meshroom/ui/qml/main.qml

Cut option on nodes available in Graph Editor. Shortcut CTRL+X also added for cut option.

[ui] Cut option available in GraphEditor

---

meshroom/core/graph.py
meshroom/core/node.py

While copying/pasting nodes internal attribute's values are now copied.

[core] Set internal attributes when copy/pasting nodes

---

meshroom/ui/qml/Viewer/SequencePlayer.qml

With the current UI, it is possible to use the "previous frame" or "next frame" buttons of the Sequence Player to select negative frame numbers or frame numbers that are larger than the actual number of frames in the sequence. 
Selecting an invalid frame number has no functional impact on the Sequence Player (it is not allowed on QtAliceVision's side) but it is still a glitch from a user standpoint. 
When typing in a negative frame number, said number is immediately replaced by "0" (as it should). However, when typing in a frame number that is larger than the number of frames, no such check is performed.
We would like to disable the "previous frame" buttons when the selected frame ID is 0, since it makes no sense to go lower than that; conversely, we would like to disable the "next frame" …

SequencePlayer: Forbid "selecting" an invalid frame number

---

meshroom/ui/qml/Viewer3D/TransformGizmo.qml

Implemented this feature, one can now adjust the bounding-box by clicking on an moving the points which are in the center of the surfaces.
I implemented two different entities, one for surfaces that are located in the direction of the axis, and one for the other surfaces. I did it, as it seemed to be a simple way to tackle the different behaviour of these surfaces when I wanted to move them. There is maybe a better way to do this.

Viewer3D: Adjust bounding-box by moving faces

---

meshroom/ui/qml/GraphEditor/AttributeItemDelegate.qml

Internal Custom Color Picker disabled when node is locked.

[GraphEditor] Internal Custom Color Picker disabled when node is locked

---

meshroom/ui/qml/Viewer/Viewer2D.qml

Fix when dropping external image on the Viewer, we don't want to see the feature points so we disabled them and the button.

[ui] Prevent Feature Points to display on external images

---

meshroom/ui/qml/GraphEditor/Node.qml

As we would like maybe to have color for categories of nodes, it is better if we don't hide those colors while selecting nodes. We still have the border but the header keeps its baseColor.

[ui] Selected node header set to base color

---

meshroom/ui/qml/GraphEditor/AttributeItemDelegate.qml

Right click on text element in AttributeEditor open Copy/Paste menu
- Able to paste nodeContent in text element

[ui] Right click on text element in AttributeEditor open Copy/Paste menu

---

meshroom/ui/qml/Viewer3D/Inspector3D.qml

Fix BoundingBox visibility icon because of mapping name. Before it was not shown.

[ui] Fix BoundingBox visibility icon because of mapping name

---

meshroom/nodes/aliceVision/NodalSfM.py
meshroom/nodes/aliceVision/RelativePoseEstimating.py
meshroom/nodes/aliceVision/SfmBootstraping.py
meshroom/pipelines/nodalCameraTracking.mg
meshroom/pipelines/nodalCameraTrackingWithoutCalibration.mg

Remove non needed features in multiple nodes 
Associated to https://github.com/alicevision/AliceVision/pull/1716

Add track coordinates

---

meshroom/multiview.py
meshroom/ui/app.py

Project, import and import recursive in meshroom command are now absolute paths.
Prevent from having some files gone while reopening the scene not from the same folder.

[ui] Conversion of relative paths to absolute ones

---

meshroom/core/graph.py
meshroom/ui/qml/main.qml
meshroom/ui/reconstruction.py

As sometimes a different instance of the file could be opened and have been modified since the last opening of the file, it is great to have a check and a warning if the file has been again saved somewhere else. You then have the possibility to overwrite, reload or do nothing.

[core] Compare last saved date before saving to prevent overwrite

---

meshroom/ui/qml/Viewer3D/DefaultCameraController.qml

When zooming in the 3D Viewer, we get stuck when we come the camera position and the viewpoint are too close.
This fix solves this problem by not allowing us those two points to get too close.
Solved with @almarouk and @Just-Kiel
The zoom and dezoom depends on the distance between camera and center position, if this distance is too low, the translation we apply to zoom/dezoom won't have any impact in the worst case as we are limited by float representation (and that's why we are stuck), or would be very low in the other case (and we'll need more user actions to have a visible dezoom).
There are two possibilities for the camera position to be too close to the center.
1/ We forbid too big zoom, as it means the distance between camera and center would be too low and we'll have no translation …

Fix 3D Viewer zooming problem

---

meshroom/nodes/aliceVision/ImageProcessing.py

In ImageProcessing node the attribute Keep Image Filename was not used. Now for the outputs that are based on VIEW_ID if the attribute is true then VIEW_ID is change to FILENAME.

[nodes] ImageProcessing : use keepImageFilename attribute

---

meshroom/nodes/aliceVision/ExportAnimatedCamera.py
meshroom/nodes/aliceVision/ImageSegmentation.py
meshroom/nodes/blender/ScenePreview.py
meshroom/ui/components/filepath.py
meshroom/ui/qml/Viewer/Viewer2D.qml
meshroom/ui/reconstruction.py

Update undistorted image paths according on ExportAnimatedCamera node if exists. It is useful for the overlay for the camera active in Viewer 3D.

[ui] Use ExportAnimatedCamera output for image overlay in Viewer3D

---

meshroom/nodes/aliceVision/ExportAnimatedCamera.py
meshroom/ui/reconstruction.py

ExportAnimatedCamera output changed before from folder to image expression needs to be folder for Scene Preview use. So now we have a new output to see the images.

[nodes/ui] Fix ExportAnimatedCamera outputs for ScenePreview use

---

meshroom/core/attribute.py
meshroom/core/desc.py
meshroom/core/node.py
meshroom/core/taskManager.py
meshroom/ui/qml/GraphEditor/GraphEditor.qml
meshroom/ui/qml/GraphEditor/Node.qml
meshroom/ui/qml/GraphEditor/NodeEditor.qml
meshroom/ui/qml/Viewer/Viewer2D.qml
tests/test_compatibility.py
tests/test_multiviewPipeline.py

Node without computation implemented with creation of InputNode class for easy description of Node.
Also changes for UI :
- Hide buttons in menu for Compute, Submit...
- Different header color to see the difference
- Tabs depending on chunks hidden
- Output Attributes in Viewer2D doesn't include "Image gallery" when displayedNode is not computable

New InputNode for nodes without computation and support for all param types in output (and no more limited to File type)

---

meshroom/ui/reconstruction.py

When graph is in dirty topology, we do not want to update the last SfM node in the graph.

Prevent updates of the latest SfM node when the graph's topology is dirty

---

meshroom/core/node.py
meshroom/ui/qml/GraphEditor/NodeEditor.qml

Improvement of computation information in node editor header
[X] update computation time every 2.5 seconds in header
[X] computation time when error occurs 
[X] chunk computed counter in node editor header
The previous label text logic is moved to the nodeChanged signal because the logic is overwritten by the timer when setting the text time. 
I don't know if 2.5 seconds is the best choice, feel free to give other refresh timing ideas.

[ui] node time computation and chunks count in node editor header

---

meshroom/ui/qml/GraphEditor/AttributeItemDelegate.qml

Large Multiline Component added for string attributes. If the semantic includes "large" then the height is bigger than for normal one.

[ui] Add "large" option to multiline string param

---

meshroom/core/attribute.py
meshroom/core/desc.py
meshroom/core/graph.py
meshroom/core/node.py
meshroom/ui/commands.py
meshroom/ui/components/filepath.py
meshroom/ui/graph.py
meshroom/ui/reconstruction.py
tests/test_nodeCommandLineFormatting.py

- [ui] commands: When we undo a node upgrade we enforce uidConflict=True as there was a uid conflict before
- [ui] filepath: retrieve the Viewpoint param value only once
- [core] node: set internal attributes from the constructor
- [core] node: do not ask the node to upgrade internalAttributes
- [core] node: more explicit log
- [core] node: set the attribute value from the constructor
- [core] attribute: new initValue, independant from the resetToDefaultValue

Fix compatibility upgrade issue

---

meshroom/core/__init__.py
meshroom/core/attribute.py
meshroom/core/desc.py
meshroom/core/graph.py
meshroom/core/node.py
meshroom/core/taskManager.py
meshroom/ui/graph.py

When an output attribute's default value is set to None, it is treated as dynamic. This means that its value will be determined at runtime by the node. As a result, this output value is not saved within the project to prevent invalidating the scene during graph computation. Instead, the output values of these dynamic attributes are stored in the node's cache folder.

[core] New dynamic output attributes

---

meshroom/ui/qml/Controls/TextFileViewer.qml
meshroom/ui/qml/GraphEditor/NodeEditor.qml
meshroom/ui/qml/GraphEditor/NodeStatistics.qml
meshroom/ui/qml/Utils/format.js

When getting times such as 359.5, the previous version of `getTimeStr` was returning "5m60s" instead of "6m0s" because the number of minutes was first computed, and the remaining seconds were rounded up and used as such. In some cases, rounding up those remaining seconds may lead to a full minute, which should be handled.
After minutes have been computed, we now check that the rounded up remainder does not correspond to a full minute before moving to the seconds.

[Utils] `getTimeStr`: Round up the number of minutes correctly

---

meshroom/__init__.py
meshroom/core/attribute.py
meshroom/core/node.py
meshroom/ui/components/filepath.py
meshroom/ui/qml/GraphEditor/Node.qml
meshroom/ui/qml/GraphEditor/NodeEditor.qml
meshroom/ui/qml/Viewer/SequencePlayer.qml
meshroom/ui/qml/Viewer/Viewer2D.qml
requirements.txt

- Image sequence is detected because the semantic of the output is defined as "sequence" in the description of the node
- SequencePlayer is enabled when double-clicked on the node
- Need to set the path for the image sequence is : `/path/to/define/<FRAMEID>.extension`
- Unsync of Viewers and SequencePlayer when displayed output is sequence output

[core/ui] Load image sequence from node's output in SequencePlayer

---

meshroom/core/graph.py
meshroom/ui/reconstruction.py

This PR adds a `viewpoint` property to the `Graph` object, containing the viewpoint attribute corresponding to the image that is currently selected in the Image Gallery.
This property is updated every time the selected viewpoint changes, and can thus be accessed from any object that has access to the `Graph` object itself (e.g. from inside a node, with `node.graph.viewpoint`).

Provide access to the current frame from the graph

---

meshroom/ui/graph.py

This PR fixes an issue introduced in df70f992563070a07ae60238b43470fb0d0dcc5d, which reduced the calls to `graph.update()` when setting the graph. 
Connecting the chunks was initially done after a call to `graph.update()`, but as the calls to the entire update have been removed when opening up a project, the chunks are never connected then, meaning the progress bar remains invisible until an explicit call to `graph.update()` is done.
Instead of updating the whole graph when it is set up for the first time, we rather explicitly connect the chunks.

[ui] Graph: Connect all chunks when setting a graph for the first time

---

meshroom/core/graph.py
meshroom/core/node.py

If the edges of a node to submit include an `InputNode` (which cannot be computed), then that `InputNode` should be excluded from the list of edges to process as if it had already been computed.
This allows to submit any type of graph involving `InputNode` to the farm.

[core] Exclude edges from `InputNode` nodes in `dfsToProcess`

---

meshroom/__init__.py
meshroom/ui/app.py
meshroom/ui/components/scriptEditor.py
meshroom/ui/qml/GraphEditor/ScriptEditor.qml
meshroom/ui/qml/GraphEditor/qmldir
meshroom/ui/qml/main.qml

This PR adds a new QML component to the GraphEditor tab which allows to easily write and execute Python code within Meshroom. Python scripts can be exported from or imported in the script editor, and the history of executed scripts is saved.
The ScriptEditor's input zone is set by default with a minimal script that lists the nodes that are part of the current graph, thus showing an example on how to access Meshroom elements in Python.

Add a Python ScriptEditor in the GraphEditor tab

---

bin/meshroom_batch
bin/meshroom_compute
bin/meshroom_submit
meshroom/core/__init__.py
meshroom/ui/app.py
tests/test_multiviewPipeline.py
tests/test_nodeCommandLineFormatting.py
tests/test_templatesVersion.py

Avoid plugins load at meshroom.core import by replacing direct loading of nodes, submitters and pipelines in meshroom.core __init__.py with functions and call them appropriately in app and bin.
One function created per type, nodes, submitters and pipelines and one global function calling all of them.

Remove plugin loading from core __init__

---

meshroom/core/desc.py

If a node uses a ChoiceParam with values that are not list, we throw an error with an explicit message.

[core] Values of ChoiceParam should be a list, Error message added for initialisation

---

meshroom/nodes/aliceVision/SphereDetection.py

This PR updates the maximum value for the `sphereRadius` parameter of the `SphereDetection` node from 1000 to 10000.

[nodes] SphereDetection: Increase max value for `sphereRadius`

---

bin/meshroom_compute
meshroom/core/node.py
meshroom/ui/graph.py
meshroom/ui/qml/GraphEditor/AttributeItemDelegate.qml

Some fixes for dynamic output attributes

---

meshroom/ui/qml/Viewer/Viewer2D.qml

To prevent reset of index in Image Gallery, we need to move the reset of current frame for the Sequence Player.

[Viewer] Current frame for Sequence should not be set during changes of Image Gallery

---

meshroom/ui/qml/main.qml

If a project is not saved but you still want to process part of the graph, it is great to know all the selected nodes, to then be able to compute only them.

[ui] Fix local computation of subgraphs for unsaved projects

---

meshroom/ui/reconstruction.py

Prevent from putting the index of Camera Init group in the Image Gallery to 1 if we only add or remove an external Camera Init.

[ui] Fix Camera Init Group Index should stay the same at adding or removing CameraInit events

---

meshroom/ui/qml/Viewer/Viewer2D.qml

Fix of bug when closing a node the index of ImageGallery is reset. Comes from the building of sequence.

[Viewer2D] Only reset index of currentFrame if the currentFrame is after max of frameRange

---

meshroom/ui/reconstruction.py

setSFM was changed to rely on sfmData nodes but it is not working.
And setCameraInitNode should be triggered only if the node is different from the current one.

[ui] setSfm only depends on nodes with category "sfm" and CameraInit should be set only if it is different from the current one

---

meshroom/ui/qml/GraphEditor/AttributeItemDelegate.qml

This PR fixes an issue related to the component display for push button attributes.
The value of a `PushButtonParam` being always `None`, it is necessary to check that the type of the component is not `PushButtonParam` before comparing its value to `undefined`. 
Otherwise, any `PushButtonParam` will always be represented by a "notComputed" component, making the `PushButtonParam` unusable.

[GraphEditor] AttributeItemDelegate: Return valid component for `PushButton`

---

meshroom/ui/qml/WorkspaceView.qml
meshroom/ui/qml/main.qml
meshroom/ui/reconstruction.py

As it was not the case, we add the behavior to extend the Recent Projects variable with the projects dropped within Meshroom.
To do wo, we had to implement a boolean as a return from handleFilesByUrl to know if the loading was a success or not.

[ui] Add project to recent projects when dropping a file

---

meshroom/core/attribute.py

The attributes' descriptions already have a `type` property which is set with `self.__class__.__name__`. Instead of performing the same call directly within the attributes, the `type` property of the description is used.
In case a description would not have a standard type (i.e. anything that may differ from the class name), this information will be propagated at the attribute level instead of being lost.

[core] Attribute: Directly access description's type in `getType()`

---

meshroom/ui/qml/Viewer/FloatImage.qml
meshroom/ui/qml/Viewer/Viewer2D.qml

This PR udpates the "error" value from QtAliceVision's `EStatus` enum following the changes introduced in https://github.com/alicevision/QtAliceVision/pull/74.

[Viewer] Update error values for QtAV's `EStatus` enum

---

bin/meshroom_batch
meshroom/core/__init__.py
meshroom/ui/app.py

This PR changes the order of initialization of the `core` plugins both in the main app and `meshroom_batch`.
- For the main app, the pipelines are now initialized prior to the parsing of the command line to ensure that the names of all the available templates can be provided to the "help" message. The nodes and submitters remain initialized at the same point.
- For `meshroom_batch`, the pipelines are also initialized prior to the parsing of the command line (for the same reasons), the nodes are initialized at the same point, and the submitters are initialized if and only if the `--submit` argument has been provided.

Initialize `core` plugins at different moments

---

meshroom/ui/qml/GraphEditor/AttributeItemDelegate.qml

The model for the values of a `ChoiceParam` attribute is now based on the attribute's list of available values instead of its description's list of available values.
This allows to edit dynamically the values for a non-exclusive `ChoiceParam` and have the UI immediately reflect these edits.

[GraphEditor] Base `ChoiceParam` model on attribute instead of description

---

meshroom/core/node.py

If a node's description contains invalid operations in its `onNodeCreated` method, exceptions are thrown without being caught and cause Meshroom to crash.
This PR fixes this issue by safely trying optional calls to the node's descriptor, and handling any encountered exception.

[core] Catch exception for calls to optional descriptor method on node creation

---

meshroom/ui/qml/Application.qml
meshroom/ui/qml/WorkspaceView.qml
meshroom/ui/qml/main.qml

This PR finishes to separate the content of the application (in opposition to the content of the homepage) from the content of the main window. 
- All the actions, file dialogs and message dialogs that are specific to the application are removed from `main.qml` and placed instead in `Application.qml`.
- Only elements and functions related to the main window remain in `main.qml`. As such, the `ensureSaved` and `ensureNotComputing` functions, used when closing the main window, remain in `main.qml`.
- Message dialogs that may be opened by these functions however are moved to `Application.qml` as they are application-specific and can't be opened on the homepage.
- Application dialogs that may need to be called when triggering the closure of the main window are aliased from `Application.qml` …

[ui] Add proper distinction between the main window and the application

---

meshroom/core/attribute.py
meshroom/ui/graph.py
meshroom/ui/qml/Controls/IntSelector.qml
meshroom/ui/qml/Controls/qmldir
meshroom/ui/qml/GraphEditor/AttributePin.qml
meshroom/ui/qml/GraphEditor/Edge.qml
meshroom/ui/qml/GraphEditor/GraphEditor.qml
meshroom/ui/qml/GraphEditor/Node.qml
meshroom/ui/qml/GraphEditor/TaskManager.qml
meshroom/ui/qml/MaterialIcons/MaterialToolLabel.qml
meshroom/ui/qml/Viewer/SequencePlayer.qml

If you connect a list to an attribute, you can iterate over the list as a for loop.
There is a expand loop button and a collapse one.
For the moment it is not possible to compute all at once but you can see every step.

First version of For Loop implementation

---

meshroom/ui/qml/Application.qml
meshroom/ui/qml/GraphEditor/AttributePin.qml
meshroom/ui/qml/GraphEditor/GraphEditor.qml
meshroom/ui/qml/GraphEditor/Node.qml
meshroom/ui/qml/Viewer3D/MediaLibrary.qml
meshroom/ui/qml/main.qml

This PR fixes the following QML warning:
`QQmlVMEMetaObject: Internal error - attempted to evaluate a function in an invalid context`
which was introduced in #1925 and occurred when edges were being destroyed while the QML context was invalid (meaning the application had entered its closing phase).
The status of the application's window is monitored to detect when it's entering its closing phase (which will lead to the QML context being invalidated). If the window is closing, during the destruction of edges components, no pin operation to re-enable pins will be performed. 
Additionally, this PR also fixes minor QML warnings:
- calls to `hasAttribute` when `currentNode` is `null`
- assignments of `undefined` to edge-related properties when the graph is being updated

[ui] Fix function evaluations in invalid QML context and minor fixes

---

meshroom/ui/qml/GraphEditor/GraphEditor.qml

As `newNodeSubMenu` loses the focus after clicking on it, we do not want to rely on it to display the nodes corresponding to the category.

[ui] Fix click on Category in Node Menu to keep the nodes displayed

---

meshroom/core/desc.py
meshroom/ui/qml/GraphEditor/Node.qml

`exposed` is useful to display the attribute in the upper part of the node in the Graph Editor. Prior to this PR, all outputs attributes were displayed in that part, but only input `File` attributes were as well. Any other input attributes was displayed in the lower part of the node. 
`exposed` is thus useless for output attributes, and is only taken into account for input attributes. By default, only `File` attributes are exposed while all the other attributes are not, in order to preserve the default behaviour we had until now.

[core/ui] "Exposed" property added to attributeDesc

---

meshroom/core/graph.py
meshroom/core/taskManager.py
meshroom/ui/qml/GraphEditor/GraphEditor.qml

- Recompute and Re-Submit not allowed for Compatibility Nodes because they are not computable nodes

Fix Several Compatibility Nodes Operations

---

meshroom/ui/qml/GraphEditor/AttributeItemDelegate.qml
meshroom/ui/qml/GraphEditor/AttributePin.qml

Under the mouse position to be sure it doesn't slide on the screen, there were some problems for the elements in list attributes such as intrinsics.
Also, it fixes dangerous behavior that displays the tooltip on the mouse position.

[AttributeItemDelegate] Position the attribute description tooltip

---

meshroom/ui/qml/main.qml

imagesFolder is in Application.qml and not in main.qml so we need to access it through current item of the stack.
Also in order to have clear code, addition of comments.

[main] Fix imagesFolder variable in order to save when gallery is not empty

---

meshroom/pipelines/cameraTrackingWithoutCalibration.mg
meshroom/pipelines/nodalCameraTrackingWithoutCalibration.mg

This PR updates the "Camera Tracking Without Calibration" and "Nodal Camera Tracking Without Calibration" templates by adding an `ExportDistortion` node to them and connecting its output (which includes a LensDistortion Nuke node) to the `Publish` node.

[pipelines] Add distortion export for templates without calibration

---

meshroom/core/__init__.py

This PR checks that the paths provided as template folders (through the `MESHROOM_PIPELINE_TEMPLATES_PATH` environment variable) exist before attempting to load templates in them. 
Performing this check allows to simply print an error and carry on with the initialisation, while Meshroom was crashing during startup prior to this PR.

[core] Check provided template folder exists before attempting to load it

---

meshroom/nodes/aliceVision/LdrToHdrCalibration.py
meshroom/nodes/aliceVision/LdrToHdrMerge.py
meshroom/nodes/aliceVision/LdrToHdrSampling.py

Use alicevision bindings instead of meshroom python code for brackets estimation, thus factorizing the logic in a unique place.
Related AliceVision pull request: https://github.com/alicevision/AliceVision/pull/1751

[nodes] Use bindings for hdr brackets estimation

---

meshroom/ui/qml/Viewer3D/MediaLibrary.qml
meshroom/ui/qml/Viewer3D/MediaLoader.qml
meshroom/ui/qml/Viewer3D/SfmDataLoader.qml
meshroom/ui/qml/Viewer3D/Viewer3D.qml

Previously, picking was working by luck.
- I removed the center point selection using double click which was not working and created side effects
- The center point selection is now only active when using CTRL modifier
- Camera picking is disabled if CTRL modifier is active
- I doubled the picking area of the camera for easier picking (using an invisible box).

Change picking behavior for qt6 upgrade

---

meshroom/nodes/aliceVision/LightingCalibration.py

This PR excludes the `lightingEstimationVisualization` output attribute from the command line. Without it, the node cannot be run as the AliceVision binary does not expect such an attribute in its command line.

[nodes] `LightingCalibration`: Exclude visualization output from command line

---

meshroom/nodes/aliceVision/LdrToHdrCalibration.py
meshroom/nodes/aliceVision/LdrToHdrMerge.py
meshroom/nodes/aliceVision/LdrToHdrSampling.py

Since `pyalicevision`, which is provided outside of Meshroom's repository, is now needed for all the LdrToHdr nodes, importing `pyalicevision` at the function level rather than at the file level allows the CI to pass even if `pyalicevision` is not available.
This PR does not fix the import and use of these nodes in Meshroom if `pyalicevision` is unavailable.

[nodes] LdrToHdr: Move import of `pyalicevision` within functions

---

meshroom/nodes/aliceVision/Publish.py
meshroom/ui/qml/GraphEditor/AttributePin.qml
meshroom/ui/qml/GraphEditor/GraphEditor.qml
meshroom/ui/qml/Homepage.qml
meshroom/ui/qml/Viewer/SequencePlayer.qml

This PR contains various minor UI fixes:
1. The `inputFiles` parameter in the `Publish` node is exposed, in order to get a display that's identical to what we had prior to #2528.
2. ~~Following the introduction of the homepage, the "application" part of Meshroom could not correctly be resized: if the size of the window was changed while the stack view was displaying the application, the content of the view was fitted vertically, but never horizontally. The window is now filled both vertically and horizontally for the application, just as it was for the homepage.~~ Fixed with #2568. 
3. The split view of the homepage that contains all the logos had a minimal size that could lead to all these logos being hidden. The minimal size now is adjusted to ensure that everything is properly fitted. …

[ui] Various minor UI fixes

---

meshroom/core/node.py

This PR fixes an error that occurred when a template contained a node whose type is unknown. 
Since all the templates that present compatibility issues are automatically upgraded, the nodes that triggered the "unknown node type" compatibility issue were upgraded, and the upgrade failed as there was no existing description for that kind of node.
For templates, the upgrade is now only performed if any compatibility issue but the "unknown node type" one exists.

[core] Node: Do not automatically upgrade unknown nodes in templates

---

meshroom/nodes/aliceVision/DepthMapRendering.py
meshroom/nodes/aliceVision/NormalMapRendering.py

Generate synthetic depthmaps using pose and intrinsics from sfmData and a mesh.
If the sfmData contains n views with pose and intrinsics then this node will generate n depthmaps
See https://github.com/alicevision/AliceVision/pull/1752

Generate depthmaps from sfmData and mesh

---

meshroom/nodes/aliceVision/PanoramaInit.py
meshroom/nodes/aliceVision/PanoramaPostProcessing.py

- display contact sheets when double clicking on panoramaInit
- display panorama preview and not the full resolution when double clicking on panoramaPostProcessing

Update panorama display

---

meshroom/core/attribute.py
meshroom/core/node.py
tests/conftest.py
tests/test_nodeAttributeChangedCallback.py

This PR aims to improve attribute value change propagation, introduced with the concept of "onAttributeChanged" callback system on node descriptors.
The goal is to fix data model access issues happening randomly in Meshroom, leading to broken UI components as shown below in the ImageGallery:
Part of the current implementation lives in the Attribute class, binding the `valueChanged` signal to a slot directly within the class constructor. This seems to be the root issue that breaks Qt's evaluation system.
This PR move that connection logic to the `attributeFactory` function, and bind it to a slot defined on the `Node` class, where all the attribute callback and value change propagation is now dealt with.
Unit tests were added to validate the expected behavior of this system.
And while not …

Fix attribute value change propagation and callback handling

---

meshroom/nodes/aliceVision/SfMChecking.py
meshroom/nodes/aliceVision/SfmChecking.py

New node to check if the sfmData fullfills a set of constraints. Avoid unnecessary computations.

Creation of the sfm Checking node

---

meshroom/pipelines/cameraTracking.mg
meshroom/pipelines/cameraTrackingWithoutCalibration.mg
meshroom/pipelines/nodalCameraTracking.mg
meshroom/pipelines/nodalCameraTrackingWithoutCalibration.mg
meshroom/pipelines/photogrammetryAndCameraTracking.mg

Split the node ImageSegmentationPrompt of all tracking pipelines in 2 nodes, ImageDetectionPrompt + ImageSegmentationBbox in order to enable some processing on bounded boxes.

Tracking pipelines segmentation update

---

meshroom/ui/app.py
meshroom/ui/qml/Viewer/SequencePlayer.qml
meshroom/ui/qml/Viewer/Viewer2D.qml

Use the newly updated sequence player
See https://github.com/alicevision/QtAliceVision/pull/76

Use the new sequence player

---

meshroom/ui/qml/Viewer3D/DefaultCameraController.qml

For whatever reason, the logicaldevice does not work on qt 6.7 with the mouse. 
This PR will avoid the problem by using another approach

[qt6]|Viewer3D] Fix mouse for camera controller

---

meshroom/ui/components/scene3D.py
meshroom/ui/qml/Controls/DirectionalLightPane.qml
meshroom/ui/qml/Controls/qmldir
meshroom/ui/qml/Viewer/PhongImageViewer.qml
meshroom/ui/qml/Viewer/PhongImageViewerToolbar.qml
meshroom/ui/qml/Viewer/Viewer2D.qml
meshroom/ui/qml/Viewer3D/Inspector3D.qml
meshroom/ui/qml/Viewer3D/Viewer3D.qml
meshroom/ui/qml/Viewer3D/Viewer3DSettings.qml
meshroom/ui/qml/Viewer3D/ViewpointCamera.qml

**Add the new QtAliceVision 2D viewer with toolbar and a new light direction controller.**
<p align="center"><img src="https://github.com/alicevision/Meshroom/assets/16002026/b017f244-0452-4440-826d-f4b249f4dcc1" width=40%> <img src="https://github.com/alicevision/Meshroom/assets/16002026/5b52e62c-2887-4cd9-8709-0009414c3791" width=40%></p>
<p align="center"><i>A normal map with two light directions.</i></p>
**Add the ability to change the camera-relative light direction in the 3D viewer**
<p align="center"><img src="https://github.com/alicevision/Meshroom/assets/16002026/7d9527f7-d2c6-4669-807d-a178cbae7ddc" width=40%> <img src="https://github.com/alicevision/Meshroom/assets/16002026/8ff7194f-313a-4819-92e3-48930d74784b" width=40%></p>
<p align="center"><i>Same object with two different …

[ui] Add and improve multiple UI tools for Photometric stereo

---

meshroom/core/exception.py
meshroom/core/graph.py
meshroom/core/node.py
tests/test_compatibility.py
tests/test_nodeAttributeChangedCallback.py

Ensure attribute changed callbacks are not triggered on graph loading.
When loading a graph, we expect nodes to be deserialized in the exact state they were saved.
Attribute callbacks may modify attribute values and impact the UID of the nodes.
This was leading to UID compatibility conflicts on file opening, for Graph containing Nodes using such mechanisms.
While this behavior was covered by a test, it turned out to be a false positive.
The error was hidden behind the fact that the tested Node was actually UID conflicting due to the callback, and swapped to a Compatibility Node. Therefore, attribute values were restored to the serialized ones, with expected values.
The introduction of the "strictCompatibility" mode allows to test this behavior more efficiently.

Discard attribute changed callbacks during graph loading

---

meshroom/pipelines/photogrammetryAndCameraTracking.mg

This PR enables the inversion of masks and keeps the same filename for all the masks that are generated with the `ImageSegmentationBox` node in the "Photogrammetry and Camera Tracking" template.

[pipelines] PhotogCamTrack: Invert masks for segmentation

---

meshroom/ui/qml/Controls/ExpandableGroup.qml
meshroom/ui/qml/GraphEditor/Edge.qml
meshroom/ui/qml/Homepage.qml
meshroom/ui/qml/MaterialIcons/MaterialToolLabel.qml
meshroom/ui/qml/Viewer/SfmGlobalStats.qml
meshroom/ui/qml/Viewer/SfmStatsView.qml
meshroom/ui/qml/Viewer3D/Inspector3D.qml
meshroom/ui/qml/WorkspaceView.qml

This pull request fixes several minor UI issues following the merge of Qt 6:
- Correctly set the color of `MaterialToolLabels` (already existed before the merge of Qt 6);
- Explicitly set the color for the label of resectioned cameras in the Inspector3D;
- Fix the icon on the "Support AliceVision" button;
- Fix the icons in the grid view of projects on the Homepage;
- Use the correct style (Fusion) in the Inspector3D instead of Material;
- Add the missing imports to correctly display graphs related to the SfM statistics in the 2D Viewer;
- Fix the MouseArea located on the header of the expandable groups in the Inspector3D.

[ui] Minor UI stabilization fixes for Qt 6

---

meshroom/ui/reconstruction.py

Camera field of view was wrongly setup for images where the height was larger than the width.
Update fieldofview estimation function.

[ui] Fix field of view functions for tall images

---

meshroom/ui/qml/Viewer3D/Viewer3D.qml
meshroom/ui/reconstruction.py

Make sure pixel aspect ratio is used inside 3d viewer (when viewing through camera)
Associated to https://github.com/alicevision/AliceVision/pull/1745

[Viewer3D] Apply the pixel aspect ratio for the Frame Overlay

---

meshroom/ui/qml/GraphEditor/Node.qml

If unexposed attributes (ie. attributes that are located in the lower side of a node, and hidden by default) are connected, they are meant to remain visible even if the lower part of that node is hidden.
This was working fine for any attribute that was not a `ListAttribute`, as the check was made on whether the attribute's value was a link to another attribute. For `ListAttributes`, whose value is actually a list of values, this was not working as nested links were not checked.
Instead of relying on the `isLink` property, we now use `isLinkNested`: for regular attributes, this is equivalent to using `isLink`, but for `ListAttributes`, the full list of values will be checked.

[GraphEditor] Node: Check if unexposed `ListAttributes` contain links

---

meshroom/ui/qml/Controls/SearchBar.qml
meshroom/ui/qml/GraphEditor/GraphEditor.qml
meshroom/ui/qml/GraphEditor/NodeEditor.qml
meshroom/ui/qml/ImageGallery/ImageGallery.qml

* Search bar can now be toggled with the Search Button.
* The GraphEditor had an obstructive search before and now it is clubbed with the bottom panel options.
* The Search Bar now supports "Return Key Press" to move on the next filtered item in the Graph Editor.
* Search Bar also gets a clear text action when text is entered in the field.
* Updated SearchBar in ImageGallery, Node Editor, 3D Inspector to now be toggled.

[ui] Improve Search Bar component

---

meshroom/ui/qml/Application.qml

Validating the filename to ensure that the file does not gets saved with just the extension
* Added a Validation to the file and template save process to ensure we have a valid filename to save to and not just the extension in the saved filename.
* The validation process involves showing up a dialog box prompting user to provide a correct filename to save. This dialog box is recurring till the time a valid filename is entered for saving the file.

[BugFix] File save dialog now requires a valid filename

---

meshroom/ui/qml/GraphEditor/Edge.qml

This pull request correctly updates the mouse area over edges when nodes these edges are connected to have been moved. 
Prior to it, the mouse area of each edge was set once and never updated afterwards, meaning the edge remained selectable if and only if it did not move too much from its original position. The curve scale of the mouse area is now recomputed every single time the size of its edge has changed (i.e. whenever a node it is connected to has been moved).

[GraphEditor] Edge: Correctly update the `EdgeMouseArea` when moving nodes

---

.git-blame-ignore-revs
meshroom/common/qt.py
meshroom/ui/components/__init__.py
meshroom/ui/components/geom2D.py
meshroom/ui/graph.py
meshroom/ui/qml/Application.qml
meshroom/ui/qml/Controls/DelegateSelectionBox.qml
meshroom/ui/qml/Controls/SelectionBox.qml
meshroom/ui/qml/Controls/qmldir
meshroom/ui/qml/GraphEditor/GraphEditor.qml
meshroom/ui/qml/GraphEditor/Node.qml

This PR addresses several issues related to the Node selection management, mostly related to performance and user experience.
This PR changes the selection management backend to use QItemSelectionModel, instead of manually maintaining an extra QObjectListModel. This allows to rely on Qt to perform selection commands (ClearAndSelect, Deselect, Toggle..).  
It also fixes the main issue of having a lot of properties binding to the selection model, which was on top of that emitting its notify signal way to often.
The node context menu was one of the most costly component, due to many direct bindings it had with the selection model.  
And it was created at application startup and living until application shutdown, even if unused.
It is now created dynamically only when explicitly required, and …

Refactor Node selection for better UX and performance

---

meshroom/nodes/aliceVision/SfMColorizing.py

Application to colorize the point cloud given the observed images
Same algorithm than the one used at the end of the structureFromMotion node
https://github.com/alicevision/AliceVision/pull/1787

New SfMColorizing Node

---

meshroom/core/graph.py

Add missing return statement to the load function, used by the UI to determine whether the load was successful,
and add the project to the list of recent projects.
#2598 introduced this issue, missing to return the load status.

Fix projects disappearing from the list of recent projects

---

meshroom/ui/qml/GraphEditor/AttributeItemDelegate.qml

This PR fixes an issue with the MaterialIcon label of attributes with dynamic values that have not yet been computed. Following the migration to Qt 6, labels that used the MaterialIcon font without being properly declared as `MaterialLabel` were not correctly displayed. 
<div align="center">Before this PR:<br/>
<div align="center">After:<br/><img src="https://github.com/user-attachments/assets/40ed3239-4f41-4a2c-a587-8230edc3075c" /></div>

[GraphEditor] AttributeItemDelegate: Use MaterialLabel for uncomputed attributes

---

.github/workflows/continuous-integration.yml

CI: add codecov

---

meshroom/ui/qml/GraphEditor/GraphEditor.qml

This PR addresses the Key Handling issue in the Node Creation Menu within the `GraphEditor`.
The changes ensure that the **Enter** and **Return** key events are correctly captured and handled by the Item first and then forwarded to the specified Item i.e. `SearchBar.textField`.
* Fixed the issue with Node creation Menu by setting the `Keys.priority` property to be `Keys.AfterItem`.
Quoting from https://doc.qt.io/qt-6/qml-qtquick-keys.html
```
Default priority ordering is Keys.BeforeItem and has the key event processing as:
1. Items specified in forwardTo
2. Specific key handlers, e.g. onReturnPressed, onPressed, onReleased handlers
3. Item specific key handling (Key handling of the parent item)
Keys.AfterItem has the key event processing as:
1. Item specific key handling (Key handling of …
```

[ui] GraphEditor: Address Key Event Conflicts in Node Menu

---

meshroom/nodes/aliceVision/ExportDistortion.py
meshroom/pipelines/cameraTracking.mg
meshroom/pipelines/cameraTrackingWithoutCalibration.mg
meshroom/pipelines/distortionCalibration.mg
meshroom/pipelines/nodalCameraTracking.mg
meshroom/pipelines/nodalCameraTrackingWithoutCalibration.mg
meshroom/pipelines/photogrammetryAndCameraTracking.mg

In ExportDistortion, add an option to export a nuke file with per frame information about distortion

[nodes] `ExportDistortion`: Add animated distortion option

---

meshroom/ui/components/filepath.py
meshroom/ui/qml/Application.qml

This PR introduces a validation check to enhance the user experience by showing a warning popup when saving a file/template to a directory which is either not present or is not accessible to the user for writing to it.
Added an `accessible` helper to validate whether a given directory to save to is accessible for the user.
Updated the common `validateFilepathForSave` function to ensure the user has permission to save to the provided path.
This works in two ways, if either the directory the user is trying to save to does not exist it will return false, and the warning dialog shows up, or in case the user does not have access to writing to the directory also prompts the warning dialog.

[ui] Add Validation for Save file path accessibility

---

meshroom/core/graph.py
meshroom/ui/qml/Application.qml
meshroom/ui/qml/GraphEditor/NodeEditor.qml
meshroom/ui/qml/GraphEditor/StatViewer.qml

This PR addresses an issue with the Node Editor, where the selected tab was not getting retained when switching between selected nodes.
~- Introduced the `currentProjectChanged` signal which is meant to trigger update on various components when the scene is changed~
~- Currently the `onCurrentProjectChanged` slot is linked to refreshing the NodeEditor tabs.~
Updated the event trigger to be `onVisibleChanged` rather than `onIsComputableChanged` as the latter does not get triggered when there is no node selected and then an incomputable node gets selected but the value of isComputable remains the same.
Visibility acts as a better trigger in my view, getting triggered when a node gets selected or deselected.
The condition is also updated to check if the current tab is not valid for the …

[ui] NodeEditor: Addressed Tab Retention when switching Node selection

---

meshroom/env.py
meshroom/ui/app.py

This PR adds the required setup to be able to attach the QML debugger/profiler to Meshroom.
QML debugging can be activated using the environment variable
```
MESHROOM_QML_DEBUG=1
```
And optionally configured using (with params as expected by [-qmljsdebugger](https://doc.qt.io/qt-6/qtquick-debugging.html#starting-applications)):
```
MESHROOM_QML_DEBUG_PARAMS=port:5555
```
The help of those environment variables can be accessed via CLI using:
```bash
> meshroom --env-help
Meshroom environment variables:
MESHROOM_QML_DEBUG: Enable QML debugging (bool, default: 'False')
MESHROOM_QML_DEBUG_PARAMS: QML debugging params as expected by -qmljsdebugger (str, default: 'port:3768')
```
This can be used to attach the QML debugger from Qt Creator, using:
```
Debug > Start Debugging > Attach to QML …
```

Add support for QML debugging/profiling

---

meshroom/ui/qml/GraphEditor/AttributeItemDelegate.qml
meshroom/ui/qml/GraphEditor/NodeEditor.qml
meshroom/ui/qml/GraphEditor/ScriptEditor.qml

Minor fixes related to the injection of parameters into signal handlers, which is not supported anymore on Qt6.

[GraphEditor] Fix injections into signal handlers with JS functions

---

meshroom/nodes/aliceVision/CameraInit.py
meshroom/pipelines/cameraTracking.mg
meshroom/pipelines/cameraTrackingWithoutCalibration.mg
meshroom/pipelines/distortionCalibration.mg
meshroom/pipelines/hdrFusion.mg
meshroom/pipelines/multi-viewPhotometricStereo.mg
meshroom/pipelines/nodalCameraTracking.mg
meshroom/pipelines/nodalCameraTrackingWithoutCalibration.mg
meshroom/pipelines/panoramaFisheyeHdr.mg
meshroom/pipelines/panoramaHdr.mg
meshroom/pipelines/photogrammetry.mg
meshroom/pipelines/photogrammetryAndCameraTracking.mg
meshroom/pipelines/photogrammetryDraft.mg
meshroom/pipelines/photometricStereo.mg

Add the model to the list in camera init.
See https://github.com/alicevision/AliceVision/pull/1801

Add equirectangular camera model in `CameraInit`

---

meshroom/ui/components/__init__.py
meshroom/ui/components/scriptEditor.py
meshroom/ui/qml/Application.qml
meshroom/ui/qml/GraphEditor/ScriptEditor.qml

* Script Editor now retains history of the code which is executed across Meshroom sessions.
* Script Editor also highlights the code Syntax for Python
* The output clearly distinguishes between executed code and the result of the code with different colors.

[ui] Python Script Editor Improvements

---

meshroom/nodes/aliceVision/ExportMatches.py
meshroom/nodes/aliceVision/RelativePoseEstimating.py
meshroom/nodes/aliceVision/SfmBootstraping.py
meshroom/nodes/aliceVision/SfmExpanding.py
meshroom/pipelines/nodalCameraTracking.mg
meshroom/pipelines/nodalCameraTrackingWithoutCalibration.mg

see https://github.com/alicevision/AliceVision/pull/1803
This PR add a set of features to enable use of lidar measures as smooth constraints on the landmark positions.
Assumes one frame of the sequence is correclty aligned with the lidar geometric frame.
Assumes the camera calibration is fully and precisely known.
Use Mesh generated from lidar to fetch 3D point for a given 2D landmark by point back projection.

Update sfm pipeline to accept meshes

---

meshroom/ui/qml/ImageGallery/ImageGallery.qml
meshroom/ui/qml/ImageGallery/IntrinsicDisplayDelegate.qml

This pull request fixes a crash that occurred when the Application view of Meshroom was being displayed without displaying the Homepage beforehand (e.g. when opening a file at Meshroom's launch with the command line, when switching from one color palette to another, when using the QML hot reload).
Under these conditions, the `TableModel` containing the intrinsics was being filled (with attempts to add rows) before the component itself had been fully instantiated.
We now forbid the model to be populated unless the component is ready. Additionally, we now use Meshroom's palette to set the color of the intrinsics attributes in the `TableView` instead of hardcoding them to "white".
The `TableModel` for intrinsics now has a `ready` property that is set to `true` only once its …

[ImageGallery] Intrinsics table: Always fully instantiate the model before populating it

---

meshroom/nodes/aliceVision/SfMMerge.py

See https://github.com/alicevision/AliceVision/pull/1807
Previous sfmMerge was only accepting 2 sfmData.
Here we enable use of N>0 sfmData.

Enable merge of multiple sfmDatas

---

meshroom/ui/qml/GraphEditor/GraphEditor.qml

This PR adds functionality to consider the Selected Nodes when calling `fit` in the **GraphEditor**.
This change ensures that if there is a node selection available, GraphEditor is fit to the selected Nodes and if not, the fit considers all of the available nodes in the Graph to fit to that bounding box.
Considering the selectedNodes' bounding box when a node selection exists to reuse the same shortcut `F`

Enable Fitting of selected Nodes in the Graph Editor when Fit is invoked 

---

meshroom/ui/components/edge.py
meshroom/ui/qml/GraphEditor/Edge.qml

~~Event::button() was sometimes causing a crash, copying the event and using event.buttons() from the copied event seems to be stable before calling event.button() eventually~~
This PR addresses a known crash issue with the EdgeMouseArea (QQuickItem)'s mousePressEvent.
The crash occurs when querying button() from the event.
The event is not null and is able to provide other data correctly before ending up crashing when queried for button.
~~Current Fix is based on copying the provided event and calling event.buttons() to check if the buttons are supported and then calling button() is the custom MouseEvent constructor.~~
This seems to have stopped the crashes for now, but still testing on larger scale is pending before we confirm anything.

[ui][fix] Edge: Fixing an issue with mouse event on Custom EdgeMouseArea causing Crash

---

meshroom/ui/app.py
meshroom/ui/qml/Homepage.qml

This pull request addresses some performance issues that were detected when interacting with the list of recent project files.
It mostly focuses on refactoring the access to the list of recent project files, which involved reading the QSettings every single time the content of the list was to be accessed, and accessing it far too many times. 
It also decouples the need for thumbnails between the homepage and the application: while the homepage needs access to thumbnails (if available) to set up the list of recent project files, the application has no use for them. When the list of project files is edited, there is no need to retrieve the corresponding thumbnail (if it exists) unless the current view is the homepage's.
Finally, it prevents the homepage from performing any such request for …

[ui] Refactor the access to the list of recent project files

---

meshroom/nodes/aliceVision/MaskProcessing.py

See https://github.com/alicevision/AliceVision/pull/1814

Mask processing node

---

meshroom/nodes/aliceVision/ExtractMetadata.py

This PR adds a pure python node dedicated to extract metadata from image files using exifTool. This node can be connected to the cameraInit node and for all images referenced in the "cameraInit.sfm" file, if exifTool is available, a file containing all metadata is generated. The file format can be selected amongst "txt", "xmp", "xml". Be aware that the "xmp" format cannot store all metadata contained in the image file.
The invocated exifTool command depends on the requested file format in the following way:
- "txt": `exiftool [args] imageFile > metadataFile.txt`
- "xml": `exiftool -X [args] imageFile > metadataFile.xml`
- "xmp": `exiftool -tagsfromfile imageFile [args] metadataFile.xmp`
Optional arguments 'args' can be defined through a string parameter of the meshroom node.
The boolean …

Extract more metadata using exifTool

---

meshroom/nodes/aliceVision/ExportMaya.py

Export a maya mel script such that the scene will contains
- The mesh
- The cameras correctly setup'ed
- The background images

Export Maya .mel Script 

---

meshroom/core/attribute.py

This PR adresses performance issues when loading large project files (in UI mode), introduced as part of #2586.
It changes the way a Node is notified of an Attribute value change, which has a great impact on Attribute creation time.
The figures below shows the before and after for a project with a large number of attributes.
**Before**
Overall attribute creation time: 146s
**After**
Overall attribute creation time: 1.24s
The notification of attribute value change to the owning node has been reworked to use a Signal/Slot connection, rather than a Signal/lambda.
This leads to much better performance, while preserving the same behavior.

Fix: Improve large project file loading performance

---

meshroom/nodes/aliceVision/SfMPoseInjecting.py
meshroom/nodes/aliceVision/SfmBootstraping.py
meshroom/nodes/aliceVision/SfmExpanding.py
meshroom/pipelines/cameraTrackingExperimental.mg
meshroom/pipelines/cameraTrackingWithoutCalibrationExperimental.mg
meshroom/pipelines/photogrammetryAndCameraTrackingExperimental.mg
meshroom/pipelines/photogrammetryExperimental.mg
meshroom/ui/reconstruction.py

- Create experimental pipelines templates for 
1. tracking
2. tracking without calibration
3. photogrammetry
4. photogrammetry with tracking
- Update meshroom to consider the new sfm Nodes as if it was the previous StructureFromMotion node
Requires https://github.com/alicevision/AliceVision/pull/1818

Create new pipeline for testing modular sfm

---

meshroom/core/node.py

Improve propagation of attribute value change signals to get proper UI update.
Propagate attribute value changes downstream using `valueChanged` signal emission, instead of calling `_onAttributeChanged` directly. 
This does not change the current core behavior, but it triggers the property notification signal when in UI mode.
This makes changes happening upstream properly reflected in downstream nodes.

Node: Propagate attribute change via `valueChanged` signal

---

meshroom/ui/qml/Controls/FilterComboBox.qml
meshroom/ui/qml/GraphEditor/AttributeControls/Choice.qml
meshroom/ui/qml/GraphEditor/AttributeControls/ChoiceMulti.qml
meshroom/ui/qml/GraphEditor/AttributeItemDelegate.qml

Re-design the UI control for editing a ChoiceParam.
The exclusive ChoiceParam component has been resigned to address multiple issues with the current controls.
This component has been redesigned to display custom values outside the range of possible values.
That may happen when a node description is modified and potentially discard already serialized value in existing scenes.
This can be tried out by pasting this code snippet in Meshroom's script editor:
```python
from meshroom.ui import uiInstance
graph = uiInstance.activeProject
node = graph.addNewNode("FeatureExtraction")
graph.selectedNode = node
graph.setAttribute(node.describerTypes, ["other", "custom"])
```
Rely as much as possible on the behaviors provided by the default ComboBox component to avoid custom logic for e.g keyboard …

UI: Redesign ChoiceParam UI component

---

meshroom/ui/app.py

Fix Meshroom app CLI `latest` option that was raising an error.
Fix code that was not converted when _recentProjectFiles was converted from a function to a member variable.

Fix Meshroom App CLI `latest` option

---

meshroom/core/desc/node.py
meshroom/core/graph.py
meshroom/core/node.py
tests/test_nodeCallbacks.py

This PR changes the logic of when node descriptors `onNodeCreated` callbacks are triggered.
`desc.Node.onCreated` callback is a hook in the Node API for developers to write custom behavior on a node first initialization. 
By being called in the core.Node constructor, this was triggered in several situations that don't match this idea and with unpredictable side effects (graph loading, node re-creation on undo...).
This changes this behavior to only trigger this callback for explicit node creation:
- when a new node is added to a graph
- for each node created when a graph is initialized from a template
* Make `onNodeCreated` callback an explicit method on desc.Node.
* Remove the call to node descriptor's `onNodeCreated` callback outside core.Node constructor.
* Trigger this callback on …

NodeAPI: Trigger node creation callback only for explicit new node creation

---

meshroom/ui/app.py

This PR moves the QML registration of components before the instantiation of the QML engine. 
Functionally speaking, this does not change anything as Qt 6.6.x supports the registration of all types, including singleton, even after the instantiation of the engine, but this will not be the case anymore with Qt 6.7.x and above.

[ui] app: Register components to QML before instantiating the engine

---

meshroom/nodes/aliceVision/ExportMaya.py
meshroom/nodes/aliceVision/ExtractMetadata.py
meshroom/nodes/aliceVision/MaskProcessing.py
meshroom/pipelines/cameraTrackingExperimental.mg
meshroom/pipelines/cameraTrackingWithoutCalibrationExperimental.mg
meshroom/pipelines/photogrammetryAndCameraTrackingExperimental.mg
meshroom/pipelines/photogrammetryExperimental.mg

This PR realigns all nodes and applies the correct colors on them for the following experimental pipelines:
- Camera Tracking
- Camera Tracking without calibration
- Photogrammetry
- Photogrammetry & Camera Tracking
Additionally, the labels and descriptions of some attributes for the `ExportMaya` and `ExtractMetadata` nodes are improved.

[pipelines] Experimental: Align and set colors for all nodes

---

meshroom/ui/qml/Application.qml
meshroom/ui/qml/GraphEditor/GraphEditor.qml

This PR fixes QML warnings that are generated when project files are dropped into the Graph Editor.

[qml] Fix QML warnings when dropping project files into the Graph Editor

---

meshroom/core/attribute.py
meshroom/core/desc/attribute.py
tests/test_attributeChoiceParam.py

This PR extends the current behavior of ChoiceParam by allowing node developers to save the list of values if they have been overridden at runtime.
Introduce a new `saveValuesOverride` parameter on desc.ChoiceParam to define whether to serialize the list of possible values if they have been overridden at runtime.
If that is set to True, the ChoiceParam instance is serialized as a dictionary containing both the value and list of possible values.

ChoiceParam: add option to serialize overriden values

---

meshroom/nodes/aliceVision/ExportImages.py
meshroom/nodes/aliceVision/IntrinsicsTransforming.py

See https://github.com/alicevision/AliceVision/pull/1828

[nodes] Add nodes for versatile image exporting

---

meshroom/core/node.py

Prior to this PR, nodes with a varying number of chunks were initialized with an empty list of chunks (as expected), but with a global status that was set to `SUCCESS` instead of `NONE`. 
This caused issues on the graphical side as `SUCCESS` is interpreted as the status for nodes that have been successfully computed. For nodes that had not been computed and whose number of chunks was not set yet, we thus ended up with computation times (set to "0.00s", as no actual computation had taken place) displayed as if said computation had been successful:
<div display="block" align="center"><img src="https://github.com/user-attachments/assets/32f36030-3a7a-4eb0-bb8f-bb8f6ca02e1c" /></div>
This PR addresses this issue by ensuring that the global status of a node with an empty list of chunks is …

[core] Node: Status should be `NONE` when there is no chunk

---

README.md

Change the git clone link under the "get the project" section to use the https github link, as the git link will not work in many circumstances. The https link should work universally
No features have been added
No remarks

change git clone link to use https link in "get the project"

---

bin/meshroom_batch

Following the removal of `meshroom.core.defaultCacheFolder` in #2703, this PR removes it fully from `meshroom_batch`, which kept on using it as the default value for the `--cache` option. Instead, `""` is used as a default value, as it is in `meshroom.core`.

[bin] `meshroom_batch`: Stop using removed `defaultCacheFolder`

---

meshroom/core/desc/node.py

This PR fixes an issue that occurs only on Windows when executing nodes, following #2703.
The `CREATE_NEW_PROCESS_GROUP` flag must be added to the list of creation flags when doing the `Popen` to ensure that the process to execute will not be fully detached (and hence will be killable). However, `psutil` does not contain any creation flags, instead supporting those from `subprocess` (https://psutil.readthedocs.io/en/stable/#psutil.Popen).
Prior to this PR, attempting to use `psutil.CREATE_NEW_PROCESS_GROUP` would cause an error on the execution for all the node processes as it did not exist. This PR replaces it by `subprocess.CREATE_NEW_PROCESS_GROUP`, effectively creating the process with the correct status. It is worth noting that `subprocess.CREATE_NEW_PROCESS_GROUP` is imported within …

[desc] Import `CREATE_NEW_PROCESS_GROUP` flag from `subprocess`

---

meshroom/core/attribute.py
meshroom/ui/qml/Application.qml
meshroom/ui/qml/GraphEditor/AttributeEditor.qml
meshroom/ui/qml/GraphEditor/AttributeItemDelegate.qml
meshroom/ui/qml/GraphEditor/NodeEditor.qml
tests/test_attributes.py

Add navigation buttons around attributes label in the `AttributeEditor`
If an attribute have linked attributes:
- a button appear on the left of the label, for input attributes
- a button appear on the right of the label, for output attributes

[ui] AttributeEditor: Feature/attribute navigation buttons

---

meshroom/ui/qml/Viewer/FeaturesInfoOverlay.qml
meshroom/ui/qml/Viewer/Viewer2D.qml
meshroom/ui/reconstruction.py

This PR enable the loading and display of tracks in the experimental pipeline (using pre computed json tracks files).
Also add the list of providers in the feature overlay

[ui] Viewer2D can display the content of tracks files

---

meshroom/ui/reconstruction.py

This PR fixes an issue introduced in cfd2b1e00aa7d99e7ed7a696395a53b2bee38aca which changes the `clear()` method from the `Reconstruction` class from a slot to a regular method. 
If `clear()` is not a slot, it cannot be called from the QML side. In practice, it made the "Home" button ineffective from the Application; once the Homepage had been left, it could not be returned to.

[ui] Reconstruction: Restore the `Slot` status of the `clear` method

---

meshroom/core/node.py

If a node has only one chunk, then getFusedStatus returned a reference (not a copy) which is then modified by getRecursiveFusedStatus() which considered it was a copy.

Fix elapsed time when there is only one chunk

---

meshroom/core/node.py

This PR allows to stop the computation of a pure python node when processing locally. Before, the ExecMode status was reset to NONE when starting the computation in the subprocess. ExecMode is not a dynamic value, it has been removed from the resetDynamicValues method and set only at initialization.

bugfix ExecMode status

---

meshroom/ui/qml/GraphEditor/NodeStatus.qml

Node status tab was not updated during node status changes.

[ui] Update node status when modified

---

meshroom/ui/components/edge.py
meshroom/ui/graph.py
meshroom/ui/qml/Controls/DelegateSelectionLine.qml
meshroom/ui/qml/Controls/SelectionLine.qml
meshroom/ui/qml/Controls/qmldir
meshroom/ui/qml/GraphEditor/Edge.qml
meshroom/ui/qml/GraphEditor/GraphEditor.qml
meshroom/ui/qml/GraphEditor/Node.qml

This PR introduces various methods to remove Node edges within the Graph. These methods enhance the usability of the Node Graph by providing users with multiple options to managed node egde connections.
The various methods include,
* Context Menu Change -> Right click on an edge now shows a popup.
* Fix -> Alt + Click on the Edge was not working after Qt6 Migration and is now fixed.
* Added functionality to remove all incoming and outgoing connections of nodes which are not present in the current selection
* This feature can be accessed using various ways, Right click on Node > Disconnect Node(s)
* Selecting Node(s) and Pressing `X` on the Keyboard
* Selecting Node(s) and shaking them.
* Another way is to Press and Hold `Ctrl` and `Alt` on the Keyboard and Left click + Drag on the edges, …

[ui]: Introduction of multiple ways to remove Node Edges

---

meshroom/ui/qml/Viewer/Viewer2D.qml

Remove targetSize, this has been replaced by resizeRatio a long time ago.
See also https://github.com/alicevision/QtAliceVision/pull/85

[fix] remove targetSize in viewer2d which was removed in qtAliceVision

---

meshroom/core/test.py

This PR removes the import of `unregisterNodeType` from the test on templates, as the method has been removed from `meshroom.core` and is now part of the PluginManager.

[core] Templates test: Remove outdated `unregisterNodeType` import

---

.git-blame-ignore-revs
.github/workflows/continuous-integration.yml
meshroom/core/__init__.py
meshroom/core/attribute.py
meshroom/core/desc/node.py
meshroom/core/graph.py
meshroom/core/graphIO.py
meshroom/core/plugins.py
meshroom/env.py
tests/conftest.py
tests/plugins/meshroom/pluginA/PluginANodeA.py
tests/plugins/meshroom/pluginA/PluginANodeB.py
tests/plugins/meshroom/pluginB/PluginBNodeA.py
tests/plugins/meshroom/pluginB/PluginBNodeB.py
tests/test_attributeChoiceParam.py
tests/test_attributes.py
tests/test_compatibility.py
tests/test_graphIO.py
tests/test_invalidation.py
tests/test_listAttribute.py
tests/test_nodeAttributeChangedCallback.py
tests/test_nodeCallbacks.py
tests/test_nodeCommandLineFormatting.py
tests/test_plugins.py
tests/utils.py

This PR builds on top of #2703 and #2733, which respectively added the notion of local isolated computations for nodes, and the concept of plugins. This pull request adds the notion of runtime-specific environment, allowing nodes to be executed in a dedicated environment that contains their required dependencies independently from Meshroom's. 
Two types of execution environments are added in this PR:
1. **DirTreeProcessEnv**
Based on the root folder of the plugin, it sets up the environment (`PYTHONPATH`, `PATH` and `LD_LIBRARY_PATH` environment variables). It assumes the plugin has a standard hierarchy:
```
mrPlugin/
|-- bin
|-- lib
|   `-- pythonX.X
|       `-- site-packages
|           |-- anotherModule
|           `-- myCustomModule
`-- meshroom
|-- myNodes
|   |-- NodeA.py
|   |-- …
```

[core] Runtime-specific environments support

---

meshroom/core/__init__.py

This PR removes the check in the "meshroom/pipelines" folder when looking for templates. The folder has been removed when ndoes have been moved out from Meshroom, therefore there's no need to look in it anymore. By doing so, we remove the error message that was generated precisely because the "meshroom/pipelines" folder did not exist.

[core] Stop checking for templates in "pipelines" folder

---

meshroom/ui/qml/Viewer/HdrImageToolbar.qml
meshroom/ui/qml/Viewer/Viewer2D.qml

In viewer2D, using keyboard shortcuts break the channelBox combobox
Add functions to let the component internally manage the way it set the channel

[ui] [fix] Viewer2D: using the keyboard shortcuts (r,g,b,a) break the channelBox combobox

---

meshroom/ui/reconstruction.py

This PR fixes a bug introduced by https://github.com/alicevision/Meshroom/pull/2733 which caused the setup of temporary `CameraInit` nodes to fail, as we were attempting to call a method from an object that had not been instantiated yet. 
Temporary `CameraInit` nodes are used, among other things, to display the results of the `LdrToHdrMerge` node in the "Hdr Fusion" pipeline.

[ui] Reconstruction: Fix setup of temporary `CameraInit` nodes

---

meshroom/core/desc/computation.py

By adding `rangeBlocksCount` to `parallelization`, called nodes have knowledge of the number of parallelized chunks. This enable easier estimation of optimal work partition.

[core] Adding rangeBlocksCount to `Parallelization`

---

meshroom/ui/reconstruction.py

The image overlay (see through camera) should work for exportImage node.
**This is a quick and dirty fix,  a refacto is necessary on this area.**
We should use ioc (inversion of control) for this kind of behavior, the system should be able to retrieve nodes that implements some features, and call the the node implementation on runtime. 
The node that implements a feature (ex: provideOverlayImage) is responsible of the implmentaiton (here how to return the image overlay to the system)
- [ X ]  Add the exportImages node to the activeNodes able to provide image to overlay sysgtem.

[ui] fix: Overlay image doesn't work on pipeline "Photogrametry experimental" 

---

INSTALL_PLUGINS.md
meshroom/core/plugins.py

This PR updates the handling and documentation of virtual environments for plugins in the Meshroom project. The changes standardize the naming convention for virtual environments to "venv" (in opposition of giving them the plugin's name) and update the relevant code and documentation accordingly.

[core] plugins: Virtual environments should be named "venv" instead of having the plugin's name

---

meshroom/ui/palette.py
meshroom/ui/qml/Application.qml
meshroom/ui/qml/Controls/MessageDialog.qml
meshroom/ui/qml/GraphEditor/Node.qml
meshroom/ui/qml/GraphEditor/ScriptEditor.qml
meshroom/ui/qml/LiveSfmView.qml
meshroom/ui/qml/main.qml

This pull request introduces several updates to improve UI consistency, enhance styling, and standardize imports across the `meshroom` project. The most significant changes include adjustments to palette colors, layout properties, and shadow effects, as well as the removal of version-specific imports for `Qt.labs.platform`.
* Updated the default text and highlighted text colors in the `defaultPalette` initialization in `meshroom/ui/palette.py` to improve readability. (`[meshroom/ui/palette.pyR45-R46](diffhunk://#diff-f7fe8399c1c9910e333103be4045293618a446507cdf54fe025f3f088e08992eR45-R46)`)
* Modified `GraphEditor/Node.qml` to use `activePalette` for `defaultColor`, `shadowColor`, and `highlightedText` properties, ensuring consistent theming across nodes. …

[qml] Minor UI fixes

---

meshroom/multiview.py
meshroom/ui/graph.py
meshroom/ui/reconstruction.py

This pull request makes improvements to how files and directories are handled and categorized in `meshroom/multiview.py` and `meshroom/ui/reconstruction.py`. The main changes focus on more accurately detecting file types, improving directory traversal (especially for non-recursive cases), and clarifying documentation.
This addresses the frequent error dialog that was raised when dropping a folder that contained other folders: since `hasExtension` attempted to retrieve an extension from folders, it ended up with an empty string that satisfied the `in` requirement when compared to extensions for the panorama pipelines.
**File and directory handling improvements:**
* Updated `hasExtension` to return `False` for directories, ensuring only files are checked for extensions.
* Improved …

Improve behaviour when dropping folders

---

meshroom/core/plugins.py

This pull request makes a minor adjustment to the logging behavior in the `loadConfig` method of `meshroom/core/plugins.py`. The change lowers the logging level from warning to debug for messages about missing resolved paths, reducing noise in the logs for non-critical issues.

[core] plugins: Downgrade the log level when loading the config file

---

INSTALL.md

This pull request updates the `INSTALL.md` documentation to add a new quick start guide, a table of contents, clearer instructions for using prebuilt AliceVision binaries, and streamlined environment variable documentation.
These updates make the installation process more user-friendly and reduce confusion for new contributors.
Relates to https://github.com/alicevision/AliceVision/pull/1952.

[doc] Update `INSTALL.md`

---

meshroom/core/node.py
meshroom/ui/qml/GraphEditor/NodeDocumentation.qml
tests/plugins/meshroom/pluginC/PluginCNodeA.py
tests/test_nodes.py

This PR adds additional information on the Documentation tab of nodes. 
Here are examples :
```py
import os
from meshroom.core import desc
__version__ = "1.0"
__author__ = "moduleauthor"
__license__ = "MIT"
class TestCLNode(desc.CommandLineNode):
category = 'TestPlugin'
commandLine = 'command'
documentation = """# TestCLNode
here are info on the node
Here are more info
1. First step
2. Second step
"""
```
Also we can override parameters at the node level :
- "author" and "version" can be directly overrided
- It is possible to put any additional information in a `__nodeInfo__` list
```py
class TestCLNode2(desc.CommandLineNode):
"""# TestCLNode
here are info on the node
Here are more info
1. First step
2. Second step
"""
category = 'TestPlugin'
author = "Alice"
version = "2.0.0" …
```

[ui] Add additional node information in the documentation tab

---

meshroom/core/plugins.py
meshroom/submitters/simpleFarmSubmitter.py

Force using specific versions on subprocess and simpleFarm jobs.
> [!NOTE]  
> Now, when we submit/compute a node, it uses the current env to select versions that are going to be used.
> However there are several case where we can have a mismatch.
> For example, if `pkg-v` and `pkg-v.1` are deployed and we have `pkg==v` in the current env, then `REZ_RESOLVE` will have resolved `pkg-v` (which is correct) however if we resolve `pkg-v` we won't have the version we want.
Therefore in this PR we propose to fix the packages whose version is taken from the current env and to fix it in the subprocess by using the `==` delimiter.
Also we address some other issues :
- package versions that are explicitely excluded (prefixed by `!`)
- packages with version delimiters different than `-`
- packages …

[core/submitters] Freeze rez plugins dependencies versions in subprocess and farm submitter

---

meshroom/ui/qml/Controls/DirectionalLightPane.qml
meshroom/ui/qml/Viewer/Viewer2D.qml

Various improvements / small fixes for the `PhongImageViewer`.
Linked to QtAliceVision PR: https://github.com/alicevision/QtAliceVision/pull/89

[qml] PhongImageViewer: Various improvements
